// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkFlowBox;

class GtkFlowBox
{
    public static function new_() -> int
    {
        return gtkflowbox_new();
    }

    public static function append(int handle, int child) -> void
    {
        gtkflowbox_append(handle, child);
    }

    public static function getActivateOnSingleClick(int handle) -> bool
    {
        int r;

        let r = gtkflowbox_get_activate_on_single_click(handle);

        return r == 1;
    }

    public static function getChildAtIndex(int handle, int idx) -> int
    {
        return gtkflowbox_get_child_at_index(handle, idx);
    }

    public static function getChildAtPos(int handle, int x, int y) -> int
    {
        return gtkflowbox_get_child_at_pos(handle, x, y);
    }

    public static function getColumnSpacing(int handle) -> int
    {
        return gtkflowbox_get_column_spacing(handle);
    }

    public static function getHomogeneous(int handle) -> bool
    {
        int r;

        let r = gtkflowbox_get_homogeneous(handle);

        return r == 1;
    }

    public static function getMaxChildrenPerLine(int handle) -> int
    {
        return gtkflowbox_get_max_children_per_line(handle);
    }

    public static function getMinChildrenPerLine(int handle) -> int
    {
        return gtkflowbox_get_min_children_per_line(handle);
    }

    public static function getRowSpacing(int handle) -> int
    {
        return gtkflowbox_get_row_spacing(handle);
    }

    public static function getSelectedChildren(int handle) -> array
    {
        var result;

        let result = gtkflowbox_get_selected_children(handle);

        return result;
    }

    public static function getSelectionMode(int handle) -> int
    {
        return gtkflowbox_get_selection_mode(handle);
    }

    public static function insert(int handle, int widget, int position) -> void
    {
        gtkflowbox_insert(handle, widget, position);
    }

    public static function invalidateFilter(int handle) -> void
    {
        gtkflowbox_invalidate_filter(handle);
    }

    public static function invalidateSort(int handle) -> void
    {
        gtkflowbox_invalidate_sort(handle);
    }

    public static function prepend(int handle, int child) -> void
    {
        gtkflowbox_prepend(handle, child);
    }

    public static function remove(int handle, int widget) -> void
    {
        gtkflowbox_remove(handle, widget);
    }

    public static function removeAll(int handle) -> void
    {
        gtkflowbox_remove_all(handle);
    }

    public static function selectAll(int handle) -> void
    {
        gtkflowbox_select_all(handle);
    }

    public static function selectChild(int handle, int child) -> void
    {
        gtkflowbox_select_child(handle, child);
    }

    public static function setActivateOnSingleClick(int handle, bool single) -> void
    {
        gtkflowbox_set_activate_on_single_click(handle, single);
    }

    public static function setColumnSpacing(int handle, int spacing) -> void
    {
        gtkflowbox_set_column_spacing(handle, spacing);
    }

    public static function setHadjustment(int handle, int adjustment) -> void
    {
        gtkflowbox_set_hadjustment(handle, adjustment);
    }

    public static function setHomogeneous(int handle, bool homogeneous) -> void
    {
        gtkflowbox_set_homogeneous(handle, homogeneous);
    }

    public static function setMaxChildrenPerLine(int handle, int nChildren) -> void
    {
        gtkflowbox_set_max_children_per_line(handle, nChildren);
    }

    public static function setMinChildrenPerLine(int handle, int nChildren) -> void
    {
        gtkflowbox_set_min_children_per_line(handle, nChildren);
    }

    public static function setRowSpacing(int handle, int spacing) -> void
    {
        gtkflowbox_set_row_spacing(handle, spacing);
    }

    public static function setSelectionMode(int handle, int mode) -> void
    {
        gtkflowbox_set_selection_mode(handle, mode);
    }

    public static function setVadjustment(int handle, int adjustment) -> void
    {
        gtkflowbox_set_vadjustment(handle, adjustment);
    }

    public static function unselectAll(int handle) -> void
    {
        gtkflowbox_unselect_all(handle);
    }

    public static function unselectChild(int handle, int child) -> void
    {
        gtkflowbox_unselect_child(handle, child);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "accept-unpaired-release" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved gtk_flow_box_bind_model(GListModel* model, GtkFlowBoxCreateWidgetFunc create_widget_func, gpointer user_data, GDestroyNotify user_data_free_func) — non-signal callback
    // @reserved gtk_flow_box_selected_foreach(GtkFlowBoxForeachFunc func, gpointer data) — non-signal callback
    // @reserved gtk_flow_box_set_filter_func(GtkFlowBoxFilterFunc filter_func, gpointer user_data, GDestroyNotify destroy) — non-signal callback
    // @reserved gtk_flow_box_set_sort_func(GtkFlowBoxSortFunc sort_func, gpointer user_data, GDestroyNotify destroy) — non-signal callback

}
