// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gdk\GdkKeyval;

class GdkKeyval
{
    public static function convertCase(int symbol) -> array
    {
        var result;

        let result = gdkkeyval_convert_case(symbol);

        return result;
    }

    public static function fromName(string name) -> int
    {
        return gdkkeyval_from_name(name);
    }

    public static function isLower(int keyval) -> bool
    {
        int r;

        let r = gdkkeyval_is_lower(keyval);

        return r == 1;
    }

    public static function isUpper(int keyval) -> bool
    {
        int r;

        let r = gdkkeyval_is_upper(keyval);

        return r == 1;
    }

    public static function name(int keyval) -> var
    {
        var result;

        let result = gdkkeyval_name(keyval);

        return result;
    }

    public static function toLower(int keyval) -> int
    {
        return gdkkeyval_to_lower(keyval);
    }

    public static function toUnicode(int keyval) -> int
    {
        return gdkkeyval_to_unicode(keyval);
    }

    public static function toUpper(int keyval) -> int
    {
        return gdkkeyval_to_upper(keyval);
    }

    public static function fromUnicode(int wc) -> int
    {
        return gdkkeyval_from_unicode(wc);
    }
}
