// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkAspectFrame;

class GtkAspectFrame
{
    public static function new_(double xalign, double yalign, double ratio, bool obeyChild) -> int
    {
        return gtkaspectframe_new(xalign, yalign, ratio, obeyChild);
    }

    public static function getChild(int handle) -> int
    {
        return gtkaspectframe_get_child(handle);
    }

    public static function getObeyChild(int handle) -> bool
    {
        int r;

        let r = gtkaspectframe_get_obey_child(handle);

        return r == 1;
    }

    public static function getRatio(int handle) -> double
    {
        return gtkaspectframe_get_ratio(handle);
    }

    public static function getXalign(int handle) -> double
    {
        return gtkaspectframe_get_xalign(handle);
    }

    public static function getYalign(int handle) -> double
    {
        return gtkaspectframe_get_yalign(handle);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkaspectframe_set_child(handle, child);
    }

    public static function setObeyChild(int handle, bool obeyChild) -> void
    {
        gtkaspectframe_set_obey_child(handle, obeyChild);
    }

    public static function setRatio(int handle, double ratio) -> void
    {
        gtkaspectframe_set_ratio(handle, ratio);
    }

    public static function setXalign(int handle, double xalign) -> void
    {
        gtkaspectframe_set_xalign(handle, xalign);
    }

    public static function setYalign(int handle, double yalign) -> void
    {
        gtkaspectframe_set_yalign(handle, yalign);
    }
}
