// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkWindow;

class GtkWindow
{
    public static function new_() -> int
    {
        return gtkwindow_new();
    }

    public static function getDefaultIconName() -> var
    {
        var result;

        let result = gtkwindow_get_default_icon_name();

        return result;
    }

    public static function getToplevels() -> int
    {
        return gtkwindow_get_toplevels();
    }

    public static function listToplevels() -> array
    {
        var result;

        let result = gtkwindow_list_toplevels();

        return result;
    }

    public static function setAutoStartupNotification(bool setting) -> void
    {
        gtkwindow_set_auto_startup_notification(setting);
    }

    public static function setDefaultIconName(string name) -> void
    {
        gtkwindow_set_default_icon_name(name);
    }

    public static function setInteractiveDebugging(bool enable) -> void
    {
        gtkwindow_set_interactive_debugging(enable);
    }

    public static function close(int handle) -> void
    {
        gtkwindow_close(handle);
    }

    public static function destroy(int handle) -> void
    {
        gtkwindow_destroy(handle);
    }

    public static function fullscreen(int handle) -> void
    {
        gtkwindow_fullscreen(handle);
    }

    public static function fullscreenOnMonitor(int handle, int monitor) -> void
    {
        gtkwindow_fullscreen_on_monitor(handle, monitor);
    }

    public static function getApplication(int handle) -> int
    {
        return gtkwindow_get_application(handle);
    }

    public static function getChild(int handle) -> int
    {
        return gtkwindow_get_child(handle);
    }

    public static function getDecorated(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_decorated(handle);

        return r == 1;
    }

    public static function getDefaultSize(int handle) -> array
    {
        var result;

        let result = gtkwindow_get_default_size(handle);

        return result;
    }

    public static function getDefaultWidget(int handle) -> int
    {
        return gtkwindow_get_default_widget(handle);
    }

    public static function getDeletable(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_deletable(handle);

        return r == 1;
    }

    public static function getDestroyWithParent(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_destroy_with_parent(handle);

        return r == 1;
    }

    public static function getFocus(int handle) -> int
    {
        return gtkwindow_get_focus(handle);
    }

    public static function getFocusVisible(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_focus_visible(handle);

        return r == 1;
    }

    public static function getGroup(int handle) -> int
    {
        return gtkwindow_get_group(handle);
    }

    public static function getHandleMenubarAccel(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_handle_menubar_accel(handle);

        return r == 1;
    }

    public static function getHideOnClose(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_hide_on_close(handle);

        return r == 1;
    }

    public static function getIconName(int handle) -> var
    {
        var result;

        let result = gtkwindow_get_icon_name(handle);

        return result;
    }

    public static function getMnemonicsVisible(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_mnemonics_visible(handle);

        return r == 1;
    }

    public static function getModal(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_modal(handle);

        return r == 1;
    }

    public static function getResizable(int handle) -> bool
    {
        int r;

        let r = gtkwindow_get_resizable(handle);

        return r == 1;
    }

    public static function getTitle(int handle) -> var
    {
        var result;

        let result = gtkwindow_get_title(handle);

        return result;
    }

    public static function getTitlebar(int handle) -> int
    {
        return gtkwindow_get_titlebar(handle);
    }

    public static function getTransientFor(int handle) -> int
    {
        return gtkwindow_get_transient_for(handle);
    }

    public static function hasGroup(int handle) -> bool
    {
        int r;

        let r = gtkwindow_has_group(handle);

        return r == 1;
    }

    public static function isActive(int handle) -> bool
    {
        int r;

        let r = gtkwindow_is_active(handle);

        return r == 1;
    }

    public static function isFullscreen(int handle) -> bool
    {
        int r;

        let r = gtkwindow_is_fullscreen(handle);

        return r == 1;
    }

    public static function isMaximized(int handle) -> bool
    {
        int r;

        let r = gtkwindow_is_maximized(handle);

        return r == 1;
    }

    public static function isSuspended(int handle) -> bool
    {
        int r;

        let r = gtkwindow_is_suspended(handle);

        return r == 1;
    }

    public static function maximize(int handle) -> void
    {
        gtkwindow_maximize(handle);
    }

    public static function minimize(int handle) -> void
    {
        gtkwindow_minimize(handle);
    }

    public static function present(int handle) -> void
    {
        gtkwindow_present(handle);
    }

    public static function setApplication(int handle, int application) -> void
    {
        gtkwindow_set_application(handle, application);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkwindow_set_child(handle, child);
    }

    public static function setDecorated(int handle, bool setting) -> void
    {
        gtkwindow_set_decorated(handle, setting);
    }

    public static function setDefaultSize(int handle, int width, int height) -> void
    {
        gtkwindow_set_default_size(handle, width, height);
    }

    public static function setDefaultWidget(int handle, int defaultWidget) -> void
    {
        gtkwindow_set_default_widget(handle, defaultWidget);
    }

    public static function setDeletable(int handle, bool setting) -> void
    {
        gtkwindow_set_deletable(handle, setting);
    }

    public static function setDestroyWithParent(int handle, bool setting) -> void
    {
        gtkwindow_set_destroy_with_parent(handle, setting);
    }

    public static function setDisplay(int handle, int display) -> void
    {
        gtkwindow_set_display(handle, display);
    }

    public static function setFocus(int handle, int focus) -> void
    {
        gtkwindow_set_focus(handle, focus);
    }

    public static function setFocusVisible(int handle, bool setting) -> void
    {
        gtkwindow_set_focus_visible(handle, setting);
    }

    public static function setHandleMenubarAccel(int handle, bool handleMenubarAccel) -> void
    {
        gtkwindow_set_handle_menubar_accel(handle, handleMenubarAccel);
    }

    public static function setHideOnClose(int handle, bool setting) -> void
    {
        gtkwindow_set_hide_on_close(handle, setting);
    }

    public static function setIconName(int handle, var name) -> void
    {
        gtkwindow_set_icon_name(handle, name);
    }

    public static function setMnemonicsVisible(int handle, bool setting) -> void
    {
        gtkwindow_set_mnemonics_visible(handle, setting);
    }

    public static function setModal(int handle, bool modal) -> void
    {
        gtkwindow_set_modal(handle, modal);
    }

    public static function setResizable(int handle, bool resizable) -> void
    {
        gtkwindow_set_resizable(handle, resizable);
    }

    public static function setStartupId(int handle, string startupId) -> void
    {
        gtkwindow_set_startup_id(handle, startupId);
    }

    public static function setTitle(int handle, var title) -> void
    {
        gtkwindow_set_title(handle, title);
    }

    public static function setTitlebar(int handle, int titlebar) -> void
    {
        gtkwindow_set_titlebar(handle, titlebar);
    }

    public static function setTransientFor(int handle, int parent) -> void
    {
        gtkwindow_set_transient_for(handle, parent);
    }

    public static function unfullscreen(int handle) -> void
    {
        gtkwindow_unfullscreen(handle);
    }

    public static function unmaximize(int handle) -> void
    {
        gtkwindow_unmaximize(handle);
    }

    public static function unminimize(int handle) -> void
    {
        gtkwindow_unminimize(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "default-height" — no dedicated C accessor; use getDefaultSize/setDefaultSize or Bridge::getProperty
    // @reserved property "default-width" — no dedicated C accessor; use getDefaultSize/setDefaultSize or Bridge::getProperty
    // @reserved property "display" — no getter on this class; setter is setDisplay; read via GtkWidget::getDisplay or Bridge::getProperty
    // @reserved property "fullscreened" — no setter; use fullscreen/unfullscreen/isFullscreen or Bridge::getProperty
    // @reserved property "maximized" — no setter; use maximize/unmaximize/isMaximized or Bridge::getProperty
    // @reserved gtk_window_present_with_time(self, guint32 timestamp) — deprecated

}
