// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkPasswordEntry;

class GtkPasswordEntry
{
    public static function new_() -> int
    {
        return gtkpasswordentry_new();
    }

    public static function getExtraMenu(int handle) -> int
    {
        return gtkpasswordentry_get_extra_menu(handle);
    }

    public static function getShowPeekIcon(int handle) -> bool
    {
        int r;

        let r = gtkpasswordentry_get_show_peek_icon(handle);

        return r == 1;
    }

    public static function setExtraMenu(int handle, int model) -> void
    {
        gtkpasswordentry_set_extra_menu(handle, model);
    }

    public static function setShowPeekIcon(int handle, bool showPeekIcon) -> void
    {
        gtkpasswordentry_set_show_peek_icon(handle, showPeekIcon);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "activates-default" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "placeholder-text" — no C accessor; use Bridge::getProperty/setProperty

}
