
extern zend_class_entry *gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_ce;

ZEPHIR_INIT_CLASS(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow);

PHP_METHOD(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, new_);
PHP_METHOD(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, getId);
PHP_METHOD(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, getShowMenubar);
PHP_METHOD(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, setShowMenubar);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, application, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_getid, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_getshowmenubar, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_setshowmenubar, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, showMenubar, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_method_entry) {
	PHP_ME(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, new_, arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, getId, arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_getid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, getShowMenubar, arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_getshowmenubar, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkApplicationWindow_GtkApplicationWindow, setShowMenubar, arginfo_gtk_gtk_gtkapplicationwindow_gtkapplicationwindow_setshowmenubar, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
