// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GSimpleActionGroup;

class GSimpleActionGroup
{
    public static function new_() -> int
    {
        return gsimpleactiongroup_new();
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved g_simple_action_group_add_entries(self, entries, n_entries, user_data) — deprecated, use GActionMap
    // @reserved g_simple_action_group_insert(self, action) — deprecated, use GActionMap::addAction
    // @reserved g_simple_action_group_lookup(self, action_name) — deprecated, use GActionMap::lookupAction
    // @reserved g_simple_action_group_remove(self, action_name) — deprecated, use GActionMap::removeAction

}
