// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GListModel;

class GListModel
{
    public static function getItem(int handle, int position) -> int
    {
        return glistmodel_get_item(handle, position);
    }

    public static function getItemType(int handle) -> int
    {
        return glistmodel_get_item_type(handle);
    }

    public static function getNItems(int handle) -> int
    {
        return glistmodel_get_n_items(handle);
    }

    public static function getObject(int handle, int position) -> int
    {
        return glistmodel_get_object(handle, position);
    }

    public static function itemsChanged(int handle, int position, int removed, int added) -> void
    {
        glistmodel_items_changed(handle, position, removed, added);
    }
}
