// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkPopoverMenuBar;

class GtkPopoverMenuBar
{
    public static function newFromModel(int model) -> int
    {
        return gtkpopovermenubar_new_from_model(model);
    }

    public static function addChild(int handle, int child, string id) -> bool
    {
        int r;

        let r = gtkpopovermenubar_add_child(handle, child, id);

        return r == 1;
    }

    public static function getMenuModel(int handle) -> int
    {
        return gtkpopovermenubar_get_menu_model(handle);
    }

    public static function removeChild(int handle, int child) -> bool
    {
        int r;

        let r = gtkpopovermenubar_remove_child(handle, child);

        return r == 1;
    }

    public static function setMenuModel(int handle, int model) -> void
    {
        gtkpopovermenubar_set_menu_model(handle, model);
    }
}
