// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkButton;

class GtkButton
{
    public static function new_() -> int
    {
        return gtkbutton_new();
    }

    public static function newFromIconName(string iconName) -> int
    {
        return gtkbutton_new_from_icon_name(iconName);
    }

    public static function newWithLabel(string label) -> int
    {
        return gtkbutton_new_with_label(label);
    }

    public static function newWithMnemonic(string label) -> int
    {
        return gtkbutton_new_with_mnemonic(label);
    }

    public static function getCanShrink(int handle) -> bool
    {
        int r;

        let r = gtkbutton_get_can_shrink(handle);

        return r == 1;
    }

    public static function getChild(int handle) -> int
    {
        return gtkbutton_get_child(handle);
    }

    public static function getHasFrame(int handle) -> bool
    {
        int r;

        let r = gtkbutton_get_has_frame(handle);

        return r == 1;
    }

    public static function getIconName(int handle) -> var
    {
        var result;

        let result = gtkbutton_get_icon_name(handle);

        return result;
    }

    public static function getLabel(int handle) -> var
    {
        var result;

        let result = gtkbutton_get_label(handle);

        return result;
    }

    public static function getUseUnderline(int handle) -> bool
    {
        int r;

        let r = gtkbutton_get_use_underline(handle);

        return r == 1;
    }

    public static function setCanShrink(int handle, bool canShrink) -> void
    {
        gtkbutton_set_can_shrink(handle, canShrink);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkbutton_set_child(handle, child);
    }

    public static function setHasFrame(int handle, bool hasFrame) -> void
    {
        gtkbutton_set_has_frame(handle, hasFrame);
    }

    public static function setIconName(int handle, string iconName) -> void
    {
        gtkbutton_set_icon_name(handle, iconName);
    }

    public static function setLabel(int handle, string label) -> void
    {
        gtkbutton_set_label(handle, label);
    }

    public static function setUseUnderline(int handle, bool useUnderline) -> void
    {
        gtkbutton_set_use_underline(handle, useUnderline);
    }
}
