// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkMediaStream;

class GtkMediaStream
{
    public static function getDuration(int handle) -> int
    {
        return gtkmediastream_get_duration(handle);
    }

    public static function getEnded(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_get_ended(handle);

        return r == 1;
    }

    public static function getLoop(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_get_loop(handle);

        return r == 1;
    }

    public static function getMuted(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_get_muted(handle);

        return r == 1;
    }

    public static function getPlaying(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_get_playing(handle);

        return r == 1;
    }

    public static function getTimestamp(int handle) -> int
    {
        return gtkmediastream_get_timestamp(handle);
    }

    public static function getVolume(int handle) -> double
    {
        return gtkmediastream_get_volume(handle);
    }

    public static function hasAudio(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_has_audio(handle);

        return r == 1;
    }

    public static function hasVideo(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_has_video(handle);

        return r == 1;
    }

    public static function isPrepared(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_is_prepared(handle);

        return r == 1;
    }

    public static function isSeekable(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_is_seekable(handle);

        return r == 1;
    }

    public static function isSeeking(int handle) -> bool
    {
        int r;

        let r = gtkmediastream_is_seeking(handle);

        return r == 1;
    }

    public static function pause(int handle) -> void
    {
        gtkmediastream_pause(handle);
    }

    public static function play(int handle) -> void
    {
        gtkmediastream_play(handle);
    }

    public static function realize(int handle, int surface) -> void
    {
        gtkmediastream_realize(handle, surface);
    }

    public static function seek(int handle, int timestamp) -> void
    {
        gtkmediastream_seek(handle, timestamp);
    }

    public static function seekFailed(int handle) -> void
    {
        gtkmediastream_seek_failed(handle);
    }

    public static function seekSuccess(int handle) -> void
    {
        gtkmediastream_seek_success(handle);
    }

    public static function setLoop(int handle, bool loop_) -> void
    {
        gtkmediastream_set_loop(handle, loop_);
    }

    public static function setMuted(int handle, bool muted) -> void
    {
        gtkmediastream_set_muted(handle, muted);
    }

    public static function setPlaying(int handle, bool playing) -> void
    {
        gtkmediastream_set_playing(handle, playing);
    }

    public static function setVolume(int handle, double volume) -> void
    {
        gtkmediastream_set_volume(handle, volume);
    }

    public static function streamEnded(int handle) -> void
    {
        gtkmediastream_stream_ended(handle);
    }

    public static function streamPrepared(int handle, bool hasAudio, bool hasVideo, bool seekable, int duration) -> void
    {
        gtkmediastream_stream_prepared(handle, hasAudio, hasVideo, seekable, duration);
    }

    public static function streamUnprepared(int handle) -> void
    {
        gtkmediastream_stream_unprepared(handle);
    }

    public static function unrealize(int handle, int surface) -> void
    {
        gtkmediastream_unrealize(handle, surface);
    }

    public static function update(int handle, int timestamp) -> void
    {
        gtkmediastream_update(handle, timestamp);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_media_stream_ended(GtkMediaStream* self) — deprecated
    // @reserved gtk_media_stream_error(GtkMediaStream* self, domain, code, format, ...) — varargs
    // @reserved gtk_media_stream_error_valist(GtkMediaStream* self, domain, code, format, va_list args) — va_list
    // @reserved gtk_media_stream_gerror(GtkMediaStream* self, GError* error) — GError
    // @reserved gtk_media_stream_get_error(GtkMediaStream* self) — GError* return
    // @reserved gtk_media_stream_prepared(GtkMediaStream* self, has_audio, has_video, seekable, duration) — deprecated
    // @reserved gtk_media_stream_unprepared(GtkMediaStream* self) — deprecated

}
