// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GActionMap;

class GActionMap
{
    public static function addAction(int handle, int action) -> void
    {
        gactionmap_add_action(handle, action);
    }

    public static function lookupAction(int handle, string actionName) -> int
    {
        return gactionmap_lookup_action(handle, actionName);
    }

    public static function removeAction(int handle, string actionName) -> void
    {
        gactionmap_remove_action(handle, actionName);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved g_action_map_add_action_entries(self, GActionEntry* entries, n_entries, user_data) — GActionEntry array
    // @reserved g_action_map_remove_action_entries(self, GActionEntry* entries, n_entries) — GActionEntry array

}
