// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkRange;

class GtkRange
{
    public static function getAdjustment(int handle) -> int
    {
        return gtkrange_get_adjustment(handle);
    }

    public static function getFillLevel(int handle) -> double
    {
        return gtkrange_get_fill_level(handle);
    }

    public static function getFlippable(int handle) -> bool
    {
        int r;

        let r = gtkrange_get_flippable(handle);

        return r == 1;
    }

    public static function getInverted(int handle) -> bool
    {
        int r;

        let r = gtkrange_get_inverted(handle);

        return r == 1;
    }

    public static function getRangeRect(int handle) -> array
    {
        var result;

        let result = gtkrange_get_range_rect(handle);

        return result;
    }

    public static function getRestrictToFillLevel(int handle) -> bool
    {
        int r;

        let r = gtkrange_get_restrict_to_fill_level(handle);

        return r == 1;
    }

    public static function getRoundDigits(int handle) -> int
    {
        return gtkrange_get_round_digits(handle);
    }

    public static function getShowFillLevel(int handle) -> bool
    {
        int r;

        let r = gtkrange_get_show_fill_level(handle);

        return r == 1;
    }

    public static function getSliderRange(int handle) -> array
    {
        var result;

        let result = gtkrange_get_slider_range(handle);

        return result;
    }

    public static function getSliderSizeFixed(int handle) -> bool
    {
        int r;

        let r = gtkrange_get_slider_size_fixed(handle);

        return r == 1;
    }

    public static function getValue(int handle) -> double
    {
        return gtkrange_get_value(handle);
    }

    public static function setAdjustment(int handle, int adjustment) -> void
    {
        gtkrange_set_adjustment(handle, adjustment);
    }

    public static function setFillLevel(int handle, double fillLevel) -> void
    {
        gtkrange_set_fill_level(handle, fillLevel);
    }

    public static function setFlippable(int handle, bool flippable) -> void
    {
        gtkrange_set_flippable(handle, flippable);
    }

    public static function setIncrements(int handle, double step, double page) -> void
    {
        gtkrange_set_increments(handle, step, page);
    }

    public static function setInverted(int handle, bool setting) -> void
    {
        gtkrange_set_inverted(handle, setting);
    }

    public static function setRange(int handle, double min, double max) -> void
    {
        gtkrange_set_range(handle, min, max);
    }

    public static function setRestrictToFillLevel(int handle, bool restrictToFillLevel) -> void
    {
        gtkrange_set_restrict_to_fill_level(handle, restrictToFillLevel);
    }

    public static function setRoundDigits(int handle, int roundDigits) -> void
    {
        gtkrange_set_round_digits(handle, roundDigits);
    }

    public static function setShowFillLevel(int handle, bool showFillLevel) -> void
    {
        gtkrange_set_show_fill_level(handle, showFillLevel);
    }

    public static function setSliderSizeFixed(int handle, bool sizeFixed) -> void
    {
        gtkrange_set_slider_size_fixed(handle, sizeFixed);
    }

    public static function setValue(int handle, double value) -> void
    {
        gtkrange_set_value(handle, value);
    }
}
