// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkStyleContext;

class GtkStyleContext
{
    public static function addProviderForDisplay(int display, int provider, int priority) -> void
    {
        stylecontext_add_provider_for_display(display, provider, priority);
    }

    public static function removeProviderForDisplay(int display, int provider) -> void
    {
        stylecontext_remove_provider_for_display(display, provider);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "display" — deprecated class; Bridge::getProperty/setProperty
    // @reserved gtk_style_context_add_class(self, class_name) — deprecated 4.10, GtkWidget::addCssClass
    // @reserved gtk_style_context_add_provider(self, provider, priority) — deprecated 4.10, use addProviderForDisplay
    // @reserved gtk_style_context_get_border(self, border) — deprecated 4.10
    // @reserved gtk_style_context_get_color(self, color) — deprecated 4.10
    // @reserved gtk_style_context_get_display(self) — deprecated 4.10
    // @reserved gtk_style_context_get_margin(self, margin) — deprecated 4.10
    // @reserved gtk_style_context_get_padding(self, padding) — deprecated 4.10
    // @reserved gtk_style_context_get_scale(self) — deprecated 4.10
    // @reserved gtk_style_context_get_state(self) — deprecated 4.10
    // @reserved gtk_style_context_has_class(self, class_name) — deprecated 4.10, GtkWidget::getCssClasses
    // @reserved gtk_style_context_lookup_color(self, color_name, color) — deprecated 4.10
    // @reserved gtk_style_context_remove_class(self, class_name) — deprecated 4.10, GtkWidget::removeCssClass
    // @reserved gtk_style_context_remove_provider(self, provider) — deprecated 4.10
    // @reserved gtk_style_context_restore(self) — deprecated 4.10
    // @reserved gtk_style_context_save(self) — deprecated 4.10
    // @reserved gtk_style_context_set_display(self, display) — deprecated 4.10
    // @reserved gtk_style_context_set_scale(self, scale) — deprecated 4.10
    // @reserved gtk_style_context_set_state(self, flags) — deprecated 4.10
    // @reserved gtk_style_context_to_string(self, flags) — deprecated 4.10

}
