// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GMenuModel;

class GMenuModel
{
    public static function getItemLink(int handle, int itemIndex, string link) -> int
    {
        return gmenumodel_get_item_link(handle, itemIndex, link);
    }

    public static function getNItems(int handle) -> int
    {
        return gmenumodel_get_n_items(handle);
    }

    public static function isMutable(int handle) -> bool
    {
        int r;

        let r = gmenumodel_is_mutable(handle);

        return r == 1;
    }

    public static function itemsChanged(int handle, int position, int removed, int added) -> void
    {
        gmenumodel_items_changed(handle, position, removed, added);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved g_menu_model_get_item_attribute(self, item_index, attribute, format_string, ...) — varargs
    // @reserved g_menu_model_get_item_attribute_value(self, item_index, attribute, GVariantType* expected_type) — GVariant*
    // @reserved g_menu_model_iterate_item_attributes(self, item_index) — GMenuAttributeIter*
    // @reserved g_menu_model_iterate_item_links(self, item_index) — GMenuLinkIter*

}
