// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkSelectionModel;

class GtkSelectionModel
{
    public static function isSelected(int handle, int position) -> bool
    {
        int r;

        let r = gtkselectionmodel_is_selected(handle, position);

        return r == 1;
    }

    public static function selectAll(int handle) -> bool
    {
        int r;

        let r = gtkselectionmodel_select_all(handle);

        return r == 1;
    }

    public static function selectItem(int handle, int position, bool unselectRest) -> bool
    {
        int r;

        let r = gtkselectionmodel_select_item(handle, position, unselectRest);

        return r == 1;
    }

    public static function selectRange(int handle, int position, int nItems, bool unselectRest) -> bool
    {
        int r;

        let r = gtkselectionmodel_select_range(handle, position, nItems, unselectRest);

        return r == 1;
    }

    public static function selectionChanged(int handle, int position, int nItems) -> void
    {
        gtkselectionmodel_selection_changed(handle, position, nItems);
    }

    public static function unselectAll(int handle) -> bool
    {
        int r;

        let r = gtkselectionmodel_unselect_all(handle);

        return r == 1;
    }

    public static function unselectItem(int handle, int position) -> bool
    {
        int r;

        let r = gtkselectionmodel_unselect_item(handle, position);

        return r == 1;
    }

    public static function unselectRange(int handle, int position, int nItems) -> bool
    {
        int r;

        let r = gtkselectionmodel_unselect_range(handle, position, nItems);

        return r == 1;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_selection_model_get_selection() — GtkBitset*
    // @reserved gtk_selection_model_get_selection_in_range(position, n_items) — GtkBitset*
    // @reserved gtk_selection_model_set_selection(GtkBitset* selected, GtkBitset* mask) — GtkBitset*

}
