// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GApplication;

class GApplication
{
    public static function new_(var applicationId, int flags) -> int
    {
        return gapplication_new(applicationId, flags);
    }

    public static function getDefault() -> int
    {
        return gapplication_get_default();
    }

    public static function idIsValid(string applicationId) -> bool
    {
        int r;

        let r = gapplication_id_is_valid(applicationId);

        return r == 1;
    }

    public static function activate(int handle) -> void
    {
        gapplication_activate(handle);
    }

    public static function addMainOption(int handle, string longName, int shortName, int flags, int arg, string description, var argDescription) -> void
    {
        gapplication_add_main_option(handle, longName, shortName, flags, arg, description, argDescription);
    }

    public static function getApplicationId(int handle) -> var
    {
        var result;

        let result = gapplication_get_application_id(handle);

        return result;
    }

    public static function getDbusConnection(int handle) -> int
    {
        return gapplication_get_dbus_connection(handle);
    }

    public static function getDbusObjectPath(int handle) -> var
    {
        var result;

        let result = gapplication_get_dbus_object_path(handle);

        return result;
    }

    public static function getFlags(int handle) -> int
    {
        return gapplication_get_flags(handle);
    }

    public static function getInactivityTimeout(int handle) -> int
    {
        return gapplication_get_inactivity_timeout(handle);
    }

    public static function getIsBusy(int handle) -> bool
    {
        int r;

        let r = gapplication_get_is_busy(handle);

        return r == 1;
    }

    public static function getIsRegistered(int handle) -> bool
    {
        int r;

        let r = gapplication_get_is_registered(handle);

        return r == 1;
    }

    public static function getIsRemote(int handle) -> bool
    {
        int r;

        let r = gapplication_get_is_remote(handle);

        return r == 1;
    }

    public static function getResourceBasePath(int handle) -> var
    {
        var result;

        let result = gapplication_get_resource_base_path(handle);

        return result;
    }

    public static function getVersion(int handle) -> var
    {
        var result;

        let result = gapplication_get_version(handle);

        return result;
    }

    public static function hold(int handle) -> void
    {
        gapplication_hold(handle);
    }

    public static function markBusy(int handle) -> void
    {
        gapplication_mark_busy(handle);
    }

    public static function open(int handle, array files, int nFiles, string hint) -> void
    {
        gapplication_open(handle, files, nFiles, hint);
    }

    public static function quit(int handle) -> void
    {
        gapplication_quit(handle);
    }

    public static function release(int handle) -> void
    {
        gapplication_release(handle);
    }

    public static function run(int handle, int argc, array argv) -> int
    {
        return gapplication_run(handle, argc, argv);
    }

    public static function sendNotification(int handle, var id, int notification) -> void
    {
        gapplication_send_notification(handle, id, notification);
    }

    public static function setApplicationId(int handle, var applicationId) -> void
    {
        gapplication_set_application_id(handle, applicationId);
    }

    public static function setDefault(int handle) -> void
    {
        gapplication_set_default(handle);
    }

    public static function setFlags(int handle, int flags) -> void
    {
        gapplication_set_flags(handle, flags);
    }

    public static function setInactivityTimeout(int handle, int inactivityTimeout) -> void
    {
        gapplication_set_inactivity_timeout(handle, inactivityTimeout);
    }

    public static function setOptionContextDescription(int handle, var description) -> void
    {
        gapplication_set_option_context_description(handle, description);
    }

    public static function setOptionContextParameterString(int handle, var parameterString) -> void
    {
        gapplication_set_option_context_parameter_string(handle, parameterString);
    }

    public static function setOptionContextSummary(int handle, var summary) -> void
    {
        gapplication_set_option_context_summary(handle, summary);
    }

    public static function setResourceBasePath(int handle, var resourcePath) -> void
    {
        gapplication_set_resource_base_path(handle, resourcePath);
    }

    public static function setVersion(int handle, string version) -> void
    {
        gapplication_set_version(handle, version);
    }

    public static function unmarkBusy(int handle) -> void
    {
        gapplication_unmark_busy(handle);
    }

    public static function withdrawNotification(int handle, string id) -> void
    {
        gapplication_withdraw_notification(handle, id);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved g_application_add_main_option_entries(self, GOptionEntry* entries) — GOptionEntry array
    // @reserved g_application_add_option_group(self, GOptionGroup* group) — GOptionGroup*
    // @reserved g_application_bind_busy_property(self, gpointer object, gchar* property) — gpointer
    // @reserved g_application_register(self, GCancellable* cancellable) — GError**
    // @reserved g_application_set_action_group(self, GActionGroup* action_group) — deprecated
    // @reserved g_application_unbind_busy_property(self, gpointer object, gchar* property) — gpointer

}
