// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkActionable;

class GtkActionable
{
    public static function getActionName(int handle) -> var
    {
        var result;

        let result = gtkactionable_get_action_name(handle);

        return result;
    }

    public static function setActionName(int handle, var actionName) -> void
    {
        gtkactionable_set_action_name(handle, actionName);
    }

    public static function setDetailedActionName(int handle, string detailedActionName) -> void
    {
        gtkactionable_set_detailed_action_name(handle, detailedActionName);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "action-target" — getter is get_action_target_value (GVariant*); use Bridge::getProperty
    // @reserved gtk_actionable_get_action_target_value(self) — GVariant*
    // @reserved gtk_actionable_set_action_target(self, format_string, ...) — varargs
    // @reserved gtk_actionable_set_action_target_value(self, GVariant* target_value) — GVariant*

}
