// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkAdjustment;

class GtkAdjustment
{
    public static function new_(double value, double lower, double upper, double stepIncrement, double pageIncrement, double pageSize) -> int
    {
        return gtkadjustment_new(value, lower, upper, stepIncrement, pageIncrement, pageSize);
    }

    public static function clampPage(int handle, double lower, double upper) -> void
    {
        gtkadjustment_clamp_page(handle, lower, upper);
    }

    public static function configure(int handle, double value, double lower, double upper, double stepIncrement, double pageIncrement, double pageSize) -> void
    {
        gtkadjustment_configure(handle, value, lower, upper, stepIncrement, pageIncrement, pageSize);
    }

    public static function getLower(int handle) -> double
    {
        return gtkadjustment_get_lower(handle);
    }

    public static function getMinimumIncrement(int handle) -> double
    {
        return gtkadjustment_get_minimum_increment(handle);
    }

    public static function getPageIncrement(int handle) -> double
    {
        return gtkadjustment_get_page_increment(handle);
    }

    public static function getPageSize(int handle) -> double
    {
        return gtkadjustment_get_page_size(handle);
    }

    public static function getStepIncrement(int handle) -> double
    {
        return gtkadjustment_get_step_increment(handle);
    }

    public static function getUpper(int handle) -> double
    {
        return gtkadjustment_get_upper(handle);
    }

    public static function getValue(int handle) -> double
    {
        return gtkadjustment_get_value(handle);
    }

    public static function setLower(int handle, double lower) -> void
    {
        gtkadjustment_set_lower(handle, lower);
    }

    public static function setPageIncrement(int handle, double pageIncrement) -> void
    {
        gtkadjustment_set_page_increment(handle, pageIncrement);
    }

    public static function setPageSize(int handle, double pageSize) -> void
    {
        gtkadjustment_set_page_size(handle, pageSize);
    }

    public static function setStepIncrement(int handle, double stepIncrement) -> void
    {
        gtkadjustment_set_step_increment(handle, stepIncrement);
    }

    public static function setUpper(int handle, double upper) -> void
    {
        gtkadjustment_set_upper(handle, upper);
    }

    public static function setValue(int handle, double value) -> void
    {
        gtkadjustment_set_value(handle, value);
    }
}
