// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkLabel;

class GtkLabel
{
    public static function new_(var str) -> int
    {
        return gtklabel_new(str);
    }

    public static function newWithMnemonic(var str) -> int
    {
        return gtklabel_new_with_mnemonic(str);
    }

    public static function getCurrentUri(int handle) -> var
    {
        var result;

        let result = gtklabel_get_current_uri(handle);

        return result;
    }

    public static function getEllipsize(int handle) -> int
    {
        return gtklabel_get_ellipsize(handle);
    }

    public static function getExtraMenu(int handle) -> int
    {
        return gtklabel_get_extra_menu(handle);
    }

    public static function getJustify(int handle) -> int
    {
        return gtklabel_get_justify(handle);
    }

    public static function getLabel(int handle) -> string
    {
        var result;

        let result = gtklabel_get_label(handle);

        return result;
    }

    public static function getLayout(int handle) -> int
    {
        return gtklabel_get_layout(handle);
    }

    public static function getLayoutOffsets(int handle) -> array
    {
        var result;

        let result = gtklabel_get_layout_offsets(handle);

        return result;
    }

    public static function getLines(int handle) -> int
    {
        return gtklabel_get_lines(handle);
    }

    public static function getMaxWidthChars(int handle) -> int
    {
        return gtklabel_get_max_width_chars(handle);
    }

    public static function getMnemonicKeyval(int handle) -> int
    {
        return gtklabel_get_mnemonic_keyval(handle);
    }

    public static function getMnemonicWidget(int handle) -> int
    {
        return gtklabel_get_mnemonic_widget(handle);
    }

    public static function getNaturalWrapMode(int handle) -> int
    {
        return gtklabel_get_natural_wrap_mode(handle);
    }

    public static function getSelectable(int handle) -> bool
    {
        int r;

        let r = gtklabel_get_selectable(handle);

        return r == 1;
    }

    public static function getSelectionBounds(int handle) -> array
    {
        var result;

        let result = gtklabel_get_selection_bounds(handle);

        return result;
    }

    public static function getSingleLineMode(int handle) -> bool
    {
        int r;

        let r = gtklabel_get_single_line_mode(handle);

        return r == 1;
    }

    public static function getText(int handle) -> string
    {
        var result;

        let result = gtklabel_get_text(handle);

        return result;
    }

    public static function getUseMarkup(int handle) -> bool
    {
        int r;

        let r = gtklabel_get_use_markup(handle);

        return r == 1;
    }

    public static function getUseUnderline(int handle) -> bool
    {
        int r;

        let r = gtklabel_get_use_underline(handle);

        return r == 1;
    }

    public static function getWidthChars(int handle) -> int
    {
        return gtklabel_get_width_chars(handle);
    }

    public static function getWrap(int handle) -> bool
    {
        int r;

        let r = gtklabel_get_wrap(handle);

        return r == 1;
    }

    public static function getWrapMode(int handle) -> int
    {
        return gtklabel_get_wrap_mode(handle);
    }

    public static function getXalign(int handle) -> double
    {
        return gtklabel_get_xalign(handle);
    }

    public static function getYalign(int handle) -> double
    {
        return gtklabel_get_yalign(handle);
    }

    public static function selectRegion(int handle, int startOffset, int endOffset) -> void
    {
        gtklabel_select_region(handle, startOffset, endOffset);
    }

    public static function setEllipsize(int handle, int mode) -> void
    {
        gtklabel_set_ellipsize(handle, mode);
    }

    public static function setExtraMenu(int handle, int model) -> void
    {
        gtklabel_set_extra_menu(handle, model);
    }

    public static function setJustify(int handle, int jtype) -> void
    {
        gtklabel_set_justify(handle, jtype);
    }

    public static function setLabel(int handle, string str) -> void
    {
        gtklabel_set_label(handle, str);
    }

    public static function setLines(int handle, int lines) -> void
    {
        gtklabel_set_lines(handle, lines);
    }

    public static function setMarkup(int handle, string str) -> void
    {
        gtklabel_set_markup(handle, str);
    }

    public static function setMarkupWithMnemonic(int handle, string str) -> void
    {
        gtklabel_set_markup_with_mnemonic(handle, str);
    }

    public static function setMaxWidthChars(int handle, int nChars) -> void
    {
        gtklabel_set_max_width_chars(handle, nChars);
    }

    public static function setMnemonicWidget(int handle, int widget) -> void
    {
        gtklabel_set_mnemonic_widget(handle, widget);
    }

    public static function setNaturalWrapMode(int handle, int wrapMode) -> void
    {
        gtklabel_set_natural_wrap_mode(handle, wrapMode);
    }

    public static function setSelectable(int handle, bool setting) -> void
    {
        gtklabel_set_selectable(handle, setting);
    }

    public static function setSingleLineMode(int handle, bool singleLineMode) -> void
    {
        gtklabel_set_single_line_mode(handle, singleLineMode);
    }

    public static function setText(int handle, string str) -> void
    {
        gtklabel_set_text(handle, str);
    }

    public static function setTextWithMnemonic(int handle, string str) -> void
    {
        gtklabel_set_text_with_mnemonic(handle, str);
    }

    public static function setUseMarkup(int handle, bool setting) -> void
    {
        gtklabel_set_use_markup(handle, setting);
    }

    public static function setUseUnderline(int handle, bool setting) -> void
    {
        gtklabel_set_use_underline(handle, setting);
    }

    public static function setWidthChars(int handle, int nChars) -> void
    {
        gtklabel_set_width_chars(handle, nChars);
    }

    public static function setWrap(int handle, bool wrap) -> void
    {
        gtklabel_set_wrap(handle, wrap);
    }

    public static function setWrapMode(int handle, int wrapMode) -> void
    {
        gtklabel_set_wrap_mode(handle, wrapMode);
    }

    public static function setXalign(int handle, double xalign) -> void
    {
        gtklabel_set_xalign(handle, xalign);
    }

    public static function setYalign(int handle, double yalign) -> void
    {
        gtklabel_set_yalign(handle, yalign);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_label_get_attributes(GtkLabel* self) — PangoAttrList*
    // @reserved gtk_label_get_tabs(GtkLabel* self) — PangoTabArray*
    // @reserved gtk_label_set_attributes(GtkLabel* self, PangoAttrList* attrs) — PangoAttrList*
    // @reserved gtk_label_set_tabs(GtkLabel* self, PangoTabArray* tabs) — PangoTabArray*

}
