// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkPopover;

class GtkPopover
{
    public static function new_() -> int
    {
        return gtkpopover_new();
    }

    public static function getAutohide(int handle) -> bool
    {
        int r;

        let r = gtkpopover_get_autohide(handle);

        return r == 1;
    }

    public static function getCascadePopdown(int handle) -> bool
    {
        int r;

        let r = gtkpopover_get_cascade_popdown(handle);

        return r == 1;
    }

    public static function getChild(int handle) -> int
    {
        return gtkpopover_get_child(handle);
    }

    public static function getHasArrow(int handle) -> bool
    {
        int r;

        let r = gtkpopover_get_has_arrow(handle);

        return r == 1;
    }

    public static function getMnemonicsVisible(int handle) -> bool
    {
        int r;

        let r = gtkpopover_get_mnemonics_visible(handle);

        return r == 1;
    }

    public static function getOffset(int handle) -> array
    {
        var result;

        let result = gtkpopover_get_offset(handle);

        return result;
    }

    public static function getPointingTo(int handle) -> array
    {
        var result;

        let result = gtkpopover_get_pointing_to(handle);

        return result;
    }

    public static function getPosition(int handle) -> int
    {
        return gtkpopover_get_position(handle);
    }

    public static function popdown(int handle) -> void
    {
        gtkpopover_popdown(handle);
    }

    public static function popup(int handle) -> void
    {
        gtkpopover_popup(handle);
    }

    public static function present(int handle) -> void
    {
        gtkpopover_present(handle);
    }

    public static function setAutohide(int handle, bool autohide) -> void
    {
        gtkpopover_set_autohide(handle, autohide);
    }

    public static function setCascadePopdown(int handle, bool cascadePopdown) -> void
    {
        gtkpopover_set_cascade_popdown(handle, cascadePopdown);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkpopover_set_child(handle, child);
    }

    public static function setDefaultWidget(int handle, int widget) -> void
    {
        gtkpopover_set_default_widget(handle, widget);
    }

    public static function setHasArrow(int handle, bool hasArrow) -> void
    {
        gtkpopover_set_has_arrow(handle, hasArrow);
    }

    public static function setMnemonicsVisible(int handle, bool mnemonicsVisible) -> void
    {
        gtkpopover_set_mnemonics_visible(handle, mnemonicsVisible);
    }

    public static function setOffset(int handle, int xOffset, int yOffset) -> void
    {
        gtkpopover_set_offset(handle, xOffset, yOffset);
    }

    public static function setPointingTo(int handle, double x, double y, double width, double height) -> void
    {
        gtkpopover_set_pointing_to(handle, x, y, width, height);
    }

    public static function setPosition(int handle, int position) -> void
    {
        gtkpopover_set_position(handle, position);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "default-widget" — no dedicated C accessor; use Bridge::getProperty/setProperty

}
