// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkTextBuffer;

class GtkTextBuffer
{
    public static function new_(int table) -> int
    {
        return gtktextbuffer_new(table);
    }

    public static function addSelectionClipboard(int handle, int clipboard) -> void
    {
        gtktextbuffer_add_selection_clipboard(handle, clipboard);
    }

    public static function beginIrreversibleAction(int handle) -> void
    {
        gtktextbuffer_begin_irreversible_action(handle);
    }

    public static function beginUserAction(int handle) -> void
    {
        gtktextbuffer_begin_user_action(handle);
    }

    public static function copyClipboard(int handle, int clipboard) -> void
    {
        gtktextbuffer_copy_clipboard(handle, clipboard);
    }

    public static function cutClipboard(int handle, int clipboard, bool defaultEditable) -> void
    {
        gtktextbuffer_cut_clipboard(handle, clipboard, defaultEditable);
    }

    public static function deleteMark(int handle, int mark) -> void
    {
        gtktextbuffer_delete_mark(handle, mark);
    }

    public static function deleteMarkByName(int handle, string name) -> void
    {
        gtktextbuffer_delete_mark_by_name(handle, name);
    }

    public static function deleteSelection(int handle, bool interactive, bool defaultEditable) -> bool
    {
        int r;

        let r = gtktextbuffer_delete_selection(handle, interactive, defaultEditable);

        return r == 1;
    }

    public static function endIrreversibleAction(int handle) -> void
    {
        gtktextbuffer_end_irreversible_action(handle);
    }

    public static function endUserAction(int handle) -> void
    {
        gtktextbuffer_end_user_action(handle);
    }

    public static function getCanRedo(int handle) -> bool
    {
        int r;

        let r = gtktextbuffer_get_can_redo(handle);

        return r == 1;
    }

    public static function getCanUndo(int handle) -> bool
    {
        int r;

        let r = gtktextbuffer_get_can_undo(handle);

        return r == 1;
    }

    public static function getCharCount(int handle) -> int
    {
        return gtktextbuffer_get_char_count(handle);
    }

    public static function getEnableUndo(int handle) -> bool
    {
        int r;

        let r = gtktextbuffer_get_enable_undo(handle);

        return r == 1;
    }

    public static function getHasSelection(int handle) -> bool
    {
        int r;

        let r = gtktextbuffer_get_has_selection(handle);

        return r == 1;
    }

    public static function getInsert(int handle) -> int
    {
        return gtktextbuffer_get_insert(handle);
    }

    public static function getLineCount(int handle) -> int
    {
        return gtktextbuffer_get_line_count(handle);
    }

    public static function getMark(int handle, string name) -> int
    {
        return gtktextbuffer_get_mark(handle, name);
    }

    public static function getMaxUndoLevels(int handle) -> int
    {
        return gtktextbuffer_get_max_undo_levels(handle);
    }

    public static function getModified(int handle) -> bool
    {
        int r;

        let r = gtktextbuffer_get_modified(handle);

        return r == 1;
    }

    public static function getSelectionBound(int handle) -> int
    {
        return gtktextbuffer_get_selection_bound(handle);
    }

    public static function getTagTable(int handle) -> int
    {
        return gtktextbuffer_get_tag_table(handle);
    }

    public static function getText(int handle, int startOffset, int endOffset, bool includeHiddenChars) -> var
    {
        var result;

        let result = gtktextbuffer_get_text(handle, startOffset, endOffset, includeHiddenChars);

        return result;
    }

    public static function insertAtCursor(int handle, string text, int len) -> void
    {
        gtktextbuffer_insert_at_cursor(handle, text, len);
    }

    public static function insertInteractiveAtCursor(int handle, string text, int len, bool defaultEditable) -> bool
    {
        int r;

        let r = gtktextbuffer_insert_interactive_at_cursor(handle, text, len, defaultEditable);

        return r == 1;
    }

    public static function redo(int handle) -> void
    {
        gtktextbuffer_redo(handle);
    }

    public static function removeCommitNotify(int handle, int commitNotifyHandler) -> void
    {
        gtktextbuffer_remove_commit_notify(handle, commitNotifyHandler);
    }

    public static function removeSelectionClipboard(int handle, int clipboard) -> void
    {
        gtktextbuffer_remove_selection_clipboard(handle, clipboard);
    }

    public static function setEnableUndo(int handle, bool enableUndo) -> void
    {
        gtktextbuffer_set_enable_undo(handle, enableUndo);
    }

    public static function setMaxUndoLevels(int handle, int maxUndoLevels) -> void
    {
        gtktextbuffer_set_max_undo_levels(handle, maxUndoLevels);
    }

    public static function setModified(int handle, bool setting) -> void
    {
        gtktextbuffer_set_modified(handle, setting);
    }

    public static function setText(int handle, string text, int len) -> void
    {
        gtktextbuffer_set_text(handle, text, len);
    }

    public static function undo(int handle) -> void
    {
        gtktextbuffer_undo(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "cursor-position" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved gtk_text_buffer_add_commit_notify(GtkTextBufferNotifyFlags flags, GtkTextBufferCommitNotify commit_notify, gpointer user_data, GDestroyNotify destroy) — non-signal callback
    // @reserved gtk_text_buffer_add_mark(GtkTextMark* mark, const GtkTextIter* where) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_apply_tag(GtkTextTag* tag, const GtkTextIter* start, const GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_apply_tag_by_name(const char* name, const GtkTextIter* start, const GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_backspace(GtkTextIter* iter, gboolean interactive, gboolean default_editable) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_create_child_anchor(GtkTextIter* iter) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_create_mark(const char* mark_name, const GtkTextIter* where, gboolean left_gravity) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_create_tag(const char* tag_name, const char* first_property_name, varargs ...) — varargs
    // @reserved gtk_text_buffer_delete(GtkTextIter* start, GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_delete_interactive(GtkTextIter* start_iter, GtkTextIter* end_iter, gboolean default_editable) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_bounds(GtkTextIter* start, GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_end_iter(GtkTextIter* iter) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_iter_at_child_anchor(GtkTextIter* iter, GtkTextChildAnchor* anchor) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_iter_at_line(GtkTextIter* iter, int line_number) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_iter_at_line_index(GtkTextIter* iter, int line_number, int byte_index) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_iter_at_line_offset(GtkTextIter* iter, int line_number, int char_offset) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_iter_at_mark(GtkTextIter* iter, GtkTextMark* mark) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_iter_at_offset(GtkTextIter* iter, int char_offset) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_selection_bounds(GtkTextIter* start, GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_selection_content(void) — GdkContentProvider*
    // @reserved gtk_text_buffer_get_slice(const GtkTextIter* start, const GtkTextIter* end, gboolean include_hidden_chars) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_get_start_iter(GtkTextIter* iter) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert(GtkTextIter* iter, const char* text, int len) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_child_anchor(GtkTextIter* iter, GtkTextChildAnchor* anchor) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_interactive(GtkTextIter* iter, const char* text, int len, gboolean default_editable) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_markup(GtkTextIter* iter, const char* markup, int len) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_paintable(GtkTextIter* iter, GdkPaintable* paintable) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_range(GtkTextIter* iter, const GtkTextIter* start, const GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_range_interactive(GtkTextIter* iter, const GtkTextIter* start, const GtkTextIter* end, gboolean default_editable) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_with_tags(GtkTextIter* iter, const char* text, int len, GtkTextTag* first_tag, varargs ...) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_insert_with_tags_by_name(GtkTextIter* iter, const char* text, int len, const char* first_tag_name, varargs ...) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_move_mark(GtkTextMark* mark, const GtkTextIter* where) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_move_mark_by_name(const char* name, const GtkTextIter* where) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_paste_clipboard(GdkClipboard* clipboard, GtkTextIter* override_location, gboolean default_editable) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_place_cursor(const GtkTextIter* where) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_remove_all_tags(const GtkTextIter* start, const GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_remove_tag(GtkTextTag* tag, const GtkTextIter* start, const GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_remove_tag_by_name(const char* name, const GtkTextIter* start, const GtkTextIter* end) — GtkTextIter* / stack boxed
    // @reserved gtk_text_buffer_select_range(const GtkTextIter* ins, const GtkTextIter* bound) — GtkTextIter* / stack boxed

}
