// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkNoSelection;

class GtkNoSelection
{
    public static function new_(int model) -> int
    {
        return gtknoselection_new(model);
    }

    public static function getModel(int handle) -> int
    {
        return gtknoselection_get_model(handle);
    }

    public static function setModel(int handle, int model) -> void
    {
        gtknoselection_set_model(handle, model);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "item-type" — getter lives on GListModel; use Bridge::getProperty
    // @reserved property "n-items" — getter lives on GListModel; use Bridge::getProperty

}
