// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkRevealer;

class GtkRevealer
{
    public static function new_() -> int
    {
        return gtkrevealer_new();
    }

    public static function getChild(int handle) -> int
    {
        return gtkrevealer_get_child(handle);
    }

    public static function getChildRevealed(int handle) -> bool
    {
        int r;

        let r = gtkrevealer_get_child_revealed(handle);

        return r == 1;
    }

    public static function getRevealChild(int handle) -> bool
    {
        int r;

        let r = gtkrevealer_get_reveal_child(handle);

        return r == 1;
    }

    public static function getTransitionDuration(int handle) -> int
    {
        return gtkrevealer_get_transition_duration(handle);
    }

    public static function getTransitionType(int handle) -> int
    {
        return gtkrevealer_get_transition_type(handle);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkrevealer_set_child(handle, child);
    }

    public static function setRevealChild(int handle, bool revealChild) -> void
    {
        gtkrevealer_set_reveal_child(handle, revealChild);
    }

    public static function setTransitionDuration(int handle, int duration) -> void
    {
        gtkrevealer_set_transition_duration(handle, duration);
    }

    public static function setTransitionType(int handle, int transition) -> void
    {
        gtkrevealer_set_transition_type(handle, transition);
    }
}
