// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkSeparator;

class GtkSeparator
{
    public static function new_(int orientation) -> int
    {
        return gtkseparator_new(orientation);
    }
}
