// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkEditable;

class GtkEditable
{
    public static function delegateGetAccessiblePlatformState(int handle, int state) -> bool
    {
        int r;

        let r = gtkeditable_delegate_get_accessible_platform_state(handle, state);

        return r == 1;
    }

    public static function deleteSelection(int handle) -> void
    {
        gtkeditable_delete_selection(handle);
    }

    public static function deleteText(int handle, int startPos, int endPos) -> void
    {
        gtkeditable_delete_text(handle, startPos, endPos);
    }

    public static function finishDelegate(int handle) -> void
    {
        gtkeditable_finish_delegate(handle);
    }

    public static function getAlignment(int handle) -> double
    {
        return gtkeditable_get_alignment(handle);
    }

    public static function getChars(int handle, int startPos, int endPos) -> var
    {
        var result;

        let result = gtkeditable_get_chars(handle, startPos, endPos);

        return result;
    }

    public static function getDelegate(int handle) -> int
    {
        return gtkeditable_get_delegate(handle);
    }

    public static function getEditable(int handle) -> bool
    {
        int r;

        let r = gtkeditable_get_editable(handle);

        return r == 1;
    }

    public static function getEnableUndo(int handle) -> bool
    {
        int r;

        let r = gtkeditable_get_enable_undo(handle);

        return r == 1;
    }

    public static function getMaxWidthChars(int handle) -> int
    {
        return gtkeditable_get_max_width_chars(handle);
    }

    public static function getPosition(int handle) -> int
    {
        return gtkeditable_get_position(handle);
    }

    public static function getSelectionBounds(int handle) -> array
    {
        var result;

        let result = gtkeditable_get_selection_bounds(handle);

        return result;
    }

    public static function getText(int handle) -> var
    {
        var result;

        let result = gtkeditable_get_text(handle);

        return result;
    }

    public static function getWidthChars(int handle) -> int
    {
        return gtkeditable_get_width_chars(handle);
    }

    public static function initDelegate(int handle) -> void
    {
        gtkeditable_init_delegate(handle);
    }

    public static function insertText(int handle, string text, int length, int position) -> array
    {
        var result;

        let result = gtkeditable_insert_text(handle, text, length, position);

        return result;
    }

    public static function selectRegion(int handle, int startPos, int endPos) -> void
    {
        gtkeditable_select_region(handle, startPos, endPos);
    }

    public static function setAlignment(int handle, double xalign) -> void
    {
        gtkeditable_set_alignment(handle, xalign);
    }

    public static function setEditable(int handle, bool isEditable) -> void
    {
        gtkeditable_set_editable(handle, isEditable);
    }

    public static function setEnableUndo(int handle, bool enableUndo) -> void
    {
        gtkeditable_set_enable_undo(handle, enableUndo);
    }

    public static function setMaxWidthChars(int handle, int nChars) -> void
    {
        gtkeditable_set_max_width_chars(handle, nChars);
    }

    public static function setPosition(int handle, int position) -> void
    {
        gtkeditable_set_position(handle, position);
    }

    public static function setText(int handle, string text) -> void
    {
        gtkeditable_set_text(handle, text);
    }

    public static function setWidthChars(int handle, int nChars) -> void
    {
        gtkeditable_set_width_chars(handle, nChars);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "selection-bound" — no C accessor; use getSelectionBounds or Bridge::getProperty
    // @reserved gtk_editable_delegate_get_property(object, prop_id, GValue* value, GParamSpec* pspec) — GValue/GParamSpec implementor helper
    // @reserved gtk_editable_delegate_set_property(object, prop_id, GValue* value, GParamSpec* pspec) — GValue/GParamSpec implementor helper
    // @reserved gtk_editable_install_properties(GObjectClass* object_class, first_prop) — GObjectClass implementor helper

}
