// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkScrolledWindow;

class GtkScrolledWindow
{
    public static function new_() -> int
    {
        return gtkscrolledwindow_new();
    }

    public static function getChild(int handle) -> int
    {
        return gtkscrolledwindow_get_child(handle);
    }

    public static function getHadjustment(int handle) -> int
    {
        return gtkscrolledwindow_get_hadjustment(handle);
    }

    public static function getHasFrame(int handle) -> bool
    {
        int r;

        let r = gtkscrolledwindow_get_has_frame(handle);

        return r == 1;
    }

    public static function getHscrollbar(int handle) -> int
    {
        return gtkscrolledwindow_get_hscrollbar(handle);
    }

    public static function getKineticScrolling(int handle) -> bool
    {
        int r;

        let r = gtkscrolledwindow_get_kinetic_scrolling(handle);

        return r == 1;
    }

    public static function getMaxContentHeight(int handle) -> int
    {
        return gtkscrolledwindow_get_max_content_height(handle);
    }

    public static function getMaxContentWidth(int handle) -> int
    {
        return gtkscrolledwindow_get_max_content_width(handle);
    }

    public static function getMinContentHeight(int handle) -> int
    {
        return gtkscrolledwindow_get_min_content_height(handle);
    }

    public static function getMinContentWidth(int handle) -> int
    {
        return gtkscrolledwindow_get_min_content_width(handle);
    }

    public static function getOverlayScrolling(int handle) -> bool
    {
        int r;

        let r = gtkscrolledwindow_get_overlay_scrolling(handle);

        return r == 1;
    }

    public static function getPlacement(int handle) -> int
    {
        return gtkscrolledwindow_get_placement(handle);
    }

    public static function getPolicy(int handle) -> array
    {
        var result;

        let result = gtkscrolledwindow_get_policy(handle);

        return result;
    }

    public static function getPropagateNaturalHeight(int handle) -> bool
    {
        int r;

        let r = gtkscrolledwindow_get_propagate_natural_height(handle);

        return r == 1;
    }

    public static function getPropagateNaturalWidth(int handle) -> bool
    {
        int r;

        let r = gtkscrolledwindow_get_propagate_natural_width(handle);

        return r == 1;
    }

    public static function getVadjustment(int handle) -> int
    {
        return gtkscrolledwindow_get_vadjustment(handle);
    }

    public static function getVscrollbar(int handle) -> int
    {
        return gtkscrolledwindow_get_vscrollbar(handle);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkscrolledwindow_set_child(handle, child);
    }

    public static function setHadjustment(int handle, int hadjustment) -> void
    {
        gtkscrolledwindow_set_hadjustment(handle, hadjustment);
    }

    public static function setHasFrame(int handle, bool hasFrame) -> void
    {
        gtkscrolledwindow_set_has_frame(handle, hasFrame);
    }

    public static function setKineticScrolling(int handle, bool kineticScrolling) -> void
    {
        gtkscrolledwindow_set_kinetic_scrolling(handle, kineticScrolling);
    }

    public static function setMaxContentHeight(int handle, int height) -> void
    {
        gtkscrolledwindow_set_max_content_height(handle, height);
    }

    public static function setMaxContentWidth(int handle, int width) -> void
    {
        gtkscrolledwindow_set_max_content_width(handle, width);
    }

    public static function setMinContentHeight(int handle, int height) -> void
    {
        gtkscrolledwindow_set_min_content_height(handle, height);
    }

    public static function setMinContentWidth(int handle, int width) -> void
    {
        gtkscrolledwindow_set_min_content_width(handle, width);
    }

    public static function setOverlayScrolling(int handle, bool overlayScrolling) -> void
    {
        gtkscrolledwindow_set_overlay_scrolling(handle, overlayScrolling);
    }

    public static function setPlacement(int handle, int windowPlacement) -> void
    {
        gtkscrolledwindow_set_placement(handle, windowPlacement);
    }

    public static function setPolicy(int handle, int hscrollbarPolicy, int vscrollbarPolicy) -> void
    {
        gtkscrolledwindow_set_policy(handle, hscrollbarPolicy, vscrollbarPolicy);
    }

    public static function setPropagateNaturalHeight(int handle, bool propagate) -> void
    {
        gtkscrolledwindow_set_propagate_natural_height(handle, propagate);
    }

    public static function setPropagateNaturalWidth(int handle, bool propagate) -> void
    {
        gtkscrolledwindow_set_propagate_natural_width(handle, propagate);
    }

    public static function setVadjustment(int handle, int vadjustment) -> void
    {
        gtkscrolledwindow_set_vadjustment(handle, vadjustment);
    }

    public static function unsetPlacement(int handle) -> void
    {
        gtkscrolledwindow_unset_placement(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "hscrollbar-policy" — no dedicated C accessor; use getPolicy/setPolicy or Bridge::getProperty/setProperty
    // @reserved property "vscrollbar-policy" — no dedicated C accessor; use getPolicy/setPolicy or Bridge::getProperty/setProperty

}
