
extern zend_class_entry *gtk_gtk_passwordentry_gtkpasswordentry_ce;

ZEPHIR_INIT_CLASS(Gtk_GTK_PasswordEntry_GtkPasswordEntry);

PHP_METHOD(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntryNew);
PHP_METHOD(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntrySetText);
PHP_METHOD(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntryGetText);
PHP_METHOD(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntrySetShowPeekIcon);
PHP_METHOD(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntryGetShowPeekIcon);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrynew, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrysettext, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, entry, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrygettext, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, entry, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrysetshowpeekicon, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, entry, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, showPeek, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrygetshowpeekicon, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, entry, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(gtk_gtk_passwordentry_gtkpasswordentry_method_entry) {
	PHP_ME(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntryNew, arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrynew, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntrySetText, arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrysettext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntryGetText, arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrygettext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntrySetShowPeekIcon, arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrysetshowpeekicon, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_GTK_PasswordEntry_GtkPasswordEntry, gtkPasswordEntryGetShowPeekIcon, arginfo_gtk_gtk_passwordentry_gtkpasswordentry_gtkpasswordentrygetshowpeekicon, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
