// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkWidget;

class GtkWidget
{
    public static function getDefaultDirection() -> int
    {
        return gtkwidget_get_default_direction();
    }

    public static function setDefaultDirection(int dir) -> void
    {
        gtkwidget_set_default_direction(dir);
    }

    public static function actionSetEnabled(int handle, string actionName, bool enabled) -> void
    {
        gtkwidget_action_set_enabled(handle, actionName, enabled);
    }

    public static function activate(int handle) -> bool
    {
        int r;

        let r = gtkwidget_activate(handle);

        return r == 1;
    }

    public static function activateDefault(int handle) -> void
    {
        gtkwidget_activate_default(handle);
    }

    public static function addController(int handle, int controller) -> void
    {
        gtkwidget_add_controller(handle, controller);
    }

    public static function addCssClass(int handle, string cssClass) -> void
    {
        gtkwidget_add_css_class(handle, cssClass);
    }

    public static function addMnemonicLabel(int handle, int label) -> void
    {
        gtkwidget_add_mnemonic_label(handle, label);
    }

    public static function childFocus(int handle, int direction) -> bool
    {
        int r;

        let r = gtkwidget_child_focus(handle, direction);

        return r == 1;
    }

    public static function computeBounds(int handle, int target) -> var
    {
        var result;

        let result = gtkwidget_compute_bounds(handle, target);

        return result;
    }

    public static function computeExpand(int handle, int orientation) -> bool
    {
        int r;

        let r = gtkwidget_compute_expand(handle, orientation);

        return r == 1;
    }

    public static function computePoint(int handle, int target, double pointX, double pointY) -> var
    {
        var result;

        let result = gtkwidget_compute_point(handle, target, pointX, pointY);

        return result;
    }

    public static function contains(int handle, double x, double y) -> bool
    {
        int r;

        let r = gtkwidget_contains(handle, x, y);

        return r == 1;
    }

    public static function createPangoContext(int handle) -> int
    {
        return gtkwidget_create_pango_context(handle);
    }

    public static function createPangoLayout(int handle, var text) -> int
    {
        return gtkwidget_create_pango_layout(handle, text);
    }

    public static function disposeTemplate(int handle, int widgetType) -> void
    {
        gtkwidget_dispose_template(handle, widgetType);
    }

    public static function dragCheckThreshold(int handle, int startX, int startY, int currentX, int currentY) -> bool
    {
        int r;

        let r = gtkwidget_drag_check_threshold(handle, startX, startY, currentX, currentY);

        return r == 1;
    }

    public static function errorBell(int handle) -> void
    {
        gtkwidget_error_bell(handle);
    }

    public static function getAncestor(int handle, int widgetType) -> int
    {
        return gtkwidget_get_ancestor(handle, widgetType);
    }

    public static function getBaseline(int handle) -> int
    {
        return gtkwidget_get_baseline(handle);
    }

    public static function getCanFocus(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_can_focus(handle);

        return r == 1;
    }

    public static function getCanTarget(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_can_target(handle);

        return r == 1;
    }

    public static function getChildVisible(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_child_visible(handle);

        return r == 1;
    }

    public static function getClipboard(int handle) -> int
    {
        return gtkwidget_get_clipboard(handle);
    }

    public static function getColor(int handle) -> array
    {
        var result;

        let result = gtkwidget_get_color(handle);

        return result;
    }

    public static function getCssClasses(int handle) -> array
    {
        var result;

        let result = gtkwidget_get_css_classes(handle);

        return result;
    }

    public static function getCssName(int handle) -> string
    {
        var result;

        let result = gtkwidget_get_css_name(handle);

        return result;
    }

    public static function getCursor(int handle) -> int
    {
        return gtkwidget_get_cursor(handle);
    }

    public static function getDirection(int handle) -> int
    {
        return gtkwidget_get_direction(handle);
    }

    public static function getDisplay(int handle) -> int
    {
        return gtkwidget_get_display(handle);
    }

    public static function getFirstChild(int handle) -> int
    {
        return gtkwidget_get_first_child(handle);
    }

    public static function getFocusChild(int handle) -> int
    {
        return gtkwidget_get_focus_child(handle);
    }

    public static function getFocusOnClick(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_focus_on_click(handle);

        return r == 1;
    }

    public static function getFocusable(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_focusable(handle);

        return r == 1;
    }

    public static function getFontMap(int handle) -> int
    {
        return gtkwidget_get_font_map(handle);
    }

    public static function getFrameClock(int handle) -> int
    {
        return gtkwidget_get_frame_clock(handle);
    }

    public static function getHalign(int handle) -> int
    {
        return gtkwidget_get_halign(handle);
    }

    public static function getHasTooltip(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_has_tooltip(handle);

        return r == 1;
    }

    public static function getHeight(int handle) -> int
    {
        return gtkwidget_get_height(handle);
    }

    public static function getHexpand(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_hexpand(handle);

        return r == 1;
    }

    public static function getHexpandSet(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_hexpand_set(handle);

        return r == 1;
    }

    public static function getLastChild(int handle) -> int
    {
        return gtkwidget_get_last_child(handle);
    }

    public static function getLayoutManager(int handle) -> int
    {
        return gtkwidget_get_layout_manager(handle);
    }

    public static function getLimitEvents(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_limit_events(handle);

        return r == 1;
    }

    public static function getMapped(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_mapped(handle);

        return r == 1;
    }

    public static function getMarginBottom(int handle) -> int
    {
        return gtkwidget_get_margin_bottom(handle);
    }

    public static function getMarginEnd(int handle) -> int
    {
        return gtkwidget_get_margin_end(handle);
    }

    public static function getMarginStart(int handle) -> int
    {
        return gtkwidget_get_margin_start(handle);
    }

    public static function getMarginTop(int handle) -> int
    {
        return gtkwidget_get_margin_top(handle);
    }

    public static function getName(int handle) -> string
    {
        var result;

        let result = gtkwidget_get_name(handle);

        return result;
    }

    public static function getNative(int handle) -> int
    {
        return gtkwidget_get_native(handle);
    }

    public static function getNextSibling(int handle) -> int
    {
        return gtkwidget_get_next_sibling(handle);
    }

    public static function getOpacity(int handle) -> double
    {
        return gtkwidget_get_opacity(handle);
    }

    public static function getOverflow(int handle) -> int
    {
        return gtkwidget_get_overflow(handle);
    }

    public static function getPangoContext(int handle) -> int
    {
        return gtkwidget_get_pango_context(handle);
    }

    public static function getParent(int handle) -> int
    {
        return gtkwidget_get_parent(handle);
    }

    public static function getPreferredSize(int handle) -> array
    {
        var result;

        let result = gtkwidget_get_preferred_size(handle);

        return result;
    }

    public static function getPrevSibling(int handle) -> int
    {
        return gtkwidget_get_prev_sibling(handle);
    }

    public static function getPrimaryClipboard(int handle) -> int
    {
        return gtkwidget_get_primary_clipboard(handle);
    }

    public static function getRealized(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_realized(handle);

        return r == 1;
    }

    public static function getReceivesDefault(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_receives_default(handle);

        return r == 1;
    }

    public static function getRequestMode(int handle) -> int
    {
        return gtkwidget_get_request_mode(handle);
    }

    public static function getRoot(int handle) -> int
    {
        return gtkwidget_get_root(handle);
    }

    public static function getScaleFactor(int handle) -> int
    {
        return gtkwidget_get_scale_factor(handle);
    }

    public static function getSensitive(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_sensitive(handle);

        return r == 1;
    }

    public static function getSettings(int handle) -> int
    {
        return gtkwidget_get_settings(handle);
    }

    public static function getSize(int handle, int orientation) -> int
    {
        return gtkwidget_get_size(handle, orientation);
    }

    public static function getSizeRequest(int handle) -> array
    {
        var result;

        let result = gtkwidget_get_size_request(handle);

        return result;
    }

    public static function getStateFlags(int handle) -> int
    {
        return gtkwidget_get_state_flags(handle);
    }

    public static function getTemplateChild(int handle, int widgetType, string name) -> int
    {
        return gtkwidget_get_template_child(handle, widgetType, name);
    }

    public static function getTooltipMarkup(int handle) -> var
    {
        var result;

        let result = gtkwidget_get_tooltip_markup(handle);

        return result;
    }

    public static function getTooltipText(int handle) -> var
    {
        var result;

        let result = gtkwidget_get_tooltip_text(handle);

        return result;
    }

    public static function getValign(int handle) -> int
    {
        return gtkwidget_get_valign(handle);
    }

    public static function getVexpand(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_vexpand(handle);

        return r == 1;
    }

    public static function getVexpandSet(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_vexpand_set(handle);

        return r == 1;
    }

    public static function getVisible(int handle) -> bool
    {
        int r;

        let r = gtkwidget_get_visible(handle);

        return r == 1;
    }

    public static function getWidth(int handle) -> int
    {
        return gtkwidget_get_width(handle);
    }

    public static function grabFocus(int handle) -> bool
    {
        int r;

        let r = gtkwidget_grab_focus(handle);

        return r == 1;
    }

    public static function hasCssClass(int handle, string cssClass) -> bool
    {
        int r;

        let r = gtkwidget_has_css_class(handle, cssClass);

        return r == 1;
    }

    public static function hasDefault(int handle) -> bool
    {
        int r;

        let r = gtkwidget_has_default(handle);

        return r == 1;
    }

    public static function hasFocus(int handle) -> bool
    {
        int r;

        let r = gtkwidget_has_focus(handle);

        return r == 1;
    }

    public static function hasVisibleFocus(int handle) -> bool
    {
        int r;

        let r = gtkwidget_has_visible_focus(handle);

        return r == 1;
    }

    public static function inDestruction(int handle) -> bool
    {
        int r;

        let r = gtkwidget_in_destruction(handle);

        return r == 1;
    }

    public static function initTemplate(int handle) -> void
    {
        gtkwidget_init_template(handle);
    }

    public static function insertActionGroup(int handle, string name, int group) -> void
    {
        gtkwidget_insert_action_group(handle, name, group);
    }

    public static function insertAfter(int handle, int parent, int previousSibling) -> void
    {
        gtkwidget_insert_after(handle, parent, previousSibling);
    }

    public static function insertBefore(int handle, int parent, int nextSibling) -> void
    {
        gtkwidget_insert_before(handle, parent, nextSibling);
    }

    public static function isAncestor(int handle, int ancestor) -> bool
    {
        int r;

        let r = gtkwidget_is_ancestor(handle, ancestor);

        return r == 1;
    }

    public static function isDrawable(int handle) -> bool
    {
        int r;

        let r = gtkwidget_is_drawable(handle);

        return r == 1;
    }

    public static function isFocus(int handle) -> bool
    {
        int r;

        let r = gtkwidget_is_focus(handle);

        return r == 1;
    }

    public static function isSensitive(int handle) -> bool
    {
        int r;

        let r = gtkwidget_is_sensitive(handle);

        return r == 1;
    }

    public static function isVisible(int handle) -> bool
    {
        int r;

        let r = gtkwidget_is_visible(handle);

        return r == 1;
    }

    public static function keynavFailed(int handle, int direction) -> bool
    {
        int r;

        let r = gtkwidget_keynav_failed(handle, direction);

        return r == 1;
    }

    public static function listMnemonicLabels(int handle) -> array
    {
        var result;

        let result = gtkwidget_list_mnemonic_labels(handle);

        return result;
    }

    public static function map(int handle) -> void
    {
        gtkwidget_map(handle);
    }

    public static function measure(int handle, int orientation, int forSize) -> array
    {
        var result;

        let result = gtkwidget_measure(handle, orientation, forSize);

        return result;
    }

    public static function mnemonicActivate(int handle, bool groupCycling) -> bool
    {
        int r;

        let r = gtkwidget_mnemonic_activate(handle, groupCycling);

        return r == 1;
    }

    public static function observeChildren(int handle) -> int
    {
        return gtkwidget_observe_children(handle);
    }

    public static function observeControllers(int handle) -> int
    {
        return gtkwidget_observe_controllers(handle);
    }

    public static function pick(int handle, double x, double y, int flags) -> int
    {
        return gtkwidget_pick(handle, x, y, flags);
    }

    public static function queueAllocate(int handle) -> void
    {
        gtkwidget_queue_allocate(handle);
    }

    public static function queueDraw(int handle) -> void
    {
        gtkwidget_queue_draw(handle);
    }

    public static function queueResize(int handle) -> void
    {
        gtkwidget_queue_resize(handle);
    }

    public static function realize(int handle) -> void
    {
        gtkwidget_realize(handle);
    }

    public static function removeController(int handle, int controller) -> void
    {
        gtkwidget_remove_controller(handle, controller);
    }

    public static function removeCssClass(int handle, string cssClass) -> void
    {
        gtkwidget_remove_css_class(handle, cssClass);
    }

    public static function removeMnemonicLabel(int handle, int label) -> void
    {
        gtkwidget_remove_mnemonic_label(handle, label);
    }

    public static function removeTickCallback(int handle, int id) -> void
    {
        gtkwidget_remove_tick_callback(handle, id);
    }

    public static function setCanFocus(int handle, bool canFocus) -> void
    {
        gtkwidget_set_can_focus(handle, canFocus);
    }

    public static function setCanTarget(int handle, bool canTarget) -> void
    {
        gtkwidget_set_can_target(handle, canTarget);
    }

    public static function setChildVisible(int handle, bool childVisible) -> void
    {
        gtkwidget_set_child_visible(handle, childVisible);
    }

    public static function setCssClasses(int handle, array classes) -> void
    {
        gtkwidget_set_css_classes(handle, classes);
    }

    public static function setCursor(int handle, int cursor) -> void
    {
        gtkwidget_set_cursor(handle, cursor);
    }

    public static function setCursorFromName(int handle, var name) -> void
    {
        gtkwidget_set_cursor_from_name(handle, name);
    }

    public static function setDirection(int handle, int dir) -> void
    {
        gtkwidget_set_direction(handle, dir);
    }

    public static function setFocusChild(int handle, int child) -> void
    {
        gtkwidget_set_focus_child(handle, child);
    }

    public static function setFocusOnClick(int handle, bool focusOnClick) -> void
    {
        gtkwidget_set_focus_on_click(handle, focusOnClick);
    }

    public static function setFocusable(int handle, bool focusable) -> void
    {
        gtkwidget_set_focusable(handle, focusable);
    }

    public static function setFontMap(int handle, int fontMap) -> void
    {
        gtkwidget_set_font_map(handle, fontMap);
    }

    public static function setHalign(int handle, int align) -> void
    {
        gtkwidget_set_halign(handle, align);
    }

    public static function setHasTooltip(int handle, bool hasTooltip) -> void
    {
        gtkwidget_set_has_tooltip(handle, hasTooltip);
    }

    public static function setHexpand(int handle, bool expand) -> void
    {
        gtkwidget_set_hexpand(handle, expand);
    }

    public static function setHexpandSet(int handle, bool set) -> void
    {
        gtkwidget_set_hexpand_set(handle, set);
    }

    public static function setLayoutManager(int handle, int layoutManager) -> void
    {
        gtkwidget_set_layout_manager(handle, layoutManager);
    }

    public static function setLimitEvents(int handle, bool limitEvents) -> void
    {
        gtkwidget_set_limit_events(handle, limitEvents);
    }

    public static function setMarginBottom(int handle, int margin) -> void
    {
        gtkwidget_set_margin_bottom(handle, margin);
    }

    public static function setMarginEnd(int handle, int margin) -> void
    {
        gtkwidget_set_margin_end(handle, margin);
    }

    public static function setMarginStart(int handle, int margin) -> void
    {
        gtkwidget_set_margin_start(handle, margin);
    }

    public static function setMarginTop(int handle, int margin) -> void
    {
        gtkwidget_set_margin_top(handle, margin);
    }

    public static function setName(int handle, string name) -> void
    {
        gtkwidget_set_name(handle, name);
    }

    public static function setOpacity(int handle, double opacity) -> void
    {
        gtkwidget_set_opacity(handle, opacity);
    }

    public static function setOverflow(int handle, int overflow) -> void
    {
        gtkwidget_set_overflow(handle, overflow);
    }

    public static function setParent(int handle, int parent) -> void
    {
        gtkwidget_set_parent(handle, parent);
    }

    public static function setReceivesDefault(int handle, bool receivesDefault) -> void
    {
        gtkwidget_set_receives_default(handle, receivesDefault);
    }

    public static function setSensitive(int handle, bool sensitive) -> void
    {
        gtkwidget_set_sensitive(handle, sensitive);
    }

    public static function setSizeRequest(int handle, int width, int height) -> void
    {
        gtkwidget_set_size_request(handle, width, height);
    }

    public static function setStateFlags(int handle, int flags, bool clear) -> void
    {
        gtkwidget_set_state_flags(handle, flags, clear);
    }

    public static function setTooltipMarkup(int handle, var markup) -> void
    {
        gtkwidget_set_tooltip_markup(handle, markup);
    }

    public static function setTooltipText(int handle, var text) -> void
    {
        gtkwidget_set_tooltip_text(handle, text);
    }

    public static function setValign(int handle, int align) -> void
    {
        gtkwidget_set_valign(handle, align);
    }

    public static function setVexpand(int handle, bool expand) -> void
    {
        gtkwidget_set_vexpand(handle, expand);
    }

    public static function setVexpandSet(int handle, bool set) -> void
    {
        gtkwidget_set_vexpand_set(handle, set);
    }

    public static function setVisible(int handle, bool visible) -> void
    {
        gtkwidget_set_visible(handle, visible);
    }

    public static function shouldLayout(int handle) -> bool
    {
        int r;

        let r = gtkwidget_should_layout(handle);

        return r == 1;
    }

    public static function sizeAllocate(int handle, int allocationX, int allocationY, int allocationWidth, int allocationHeight, int baseline) -> void
    {
        gtkwidget_size_allocate(handle, allocationX, allocationY, allocationWidth, allocationHeight, baseline);
    }

    public static function snapshotChild(int handle, int child, int snapshot) -> void
    {
        gtkwidget_snapshot_child(handle, child, snapshot);
    }

    public static function triggerTooltipQuery(int handle) -> void
    {
        gtkwidget_trigger_tooltip_query(handle);
    }

    public static function unmap(int handle) -> void
    {
        gtkwidget_unmap(handle);
    }

    public static function unparent(int handle) -> void
    {
        gtkwidget_unparent(handle);
    }

    public static function unrealize(int handle) -> void
    {
        gtkwidget_unrealize(handle);
    }

    public static function unsetStateFlags(int handle, int flags) -> void
    {
        gtkwidget_unset_state_flags(handle, flags);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "height-request" — no dedicated C accessor; use getSizeRequest/setSizeRequest or Bridge::getProperty
    // @reserved property "width-request" — no dedicated C accessor; use getSizeRequest/setSizeRequest or Bridge::getProperty
    // @reserved gtk_widget_activate_action(self, char* name, char* format_string, ... ...) — varargs
    // @reserved gtk_widget_activate_action_variant(self, char* name, GVariant* args) — GVariant*
    // @reserved gtk_widget_add_tick_callback(self, GtkTickCallback callback, gpointer user_data, GDestroyNotify notify) — non-signal callback
    // @reserved gtk_widget_allocate(self, int width, int height, int baseline, GskTransform* transform) — GskTransform* boxed
    // @reserved gtk_widget_compute_transform(self, GtkWidget* target, graphene_matrix_t* out_transform) — graphene_matrix_t
    // @reserved gtk_widget_get_allocated_baseline(self) — deprecated
    // @reserved gtk_widget_get_allocated_height(self) — deprecated
    // @reserved gtk_widget_get_allocated_width(self) — deprecated
    // @reserved gtk_widget_get_allocation(self, GtkAllocation* allocation) — deprecated
    // @reserved gtk_widget_get_font_options(self) — deprecated
    // @reserved gtk_widget_get_style_context(self) — deprecated
    // @reserved gtk_widget_hide(self) — deprecated
    // @reserved gtk_widget_set_font_options(self, cairo_font_options_t* options) — deprecated
    // @reserved gtk_widget_show(self) — deprecated
    // @reserved gtk_widget_translate_coordinates(self, GtkWidget* dest_widget, double src_x, double src_y, double* dest_x, double* dest_y) — deprecated

}
