// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GSimpleAction;

class GSimpleAction
{
    public static function new_(string name) -> int
    {
        return gsimpleaction_new(name);
    }

    public static function setEnabled(int handle, bool enabled) -> void
    {
        gsimpleaction_set_enabled(handle, enabled);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "enabled" — getter lives on GAction; setter is setEnabled
    // @reserved property "name" — getter lives on GAction; construct-only
    // @reserved property "parameter-type" — getter lives on GAction; construct-only
    // @reserved property "state" — getter lives on GAction; setter reserved (GVariant*)
    // @reserved property "state-type" — getter lives on GAction
    // @reserved g_simple_action_new_stateful(name, GVariantType* parameter_type, GVariant* state) — GVariant*
    // @reserved g_simple_action_set_state(self, GVariant* value) — GVariant*
    // @reserved g_simple_action_set_state_hint(self, GVariant* state_hint) — GVariant*

}
