// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkFlowBoxChild;

class GtkFlowBoxChild
{
    public static function new_() -> int
    {
        return gtkflowboxchild_new();
    }

    public static function changed(int handle) -> void
    {
        gtkflowboxchild_changed(handle);
    }

    public static function getChild(int handle) -> int
    {
        return gtkflowboxchild_get_child(handle);
    }

    public static function getIndex(int handle) -> int
    {
        return gtkflowboxchild_get_index(handle);
    }

    public static function isSelected(int handle) -> bool
    {
        int r;

        let r = gtkflowboxchild_is_selected(handle);

        return r == 1;
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkflowboxchild_set_child(handle, child);
    }
}
