// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkGesture;

class GtkGesture
{
    public static function getBoundingBox(int handle) -> var
    {
        var result;

        let result = gtkgesture_get_bounding_box(handle);

        return result;
    }

    public static function getBoundingBoxCenter(int handle) -> var
    {
        var result;

        let result = gtkgesture_get_bounding_box_center(handle);

        return result;
    }

    public static function getDevice(int handle) -> int
    {
        return gtkgesture_get_device(handle);
    }

    public static function getGroup(int handle) -> array
    {
        var result;

        let result = gtkgesture_get_group(handle);

        return result;
    }

    public static function group(int handle, int gesture) -> void
    {
        gtkgesture_group(handle, gesture);
    }

    public static function isActive(int handle) -> bool
    {
        int r;

        let r = gtkgesture_is_active(handle);

        return r == 1;
    }

    public static function isGroupedWith(int handle, int other) -> bool
    {
        int r;

        let r = gtkgesture_is_grouped_with(handle, other);

        return r == 1;
    }

    public static function isRecognized(int handle) -> bool
    {
        int r;

        let r = gtkgesture_is_recognized(handle);

        return r == 1;
    }

    public static function setState(int handle, int state) -> bool
    {
        int r;

        let r = gtkgesture_set_state(handle, state);

        return r == 1;
    }

    public static function ungroup(int handle) -> void
    {
        gtkgesture_ungroup(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_gesture_get_last_event(GtkGesture* gesture, GdkEventSequence* sequence) — GdkEvent* / GdkEventSequence*
    // @reserved gtk_gesture_get_last_updated_sequence(GtkGesture* gesture) — GdkEventSequence*
    // @reserved gtk_gesture_get_point(GtkGesture* gesture, GdkEventSequence* sequence, double* x, double* y) — GdkEventSequence*
    // @reserved gtk_gesture_get_sequence_state(GtkGesture* gesture, GdkEventSequence* sequence) — GdkEventSequence*
    // @reserved gtk_gesture_get_sequences(GtkGesture* gesture) — GList of GdkEventSequence*
    // @reserved gtk_gesture_handles_sequence(GtkGesture* gesture, GdkEventSequence* sequence) — GdkEventSequence*
    // @reserved gtk_gesture_set_sequence_state(GtkGesture* gesture, GdkEventSequence* sequence, GtkEventSequenceState state) — deprecated 4.10
    // @reserved property "n-points" — no C accessor; Bridge::getProperty

}
