// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkCalendar;

class GtkCalendar
{
    public static function new_() -> int
    {
        return gtkcalendar_new();
    }

    public static function clearMarks(int handle) -> void
    {
        gtkcalendar_clear_marks(handle);
    }

    public static function getDay(int handle) -> int
    {
        return gtkcalendar_get_day(handle);
    }

    public static function getDayIsMarked(int handle, int day) -> bool
    {
        int r;

        let r = gtkcalendar_get_day_is_marked(handle, day);

        return r == 1;
    }

    public static function getMonth(int handle) -> int
    {
        return gtkcalendar_get_month(handle);
    }

    public static function getShowDayNames(int handle) -> bool
    {
        int r;

        let r = gtkcalendar_get_show_day_names(handle);

        return r == 1;
    }

    public static function getShowHeading(int handle) -> bool
    {
        int r;

        let r = gtkcalendar_get_show_heading(handle);

        return r == 1;
    }

    public static function getShowWeekNumbers(int handle) -> bool
    {
        int r;

        let r = gtkcalendar_get_show_week_numbers(handle);

        return r == 1;
    }

    public static function getYear(int handle) -> int
    {
        return gtkcalendar_get_year(handle);
    }

    public static function markDay(int handle, int day) -> void
    {
        gtkcalendar_mark_day(handle, day);
    }

    public static function setDay(int handle, int day) -> void
    {
        gtkcalendar_set_day(handle, day);
    }

    public static function setMonth(int handle, int month) -> void
    {
        gtkcalendar_set_month(handle, month);
    }

    public static function setShowDayNames(int handle, bool value) -> void
    {
        gtkcalendar_set_show_day_names(handle, value);
    }

    public static function setShowHeading(int handle, bool value) -> void
    {
        gtkcalendar_set_show_heading(handle, value);
    }

    public static function setShowWeekNumbers(int handle, bool value) -> void
    {
        gtkcalendar_set_show_week_numbers(handle, value);
    }

    public static function setYear(int handle, int year) -> void
    {
        gtkcalendar_set_year(handle, year);
    }

    public static function unmarkDay(int handle, int day) -> void
    {
        gtkcalendar_unmark_day(handle, day);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_calendar_get_date() — GDateTime*
    // @reserved gtk_calendar_select_day(GDateTime* date) — GDateTime*

}
