// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkOverlay;

class GtkOverlay
{
    public static function new_() -> int
    {
        return gtkoverlay_new();
    }

    public static function addOverlay(int handle, int widget) -> void
    {
        gtkoverlay_add_overlay(handle, widget);
    }

    public static function getChild(int handle) -> int
    {
        return gtkoverlay_get_child(handle);
    }

    public static function getClipOverlay(int handle, int widget) -> bool
    {
        int r;

        let r = gtkoverlay_get_clip_overlay(handle, widget);

        return r == 1;
    }

    public static function getMeasureOverlay(int handle, int widget) -> bool
    {
        int r;

        let r = gtkoverlay_get_measure_overlay(handle, widget);

        return r == 1;
    }

    public static function removeOverlay(int handle, int widget) -> void
    {
        gtkoverlay_remove_overlay(handle, widget);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkoverlay_set_child(handle, child);
    }

    public static function setClipOverlay(int handle, int widget, bool clipOverlay) -> void
    {
        gtkoverlay_set_clip_overlay(handle, widget, clipOverlay);
    }

    public static function setMeasureOverlay(int handle, int widget, bool measure) -> void
    {
        gtkoverlay_set_measure_overlay(handle, widget, measure);
    }
}
