// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkEntry;

class GtkEntry
{
    public static function new_() -> int
    {
        return gtkentry_new();
    }

    public static function newWithBuffer(int buffer) -> int
    {
        return gtkentry_new_with_buffer(buffer);
    }

    public static function getActivatesDefault(int handle) -> bool
    {
        int r;

        let r = gtkentry_get_activates_default(handle);

        return r == 1;
    }

    public static function getAlignment(int handle) -> double
    {
        return gtkentry_get_alignment(handle);
    }

    public static function getBuffer(int handle) -> int
    {
        return gtkentry_get_buffer(handle);
    }

    public static function getCurrentIconDragSource(int handle) -> int
    {
        return gtkentry_get_current_icon_drag_source(handle);
    }

    public static function getExtraMenu(int handle) -> int
    {
        return gtkentry_get_extra_menu(handle);
    }

    public static function getHasFrame(int handle) -> bool
    {
        int r;

        let r = gtkentry_get_has_frame(handle);

        return r == 1;
    }

    public static function getIconActivatable(int handle, int iconPos) -> bool
    {
        int r;

        let r = gtkentry_get_icon_activatable(handle, iconPos);

        return r == 1;
    }

    public static function getIconArea(int handle, int iconPos) -> array
    {
        var result;

        let result = gtkentry_get_icon_area(handle, iconPos);

        return result;
    }

    public static function getIconAtPos(int handle, int x, int y) -> int
    {
        return gtkentry_get_icon_at_pos(handle, x, y);
    }

    public static function getIconGicon(int handle, int iconPos) -> int
    {
        return gtkentry_get_icon_gicon(handle, iconPos);
    }

    public static function getIconName(int handle, int iconPos) -> var
    {
        var result;

        let result = gtkentry_get_icon_name(handle, iconPos);

        return result;
    }

    public static function getIconPaintable(int handle, int iconPos) -> int
    {
        return gtkentry_get_icon_paintable(handle, iconPos);
    }

    public static function getIconSensitive(int handle, int iconPos) -> bool
    {
        int r;

        let r = gtkentry_get_icon_sensitive(handle, iconPos);

        return r == 1;
    }

    public static function getIconStorageType(int handle, int iconPos) -> int
    {
        return gtkentry_get_icon_storage_type(handle, iconPos);
    }

    public static function getIconTooltipMarkup(int handle, int iconPos) -> var
    {
        var result;

        let result = gtkentry_get_icon_tooltip_markup(handle, iconPos);

        return result;
    }

    public static function getIconTooltipText(int handle, int iconPos) -> var
    {
        var result;

        let result = gtkentry_get_icon_tooltip_text(handle, iconPos);

        return result;
    }

    public static function getInputHints(int handle) -> int
    {
        return gtkentry_get_input_hints(handle);
    }

    public static function getInputPurpose(int handle) -> int
    {
        return gtkentry_get_input_purpose(handle);
    }

    public static function getInvisibleChar(int handle) -> int
    {
        return gtkentry_get_invisible_char(handle);
    }

    public static function getMaxLength(int handle) -> int
    {
        return gtkentry_get_max_length(handle);
    }

    public static function getOverwriteMode(int handle) -> bool
    {
        int r;

        let r = gtkentry_get_overwrite_mode(handle);

        return r == 1;
    }

    public static function getPlaceholderText(int handle) -> var
    {
        var result;

        let result = gtkentry_get_placeholder_text(handle);

        return result;
    }

    public static function getProgressFraction(int handle) -> double
    {
        return gtkentry_get_progress_fraction(handle);
    }

    public static function getProgressPulseStep(int handle) -> double
    {
        return gtkentry_get_progress_pulse_step(handle);
    }

    public static function getTextLength(int handle) -> int
    {
        return gtkentry_get_text_length(handle);
    }

    public static function getVisibility(int handle) -> bool
    {
        int r;

        let r = gtkentry_get_visibility(handle);

        return r == 1;
    }

    public static function grabFocusWithoutSelecting(int handle) -> bool
    {
        int r;

        let r = gtkentry_grab_focus_without_selecting(handle);

        return r == 1;
    }

    public static function progressPulse(int handle) -> void
    {
        gtkentry_progress_pulse(handle);
    }

    public static function resetImContext(int handle) -> void
    {
        gtkentry_reset_im_context(handle);
    }

    public static function setActivatesDefault(int handle, bool setting) -> void
    {
        gtkentry_set_activates_default(handle, setting);
    }

    public static function setAlignment(int handle, double xalign) -> void
    {
        gtkentry_set_alignment(handle, xalign);
    }

    public static function setBuffer(int handle, int buffer) -> void
    {
        gtkentry_set_buffer(handle, buffer);
    }

    public static function setExtraMenu(int handle, int model) -> void
    {
        gtkentry_set_extra_menu(handle, model);
    }

    public static function setHasFrame(int handle, bool setting) -> void
    {
        gtkentry_set_has_frame(handle, setting);
    }

    public static function setIconActivatable(int handle, int iconPos, bool activatable) -> void
    {
        gtkentry_set_icon_activatable(handle, iconPos, activatable);
    }

    public static function setIconFromGicon(int handle, int iconPos, int icon) -> void
    {
        gtkentry_set_icon_from_gicon(handle, iconPos, icon);
    }

    public static function setIconFromIconName(int handle, int iconPos, var iconName) -> void
    {
        gtkentry_set_icon_from_icon_name(handle, iconPos, iconName);
    }

    public static function setIconFromPaintable(int handle, int iconPos, int paintable) -> void
    {
        gtkentry_set_icon_from_paintable(handle, iconPos, paintable);
    }

    public static function setIconSensitive(int handle, int iconPos, bool sensitive) -> void
    {
        gtkentry_set_icon_sensitive(handle, iconPos, sensitive);
    }

    public static function setIconTooltipMarkup(int handle, int iconPos, var tooltip) -> void
    {
        gtkentry_set_icon_tooltip_markup(handle, iconPos, tooltip);
    }

    public static function setIconTooltipText(int handle, int iconPos, var tooltip) -> void
    {
        gtkentry_set_icon_tooltip_text(handle, iconPos, tooltip);
    }

    public static function setInputHints(int handle, int hints) -> void
    {
        gtkentry_set_input_hints(handle, hints);
    }

    public static function setInputPurpose(int handle, int purpose) -> void
    {
        gtkentry_set_input_purpose(handle, purpose);
    }

    public static function setInvisibleChar(int handle, int ch) -> void
    {
        gtkentry_set_invisible_char(handle, ch);
    }

    public static function setMaxLength(int handle, int max) -> void
    {
        gtkentry_set_max_length(handle, max);
    }

    public static function setOverwriteMode(int handle, bool overwrite) -> void
    {
        gtkentry_set_overwrite_mode(handle, overwrite);
    }

    public static function setPlaceholderText(int handle, var text) -> void
    {
        gtkentry_set_placeholder_text(handle, text);
    }

    public static function setProgressFraction(int handle, double fraction) -> void
    {
        gtkentry_set_progress_fraction(handle, fraction);
    }

    public static function setProgressPulseStep(int handle, double fraction) -> void
    {
        gtkentry_set_progress_pulse_step(handle, fraction);
    }

    public static function setVisibility(int handle, bool visible) -> void
    {
        gtkentry_set_visibility(handle, visible);
    }

    public static function unsetInvisibleChar(int handle) -> void
    {
        gtkentry_unset_invisible_char(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "enable-emoji-completion" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "im-module" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "invisible-char-set" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "primary-icon-activatable" — no dedicated C accessor; use getIconActivatable/setIconActivatable or Bridge::getProperty
    // @reserved property "primary-icon-gicon" — no dedicated C accessor; use getIconGicon/setIconFromGicon or Bridge::getProperty
    // @reserved property "primary-icon-name" — no dedicated C accessor; use getIconName/setIconFromIconName or Bridge::getProperty
    // @reserved property "primary-icon-paintable" — no dedicated C accessor; use getIconPaintable/setIconFromPaintable or Bridge::getProperty
    // @reserved property "primary-icon-sensitive" — no dedicated C accessor; use getIconSensitive/setIconSensitive or Bridge::getProperty
    // @reserved property "primary-icon-storage-type" — no dedicated C accessor; use getIconStorageType or Bridge::getProperty
    // @reserved property "primary-icon-tooltip-markup" — no dedicated C accessor; use getIconTooltipMarkup/setIconTooltipMarkup or Bridge::getProperty
    // @reserved property "primary-icon-tooltip-text" — no dedicated C accessor; use getIconTooltipText/setIconTooltipText or Bridge::getProperty
    // @reserved property "scroll-offset" — no C accessor; use Bridge::getProperty
    // @reserved property "secondary-icon-activatable" — no dedicated C accessor; use getIconActivatable/setIconActivatable or Bridge::getProperty
    // @reserved property "secondary-icon-gicon" — no dedicated C accessor; use getIconGicon/setIconFromGicon or Bridge::getProperty
    // @reserved property "secondary-icon-name" — no dedicated C accessor; use getIconName/setIconFromIconName or Bridge::getProperty
    // @reserved property "secondary-icon-paintable" — no dedicated C accessor; use getIconPaintable/setIconFromPaintable or Bridge::getProperty
    // @reserved property "secondary-icon-sensitive" — no dedicated C accessor; use getIconSensitive/setIconSensitive or Bridge::getProperty
    // @reserved property "secondary-icon-storage-type" — no dedicated C accessor; use getIconStorageType or Bridge::getProperty
    // @reserved property "secondary-icon-tooltip-markup" — no dedicated C accessor; use getIconTooltipMarkup/setIconTooltipMarkup or Bridge::getProperty
    // @reserved property "secondary-icon-tooltip-text" — no dedicated C accessor; use getIconTooltipText/setIconTooltipText or Bridge::getProperty
    // @reserved property "show-emoji-icon" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "truncate-multiline" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved gtk_entry_get_attributes(self) — PangoAttrList*
    // @reserved gtk_entry_get_completion(self) — deprecated
    // @reserved gtk_entry_get_tabs(self) — PangoTabArray*
    // @reserved gtk_entry_set_attributes(self, PangoAttrList* attrs) — PangoAttrList*
    // @reserved gtk_entry_set_completion(self, GtkEntryCompletion* completion) — deprecated
    // @reserved gtk_entry_set_icon_drag_source(self, icon_pos, GdkContentProvider* provider, actions) — GdkContentProvider*
    // @reserved gtk_entry_set_tabs(self, PangoTabArray* tabs) — PangoTabArray*

}
