// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkStringList;

class GtkStringList
{
    public static function new_(var strings) -> int
    {
        return gtkstringlist_new(strings);
    }

    public static function append(int handle, string string_) -> void
    {
        gtkstringlist_append(handle, string_);
    }

    public static function find(int handle, string string_) -> int
    {
        return gtkstringlist_find(handle, string_);
    }

    public static function getString(int handle, int position) -> var
    {
        var result;

        let result = gtkstringlist_get_string(handle, position);

        return result;
    }

    public static function remove(int handle, int position) -> void
    {
        gtkstringlist_remove(handle, position);
    }

    public static function splice(int handle, int position, int nRemovals, var additions) -> void
    {
        gtkstringlist_splice(handle, position, nRemovals, additions);
    }

    public static function take(int handle, string string_) -> void
    {
        gtkstringlist_take(handle, string_);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "item-type" — getter lives on GListModel; use Bridge::getProperty
    // @reserved property "n-items" — getter lives on GListModel; use Bridge::getProperty
    // @reserved property "strings" — no C accessor; construct-only; use Bridge::getProperty

}
