// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkListBoxRow;

class GtkListBoxRow
{
    public static function new_() -> int
    {
        return gtklistboxrow_new();
    }

    public static function changed(int handle) -> void
    {
        gtklistboxrow_changed(handle);
    }

    public static function getActivatable(int handle) -> bool
    {
        int r;

        let r = gtklistboxrow_get_activatable(handle);

        return r == 1;
    }

    public static function getChild(int handle) -> int
    {
        return gtklistboxrow_get_child(handle);
    }

    public static function getHeader(int handle) -> int
    {
        return gtklistboxrow_get_header(handle);
    }

    public static function getIndex(int handle) -> int
    {
        return gtklistboxrow_get_index(handle);
    }

    public static function getSelectable(int handle) -> bool
    {
        int r;

        let r = gtklistboxrow_get_selectable(handle);

        return r == 1;
    }

    public static function isSelected(int handle) -> bool
    {
        int r;

        let r = gtklistboxrow_is_selected(handle);

        return r == 1;
    }

    public static function setActivatable(int handle, bool activatable) -> void
    {
        gtklistboxrow_set_activatable(handle, activatable);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtklistboxrow_set_child(handle, child);
    }

    public static function setHeader(int handle, int header) -> void
    {
        gtklistboxrow_set_header(handle, header);
    }

    public static function setSelectable(int handle, bool selectable) -> void
    {
        gtklistboxrow_set_selectable(handle, selectable);
    }
}
