// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkEventController;

class GtkEventController
{
    public static function getCurrentEventDevice(int handle) -> int
    {
        return gtkeventcontroller_get_current_event_device(handle);
    }

    public static function getCurrentEventState(int handle) -> int
    {
        return gtkeventcontroller_get_current_event_state(handle);
    }

    public static function getCurrentEventTime(int handle) -> int
    {
        return gtkeventcontroller_get_current_event_time(handle);
    }

    public static function getName(int handle) -> var
    {
        var result;

        let result = gtkeventcontroller_get_name(handle);

        return result;
    }

    public static function getPropagationLimit(int handle) -> int
    {
        return gtkeventcontroller_get_propagation_limit(handle);
    }

    public static function getPropagationPhase(int handle) -> int
    {
        return gtkeventcontroller_get_propagation_phase(handle);
    }

    public static function getWidget(int handle) -> int
    {
        return gtkeventcontroller_get_widget(handle);
    }

    public static function reset(int handle) -> void
    {
        gtkeventcontroller_reset(handle);
    }

    public static function setName(int handle, var name) -> void
    {
        gtkeventcontroller_set_name(handle, name);
    }

    public static function setPropagationLimit(int handle, int limit) -> void
    {
        gtkeventcontroller_set_propagation_limit(handle, limit);
    }

    public static function setPropagationPhase(int handle, int phase) -> void
    {
        gtkeventcontroller_set_propagation_phase(handle, phase);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_event_controller_get_current_event(GtkEventController* controller) — GdkEvent* is a non-GObject fundamental type
    // @reserved gtk_event_controller_set_static_name(GtkEventController* controller, const char* name) — needs a string outliving the controller; setName covers it

}
