<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class GapplicationGetDefaultOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'gapplication_get_default' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/gio-gapplication');


        return new CompiledExpression(
            'int',
            'phpgtk_gapplication_get_default(' . ')',
            $expression
        );
    }
}
