<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class GdkglcontextClearCurrentOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'gdkglcontext_clear_current' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/gdk-gl-context');


        $context->codePrinter->output('phpgtk_gdkglcontext_clear_current(' . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
