// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkStackPage;

class GtkStackPage
{
    public static function getChild(int handle) -> int
    {
        return gtkstackpage_get_child(handle);
    }

    public static function getIconName(int handle) -> var
    {
        var result;

        let result = gtkstackpage_get_icon_name(handle);

        return result;
    }

    public static function getName(int handle) -> var
    {
        var result;

        let result = gtkstackpage_get_name(handle);

        return result;
    }

    public static function getNeedsAttention(int handle) -> bool
    {
        int r;

        let r = gtkstackpage_get_needs_attention(handle);

        return r == 1;
    }

    public static function getTitle(int handle) -> var
    {
        var result;

        let result = gtkstackpage_get_title(handle);

        return result;
    }

    public static function getUseUnderline(int handle) -> bool
    {
        int r;

        let r = gtkstackpage_get_use_underline(handle);

        return r == 1;
    }

    public static function getVisible(int handle) -> bool
    {
        int r;

        let r = gtkstackpage_get_visible(handle);

        return r == 1;
    }

    public static function setIconName(int handle, string setting) -> void
    {
        gtkstackpage_set_icon_name(handle, setting);
    }

    public static function setName(int handle, string setting) -> void
    {
        gtkstackpage_set_name(handle, setting);
    }

    public static function setNeedsAttention(int handle, bool setting) -> void
    {
        gtkstackpage_set_needs_attention(handle, setting);
    }

    public static function setTitle(int handle, string setting) -> void
    {
        gtkstackpage_set_title(handle, setting);
    }

    public static function setUseUnderline(int handle, bool setting) -> void
    {
        gtkstackpage_set_use_underline(handle, setting);
    }

    public static function setVisible(int handle, bool visible) -> void
    {
        gtkstackpage_set_visible(handle, visible);
    }
}
