// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GMenuItem;

class GMenuItem
{
    public static function new_(var label, var detailedAction) -> int
    {
        return gmenuitem_new(label, detailedAction);
    }

    public static function newFromModel(int model, int itemIndex) -> int
    {
        return gmenuitem_new_from_model(model, itemIndex);
    }

    public static function newSection(var label, int section) -> int
    {
        return gmenuitem_new_section(label, section);
    }

    public static function newSubmenu(var label, int submenu) -> int
    {
        return gmenuitem_new_submenu(label, submenu);
    }

    public static function getLink(int handle, string link) -> int
    {
        return gmenuitem_get_link(handle, link);
    }

    public static function setDetailedAction(int handle, string detailedAction) -> void
    {
        gmenuitem_set_detailed_action(handle, detailedAction);
    }

    public static function setIcon(int handle, int icon) -> void
    {
        gmenuitem_set_icon(handle, icon);
    }

    public static function setLabel(int handle, var label) -> void
    {
        gmenuitem_set_label(handle, label);
    }

    public static function setLink(int handle, string link, int model) -> void
    {
        gmenuitem_set_link(handle, link, model);
    }

    public static function setSection(int handle, int section) -> void
    {
        gmenuitem_set_section(handle, section);
    }

    public static function setSubmenu(int handle, int submenu) -> void
    {
        gmenuitem_set_submenu(handle, submenu);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved g_menu_item_get_attribute(self, attribute, format_string, ...) — varargs
    // @reserved g_menu_item_get_attribute_value(self, attribute, GVariantType* expected_type) — GVariant*
    // @reserved g_menu_item_set_action_and_target(self, action, format_string, ...) — varargs
    // @reserved g_menu_item_set_action_and_target_value(self, action, GVariant* target_value) — GVariant*
    // @reserved g_menu_item_set_attribute(self, attribute, format_string, ...) — varargs
    // @reserved g_menu_item_set_attribute_value(self, attribute, GVariant* value) — GVariant*

}
