// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkViewport;

class GtkViewport
{
    public static function new_(int hadjustment, int vadjustment) -> int
    {
        return gtkviewport_new(hadjustment, vadjustment);
    }

    public static function getChild(int handle) -> int
    {
        return gtkviewport_get_child(handle);
    }

    public static function getScrollToFocus(int handle) -> bool
    {
        int r;

        let r = gtkviewport_get_scroll_to_focus(handle);

        return r == 1;
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkviewport_set_child(handle, child);
    }

    public static function setScrollToFocus(int handle, bool scrollToFocus) -> void
    {
        gtkviewport_set_scroll_to_focus(handle, scrollToFocus);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_viewport_scroll_to(GtkViewport* self, GtkWidget* descendant, GtkScrollInfo* scroll) — GtkScrollInfo* boxed

}
