// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkWindowControls;

class GtkWindowControls
{
    public static function new_(int side) -> int
    {
        return gtkwindowcontrols_new(side);
    }

    public static function getDecorationLayout(int handle) -> var
    {
        var result;

        let result = gtkwindowcontrols_get_decoration_layout(handle);

        return result;
    }

    public static function getEmpty(int handle) -> bool
    {
        int r;

        let r = gtkwindowcontrols_get_empty(handle);

        return r == 1;
    }

    public static function getSide(int handle) -> int
    {
        return gtkwindowcontrols_get_side(handle);
    }

    public static function getUseNativeControls(int handle) -> bool
    {
        int r;

        let r = gtkwindowcontrols_get_use_native_controls(handle);

        return r == 1;
    }

    public static function setDecorationLayout(int handle, var layout) -> void
    {
        gtkwindowcontrols_set_decoration_layout(handle, layout);
    }

    public static function setSide(int handle, int side) -> void
    {
        gtkwindowcontrols_set_side(handle, side);
    }

    public static function setUseNativeControls(int handle, bool setting) -> void
    {
        gtkwindowcontrols_set_use_native_controls(handle, setting);
    }
}
