// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkAboutDialog;

class GtkAboutDialog
{
    public static function new_() -> int
    {
        return gtkaboutdialog_new();
    }

    public static function addCreditSection(int handle, string sectionName, array people) -> void
    {
        gtkaboutdialog_add_credit_section(handle, sectionName, people);
    }

    public static function getArtists(int handle) -> array
    {
        var result;

        let result = gtkaboutdialog_get_artists(handle);

        return result;
    }

    public static function getAuthors(int handle) -> array
    {
        var result;

        let result = gtkaboutdialog_get_authors(handle);

        return result;
    }

    public static function getComments(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_comments(handle);

        return result;
    }

    public static function getCopyright(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_copyright(handle);

        return result;
    }

    public static function getDocumenters(int handle) -> array
    {
        var result;

        let result = gtkaboutdialog_get_documenters(handle);

        return result;
    }

    public static function getLicense(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_license(handle);

        return result;
    }

    public static function getLicenseType(int handle) -> int
    {
        return gtkaboutdialog_get_license_type(handle);
    }

    public static function getLogo(int handle) -> int
    {
        return gtkaboutdialog_get_logo(handle);
    }

    public static function getLogoIconName(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_logo_icon_name(handle);

        return result;
    }

    public static function getProgramName(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_program_name(handle);

        return result;
    }

    public static function getSystemInformation(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_system_information(handle);

        return result;
    }

    public static function getTranslatorCredits(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_translator_credits(handle);

        return result;
    }

    public static function getVersion(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_version(handle);

        return result;
    }

    public static function getWebsite(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_website(handle);

        return result;
    }

    public static function getWebsiteLabel(int handle) -> var
    {
        var result;

        let result = gtkaboutdialog_get_website_label(handle);

        return result;
    }

    public static function getWrapLicense(int handle) -> bool
    {
        int r;

        let r = gtkaboutdialog_get_wrap_license(handle);

        return r == 1;
    }

    public static function setArtists(int handle, array artists) -> void
    {
        gtkaboutdialog_set_artists(handle, artists);
    }

    public static function setAuthors(int handle, array authors) -> void
    {
        gtkaboutdialog_set_authors(handle, authors);
    }

    public static function setComments(int handle, var comments) -> void
    {
        gtkaboutdialog_set_comments(handle, comments);
    }

    public static function setCopyright(int handle, var copyright) -> void
    {
        gtkaboutdialog_set_copyright(handle, copyright);
    }

    public static function setDocumenters(int handle, array documenters) -> void
    {
        gtkaboutdialog_set_documenters(handle, documenters);
    }

    public static function setLicense(int handle, var license) -> void
    {
        gtkaboutdialog_set_license(handle, license);
    }

    public static function setLicenseType(int handle, int licenseType) -> void
    {
        gtkaboutdialog_set_license_type(handle, licenseType);
    }

    public static function setLogo(int handle, int logo) -> void
    {
        gtkaboutdialog_set_logo(handle, logo);
    }

    public static function setLogoIconName(int handle, var iconName) -> void
    {
        gtkaboutdialog_set_logo_icon_name(handle, iconName);
    }

    public static function setProgramName(int handle, var name) -> void
    {
        gtkaboutdialog_set_program_name(handle, name);
    }

    public static function setSystemInformation(int handle, var systemInformation) -> void
    {
        gtkaboutdialog_set_system_information(handle, systemInformation);
    }

    public static function setTranslatorCredits(int handle, var translatorCredits) -> void
    {
        gtkaboutdialog_set_translator_credits(handle, translatorCredits);
    }

    public static function setVersion(int handle, var version) -> void
    {
        gtkaboutdialog_set_version(handle, version);
    }

    public static function setWebsite(int handle, var website) -> void
    {
        gtkaboutdialog_set_website(handle, website);
    }

    public static function setWebsiteLabel(int handle, string websiteLabel) -> void
    {
        gtkaboutdialog_set_website_label(handle, websiteLabel);
    }

    public static function setWrapLicense(int handle, bool wrapLicense) -> void
    {
        gtkaboutdialog_set_wrap_license(handle, wrapLicense);
    }
}
