// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkSpinner;

class GtkSpinner
{
    public static function new_() -> int
    {
        return gtkspinner_new();
    }

    public static function getSpinning(int handle) -> bool
    {
        int r;

        let r = gtkspinner_get_spinning(handle);

        return r == 1;
    }

    public static function setSpinning(int handle, bool spinning) -> void
    {
        gtkspinner_set_spinning(handle, spinning);
    }

    public static function start(int handle) -> void
    {
        gtkspinner_start(handle);
    }

    public static function stop(int handle) -> void
    {
        gtkspinner_stop(handle);
    }
}
