// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkEventControllerScroll;

class GtkEventControllerScroll
{
    public static function new_(int flags) -> int
    {
        return gtkeventcontrollerscroll_new(flags);
    }

    public static function getFlags(int handle) -> int
    {
        return gtkeventcontrollerscroll_get_flags(handle);
    }

    public static function getUnit(int handle) -> int
    {
        return gtkeventcontrollerscroll_get_unit(handle);
    }

    public static function setFlags(int handle, int flags) -> void
    {
        gtkeventcontrollerscroll_set_flags(handle, flags);
    }
}
