// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gdk\GdkGLContext;

class GdkGLContext
{
    public static function getAllowedApis(int handle) -> int
    {
        return gdkglcontext_get_allowed_apis(handle);
    }

    public static function getApi(int handle) -> int
    {
        return gdkglcontext_get_api(handle);
    }

    public static function getDebugEnabled(int handle) -> bool
    {
        int r;

        let r = gdkglcontext_get_debug_enabled(handle);

        return r == 1;
    }

    public static function getDisplay(int handle) -> int
    {
        return gdkglcontext_get_display(handle);
    }

    public static function getForwardCompatible(int handle) -> bool
    {
        int r;

        let r = gdkglcontext_get_forward_compatible(handle);

        return r == 1;
    }

    public static function getRequiredVersion(int handle) -> array
    {
        var result;

        let result = gdkglcontext_get_required_version(handle);

        return result;
    }

    public static function getSurface(int handle) -> int
    {
        return gdkglcontext_get_surface(handle);
    }

    public static function getUseEs(int handle) -> bool
    {
        int r;

        let r = gdkglcontext_get_use_es(handle);

        return r == 1;
    }

    public static function getVersion(int handle) -> array
    {
        var result;

        let result = gdkglcontext_get_version(handle);

        return result;
    }

    public static function isLegacy(int handle) -> bool
    {
        int r;

        let r = gdkglcontext_is_legacy(handle);

        return r == 1;
    }

    public static function isShared(int handle, int other) -> bool
    {
        int r;

        let r = gdkglcontext_is_shared(handle, other);

        return r == 1;
    }

    public static function makeCurrent(int handle) -> void
    {
        gdkglcontext_make_current(handle);
    }

    public static function setAllowedApis(int handle, int apis) -> void
    {
        gdkglcontext_set_allowed_apis(handle, apis);
    }

    public static function setDebugEnabled(int handle, bool enabled) -> void
    {
        gdkglcontext_set_debug_enabled(handle, enabled);
    }

    public static function setForwardCompatible(int handle, bool compatible) -> void
    {
        gdkglcontext_set_forward_compatible(handle, compatible);
    }

    public static function setRequiredVersion(int handle, int major, int minor) -> void
    {
        gdkglcontext_set_required_version(handle, major, minor);
    }

    public static function setUseEs(int handle, int useEs) -> void
    {
        gdkglcontext_set_use_es(handle, useEs);
    }

    public static function clearCurrent() -> void
    {
        gdkglcontext_clear_current();
    }

    public static function getCurrent() -> int
    {
        return gdkglcontext_get_current();
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gdk_gl_context_get_shared_context(GdkGLContext* self) — deprecated 4.4, always NULL
    // @reserved gdk_gl_context_realize(GdkGLContext* self, GError** error) — GError** out-parameter

}
