// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkColumnViewColumn;

class GtkColumnViewColumn
{
    public static function new_(var title, int factory) -> int
    {
        return gtkcolumnviewcolumn_new(title, factory);
    }

    public static function getColumnView(int handle) -> int
    {
        return gtkcolumnviewcolumn_get_column_view(handle);
    }

    public static function getExpand(int handle) -> bool
    {
        int r;

        let r = gtkcolumnviewcolumn_get_expand(handle);

        return r == 1;
    }

    public static function getFactory(int handle) -> int
    {
        return gtkcolumnviewcolumn_get_factory(handle);
    }

    public static function getFixedWidth(int handle) -> int
    {
        return gtkcolumnviewcolumn_get_fixed_width(handle);
    }

    public static function getHeaderMenu(int handle) -> int
    {
        return gtkcolumnviewcolumn_get_header_menu(handle);
    }

    public static function getId(int handle) -> var
    {
        var result;

        let result = gtkcolumnviewcolumn_get_id(handle);

        return result;
    }

    public static function getResizable(int handle) -> bool
    {
        int r;

        let r = gtkcolumnviewcolumn_get_resizable(handle);

        return r == 1;
    }

    public static function getTitle(int handle) -> var
    {
        var result;

        let result = gtkcolumnviewcolumn_get_title(handle);

        return result;
    }

    public static function getVisible(int handle) -> bool
    {
        int r;

        let r = gtkcolumnviewcolumn_get_visible(handle);

        return r == 1;
    }

    public static function setExpand(int handle, bool expand) -> void
    {
        gtkcolumnviewcolumn_set_expand(handle, expand);
    }

    public static function setFactory(int handle, int factory) -> void
    {
        gtkcolumnviewcolumn_set_factory(handle, factory);
    }

    public static function setFixedWidth(int handle, int fixedWidth) -> void
    {
        gtkcolumnviewcolumn_set_fixed_width(handle, fixedWidth);
    }

    public static function setHeaderMenu(int handle, int menu) -> void
    {
        gtkcolumnviewcolumn_set_header_menu(handle, menu);
    }

    public static function setId(int handle, var id) -> void
    {
        gtkcolumnviewcolumn_set_id(handle, id);
    }

    public static function setResizable(int handle, bool resizable) -> void
    {
        gtkcolumnviewcolumn_set_resizable(handle, resizable);
    }

    public static function setTitle(int handle, var title) -> void
    {
        gtkcolumnviewcolumn_set_title(handle, title);
    }

    public static function setVisible(int handle, bool visible) -> void
    {
        gtkcolumnviewcolumn_set_visible(handle, visible);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_column_view_column_get_sorter() — GtkSorter*
    // @reserved gtk_column_view_column_set_sorter(GtkSorter* sorter) — GtkSorter*

}
