// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkApplication;

class GtkApplication
{
    public static function new_(var applicationId, int flags) -> int
    {
        return gtkapplication_new(applicationId, flags);
    }

    public static function addWindow(int handle, int window) -> void
    {
        gtkapplication_add_window(handle, window);
    }

    public static function getAccelsForAction(int handle, string detailedActionName) -> array
    {
        var result;

        let result = gtkapplication_get_accels_for_action(handle, detailedActionName);

        return result;
    }

    public static function getActionsForAccel(int handle, string accel) -> array
    {
        var result;

        let result = gtkapplication_get_actions_for_accel(handle, accel);

        return result;
    }

    public static function getActiveWindow(int handle) -> int
    {
        return gtkapplication_get_active_window(handle);
    }

    public static function getMenuById(int handle, string id) -> int
    {
        return gtkapplication_get_menu_by_id(handle, id);
    }

    public static function getMenubar(int handle) -> int
    {
        return gtkapplication_get_menubar(handle);
    }

    public static function getWindowById(int handle, int id) -> int
    {
        return gtkapplication_get_window_by_id(handle, id);
    }

    public static function getWindows(int handle) -> array
    {
        var result;

        let result = gtkapplication_get_windows(handle);

        return result;
    }

    public static function inhibit(int handle, int window, int flags, var reason) -> int
    {
        return gtkapplication_inhibit(handle, window, flags, reason);
    }

    public static function listActionDescriptions(int handle) -> array
    {
        var result;

        let result = gtkapplication_list_action_descriptions(handle);

        return result;
    }

    public static function removeWindow(int handle, int window) -> void
    {
        gtkapplication_remove_window(handle, window);
    }

    public static function setAccelsForAction(int handle, string detailedActionName, array accels) -> void
    {
        gtkapplication_set_accels_for_action(handle, detailedActionName, accels);
    }

    public static function setMenubar(int handle, int menubar) -> void
    {
        gtkapplication_set_menubar(handle, menubar);
    }

    public static function uninhibit(int handle, int cookie) -> void
    {
        gtkapplication_uninhibit(handle, cookie);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "register-session" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "screensaver-active" — no C accessor; use Bridge::getProperty

}
