// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkHeaderBar;

class GtkHeaderBar
{
    public static function new_() -> int
    {
        return gtkheaderbar_new();
    }

    public static function getDecorationLayout(int handle) -> var
    {
        var result;

        let result = gtkheaderbar_get_decoration_layout(handle);

        return result;
    }

    public static function getShowTitleButtons(int handle) -> bool
    {
        int r;

        let r = gtkheaderbar_get_show_title_buttons(handle);

        return r == 1;
    }

    public static function getTitleWidget(int handle) -> int
    {
        return gtkheaderbar_get_title_widget(handle);
    }

    public static function getUseNativeControls(int handle) -> bool
    {
        int r;

        let r = gtkheaderbar_get_use_native_controls(handle);

        return r == 1;
    }

    public static function packEnd(int handle, int child) -> void
    {
        gtkheaderbar_pack_end(handle, child);
    }

    public static function packStart(int handle, int child) -> void
    {
        gtkheaderbar_pack_start(handle, child);
    }

    public static function remove(int handle, int child) -> void
    {
        gtkheaderbar_remove(handle, child);
    }

    public static function setDecorationLayout(int handle, var layout) -> void
    {
        gtkheaderbar_set_decoration_layout(handle, layout);
    }

    public static function setShowTitleButtons(int handle, bool setting) -> void
    {
        gtkheaderbar_set_show_title_buttons(handle, setting);
    }

    public static function setTitleWidget(int handle, int titleWidget) -> void
    {
        gtkheaderbar_set_title_widget(handle, titleWidget);
    }

    public static function setUseNativeControls(int handle, bool setting) -> void
    {
        gtkheaderbar_set_use_native_controls(handle, setting);
    }
}
