// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkDropDown;

class GtkDropDown
{
    public static function new_(int model) -> int
    {
        return gtkdropdown_new(model);
    }

    public static function newFromStrings(array strings) -> int
    {
        return gtkdropdown_new_from_strings(strings);
    }

    public static function getEnableSearch(int handle) -> bool
    {
        int r;

        let r = gtkdropdown_get_enable_search(handle);

        return r == 1;
    }

    public static function getFactory(int handle) -> int
    {
        return gtkdropdown_get_factory(handle);
    }

    public static function getHeaderFactory(int handle) -> int
    {
        return gtkdropdown_get_header_factory(handle);
    }

    public static function getListFactory(int handle) -> int
    {
        return gtkdropdown_get_list_factory(handle);
    }

    public static function getModel(int handle) -> int
    {
        return gtkdropdown_get_model(handle);
    }

    public static function getSearchMatchMode(int handle) -> int
    {
        return gtkdropdown_get_search_match_mode(handle);
    }

    public static function getSelected(int handle) -> int
    {
        return gtkdropdown_get_selected(handle);
    }

    public static function getSelectedItem(int handle) -> int
    {
        return gtkdropdown_get_selected_item(handle);
    }

    public static function getShowArrow(int handle) -> bool
    {
        int r;

        let r = gtkdropdown_get_show_arrow(handle);

        return r == 1;
    }

    public static function setEnableSearch(int handle, bool enableSearch) -> void
    {
        gtkdropdown_set_enable_search(handle, enableSearch);
    }

    public static function setFactory(int handle, int factory) -> void
    {
        gtkdropdown_set_factory(handle, factory);
    }

    public static function setHeaderFactory(int handle, int factory) -> void
    {
        gtkdropdown_set_header_factory(handle, factory);
    }

    public static function setListFactory(int handle, int factory) -> void
    {
        gtkdropdown_set_list_factory(handle, factory);
    }

    public static function setModel(int handle, int model) -> void
    {
        gtkdropdown_set_model(handle, model);
    }

    public static function setSearchMatchMode(int handle, int searchMatchMode) -> void
    {
        gtkdropdown_set_search_match_mode(handle, searchMatchMode);
    }

    public static function setSelected(int handle, int position) -> void
    {
        gtkdropdown_set_selected(handle, position);
    }

    public static function setShowArrow(int handle, bool showArrow) -> void
    {
        gtkdropdown_set_show_arrow(handle, showArrow);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_drop_down_get_expression() — GtkExpression*
    // @reserved gtk_drop_down_set_expression(GtkExpression* expression) — GtkExpression*

}
