// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkScrollbar;

class GtkScrollbar
{
    public static function new_(int orientation, int adjustment) -> int
    {
        return gtkscrollbar_new(orientation, adjustment);
    }

    public static function getAdjustment(int handle) -> int
    {
        return gtkscrollbar_get_adjustment(handle);
    }

    public static function setAdjustment(int handle, int adjustment) -> void
    {
        gtkscrollbar_set_adjustment(handle, adjustment);
    }
}
