// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkTextTag;

class GtkTextTag
{
    public static function new_(var name) -> int
    {
        return gtktexttag_new(name);
    }

    public static function changed(int handle, bool sizeChanged) -> void
    {
        gtktexttag_changed(handle, sizeChanged);
    }

    public static function getPriority(int handle) -> int
    {
        return gtktexttag_get_priority(handle);
    }

    public static function setPriority(int handle, int priority) -> void
    {
        gtktexttag_set_priority(handle, priority);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "accumulative-margin" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "allow-breaks" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "allow-breaks-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "background" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "background-full-height" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "background-full-height-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "background-rgba" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "background-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "direction" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "editable" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "editable-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "fallback" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "fallback-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "family" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "family-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "font" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "font-desc" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "font-features" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "font-features-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "foreground" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "foreground-rgba" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "foreground-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "indent" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "indent-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "insert-hyphens" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "insert-hyphens-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "invisible" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "invisible-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "justification" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "justification-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "language" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "language-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "left-margin" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "left-margin-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "letter-spacing" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "letter-spacing-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "line-height" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "line-height-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "name" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "overline" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "overline-rgba" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "overline-rgba-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "overline-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "paragraph-background" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "paragraph-background-rgba" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "paragraph-background-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "pixels-above-lines" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "pixels-above-lines-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "pixels-below-lines" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "pixels-below-lines-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "pixels-inside-wrap" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "pixels-inside-wrap-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "right-margin" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "right-margin-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "rise" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "rise-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "scale" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "scale-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "sentence" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "sentence-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "show-spaces" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "show-spaces-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "size" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "size-points" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "size-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "stretch" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "stretch-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "strikethrough" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "strikethrough-rgba" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "strikethrough-rgba-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "strikethrough-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "style" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "style-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "tabs" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "tabs-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "text-transform" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "text-transform-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "underline" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "underline-rgba" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "underline-rgba-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "underline-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "variant" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "variant-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "weight" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "weight-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "word" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "word-set" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "wrap-mode" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "wrap-mode-set" — no dedicated C accessor; use Bridge::getProperty/setProperty

}
