// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkTextMark;

class GtkTextMark
{
    public static function new_(var name, bool leftGravity) -> int
    {
        return gtktextmark_new(name, leftGravity);
    }

    public static function getBuffer(int handle) -> int
    {
        return gtktextmark_get_buffer(handle);
    }

    public static function getDeleted(int handle) -> bool
    {
        int r;

        let r = gtktextmark_get_deleted(handle);

        return r == 1;
    }

    public static function getLeftGravity(int handle) -> bool
    {
        int r;

        let r = gtktextmark_get_left_gravity(handle);

        return r == 1;
    }

    public static function getName(int handle) -> var
    {
        var result;

        let result = gtktextmark_get_name(handle);

        return result;
    }

    public static function getVisible(int handle) -> bool
    {
        int r;

        let r = gtktextmark_get_visible(handle);

        return r == 1;
    }

    public static function setVisible(int handle, bool setting) -> void
    {
        gtktextmark_set_visible(handle, setting);
    }
}
