// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkMediaFile;

class GtkMediaFile
{
    public static function new_() -> int
    {
        return gtkmediafile_new();
    }

    public static function newForFile(int file) -> int
    {
        return gtkmediafile_new_for_file(file);
    }

    public static function newForFilename(var filename) -> int
    {
        return gtkmediafile_new_for_filename(filename);
    }

    public static function newForInputStream(int stream) -> int
    {
        return gtkmediafile_new_for_input_stream(stream);
    }

    public static function newForResource(var resourcePath) -> int
    {
        return gtkmediafile_new_for_resource(resourcePath);
    }

    public static function clear(int handle) -> void
    {
        gtkmediafile_clear(handle);
    }

    public static function getFile(int handle) -> int
    {
        return gtkmediafile_get_file(handle);
    }

    public static function getInputStream(int handle) -> int
    {
        return gtkmediafile_get_input_stream(handle);
    }

    public static function setFile(int handle, int file) -> void
    {
        gtkmediafile_set_file(handle, file);
    }

    public static function setFilename(int handle, var filename) -> void
    {
        gtkmediafile_set_filename(handle, filename);
    }

    public static function setInputStream(int handle, int stream) -> void
    {
        gtkmediafile_set_input_stream(handle, stream);
    }

    public static function setResource(int handle, var resourcePath) -> void
    {
        gtkmediafile_set_resource(handle, resourcePath);
    }
}
