
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "gtk/gtk/alertdialog/gtkalertdialog.zep.h"
#include "gtk/gtk/application/gtkapplication.zep.h"
#include "gtk/gtk/box/gtkbox.zep.h"
#include "gtk/gtk/button/gtkbutton.zep.h"
#include "gtk/gtk/centerbox/gtkcenterbox.zep.h"
#include "gtk/gtk/checkbutton/gtkcheckbutton.zep.h"
#include "gtk/gtk/colordialog/gtkcolordialog.zep.h"
#include "gtk/gtk/dropdown/gtkdropdown.zep.h"
#include "gtk/gtk/entry/gtkentry.zep.h"
#include "gtk/gtk/filedialog/gtkfiledialog.zep.h"
#include "gtk/gtk/fontdialog/gtkfontdialog.zep.h"
#include "gtk/gtk/glarea/gtkglarea.zep.h"
#include "gtk/gtk/gpupane/gtkgpupane.zep.h"
#include "gtk/gtk/grid/gtkgrid.zep.h"
#include "gtk/gtk/gtk.zep.h"
#include "gtk/gtk/gtkerror.zep.h"
#include "gtk/gtk/gtkglib.zep.h"
#include "gtk/gtk/gtkswitch/gtkswitch.zep.h"
#include "gtk/gtk/headerbar/gtkheaderbar.zep.h"
#include "gtk/gtk/image/gtkimage.zep.h"
#include "gtk/gtk/label/gtklabel.zep.h"
#include "gtk/gtk/listbox/gtklistbox.zep.h"
#include "gtk/gtk/listitem/gtklistitem.zep.h"
#include "gtk/gtk/listview/gtklistview.zep.h"
#include "gtk/gtk/menubutton/gtkmenubutton.zep.h"
#include "gtk/gtk/notebook/gtknotebook.zep.h"
#include "gtk/gtk/overlay/gtkoverlay.zep.h"
#include "gtk/gtk/paned/gtkpaned.zep.h"
#include "gtk/gtk/passwordentry/gtkpasswordentry.zep.h"
#include "gtk/gtk/picture/gtkpicture.zep.h"
#include "gtk/gtk/popover/gtkpopover.zep.h"
#include "gtk/gtk/progressbar/gtkprogressbar.zep.h"
#include "gtk/gtk/scale/gtkscale.zep.h"
#include "gtk/gtk/scrolledwindow/gtkscrolledwindow.zep.h"
#include "gtk/gtk/searchentry/gtksearchentry.zep.h"
#include "gtk/gtk/separator/gtkseparator.zep.h"
#include "gtk/gtk/singleselection/gtksingleselection.zep.h"
#include "gtk/gtk/spinbutton/gtkspinbutton.zep.h"
#include "gtk/gtk/spinner/gtkspinner.zep.h"
#include "gtk/gtk/stack/gtkstack.zep.h"
#include "gtk/gtk/stringlist/gtkstringlist.zep.h"
#include "gtk/gtk/textview/gtktextview.zep.h"
#include "gtk/gtk/togglebutton/gtktogglebutton.zep.h"
#include "gtk/gtk/widget/gtkwidget.zep.h"
#include "gtk/gtk/window/gtkwindow.zep.h"

#endif