// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkGLArea;

class GtkGLArea
{
    public static function new_() -> int
    {
        return gtkglarea_new();
    }

    public static function attachBuffers(int handle) -> void
    {
        gtkglarea_attach_buffers(handle);
    }

    public static function getAllowedApis(int handle) -> int
    {
        return gtkglarea_get_allowed_apis(handle);
    }

    public static function getApi(int handle) -> int
    {
        return gtkglarea_get_api(handle);
    }

    public static function getAutoRender(int handle) -> bool
    {
        int r;

        let r = gtkglarea_get_auto_render(handle);

        return r == 1;
    }

    public static function getContext(int handle) -> int
    {
        return gtkglarea_get_context(handle);
    }

    public static function getHasDepthBuffer(int handle) -> bool
    {
        int r;

        let r = gtkglarea_get_has_depth_buffer(handle);

        return r == 1;
    }

    public static function getHasStencilBuffer(int handle) -> bool
    {
        int r;

        let r = gtkglarea_get_has_stencil_buffer(handle);

        return r == 1;
    }

    public static function getRequiredVersion(int handle) -> array
    {
        var result;

        let result = gtkglarea_get_required_version(handle);

        return result;
    }

    public static function makeCurrent(int handle) -> void
    {
        gtkglarea_make_current(handle);
    }

    public static function queueRender(int handle) -> void
    {
        gtkglarea_queue_render(handle);
    }

    public static function setAllowedApis(int handle, int apis) -> void
    {
        gtkglarea_set_allowed_apis(handle, apis);
    }

    public static function setAutoRender(int handle, bool autoRender) -> void
    {
        gtkglarea_set_auto_render(handle, autoRender);
    }

    public static function setHasDepthBuffer(int handle, bool hasDepthBuffer) -> void
    {
        gtkglarea_set_has_depth_buffer(handle, hasDepthBuffer);
    }

    public static function setHasStencilBuffer(int handle, bool hasStencilBuffer) -> void
    {
        gtkglarea_set_has_stencil_buffer(handle, hasStencilBuffer);
    }

    public static function setRequiredVersion(int handle, int major, int minor) -> void
    {
        gtkglarea_set_required_version(handle, major, minor);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_gl_area_get_error(GtkGLArea* self) — GError* return
    // @reserved gtk_gl_area_get_use_es(GtkGLArea* self) — deprecated 4.12, use getApi
    // @reserved gtk_gl_area_set_error(GtkGLArea* self, const GError* error) — GError* parameter
    // @reserved gtk_gl_area_set_use_es(GtkGLArea* self, gboolean use_es) — deprecated 4.12, use setAllowedApis

}
