// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GMenu;

class GMenu
{
    public static function new_() -> int
    {
        return gmenu_new();
    }

    public static function append(int handle, var label, var detailedAction) -> void
    {
        gmenu_append(handle, label, detailedAction);
    }

    public static function appendItem(int handle, int item) -> void
    {
        gmenu_append_item(handle, item);
    }

    public static function appendSection(int handle, var label, int section) -> void
    {
        gmenu_append_section(handle, label, section);
    }

    public static function appendSubmenu(int handle, var label, int submenu) -> void
    {
        gmenu_append_submenu(handle, label, submenu);
    }

    public static function freeze(int handle) -> void
    {
        gmenu_freeze(handle);
    }

    public static function insert(int handle, int position, var label, var detailedAction) -> void
    {
        gmenu_insert(handle, position, label, detailedAction);
    }

    public static function insertItem(int handle, int position, int item) -> void
    {
        gmenu_insert_item(handle, position, item);
    }

    public static function insertSection(int handle, int position, var label, int section) -> void
    {
        gmenu_insert_section(handle, position, label, section);
    }

    public static function insertSubmenu(int handle, int position, var label, int submenu) -> void
    {
        gmenu_insert_submenu(handle, position, label, submenu);
    }

    public static function prepend(int handle, var label, var detailedAction) -> void
    {
        gmenu_prepend(handle, label, detailedAction);
    }

    public static function prependItem(int handle, int item) -> void
    {
        gmenu_prepend_item(handle, item);
    }

    public static function prependSection(int handle, var label, int section) -> void
    {
        gmenu_prepend_section(handle, label, section);
    }

    public static function prependSubmenu(int handle, var label, int submenu) -> void
    {
        gmenu_prepend_submenu(handle, label, submenu);
    }

    public static function remove(int handle, int position) -> void
    {
        gmenu_remove(handle, position);
    }

    public static function removeAll(int handle) -> void
    {
        gmenu_remove_all(handle);
    }
}
