// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkNotebookPage;

class GtkNotebookPage
{
    public static function getChild(int handle) -> int
    {
        return gtknotebookpage_get_child(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "detachable" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "menu" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "menu-label" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "position" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "reorderable" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "tab" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "tab-expand" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "tab-fill" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "tab-label" — no dedicated C accessor; use Bridge::getProperty/setProperty

}
