
extern zend_class_entry *gtk_gio_gsimpleactiongroup_gsimpleactiongroup_ce;

ZEPHIR_INIT_CLASS(Gtk_Gio_GSimpleActionGroup_GSimpleActionGroup);

PHP_METHOD(Gtk_Gio_GSimpleActionGroup_GSimpleActionGroup, new_);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gio_gsimpleactiongroup_gsimpleactiongroup_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(gtk_gio_gsimpleactiongroup_gsimpleactiongroup_method_entry) {
	PHP_ME(Gtk_Gio_GSimpleActionGroup_GSimpleActionGroup, new_, arginfo_gtk_gio_gsimpleactiongroup_gsimpleactiongroup_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
