// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkProgressBar;

class GtkProgressBar
{
    public static function new_() -> int
    {
        return gtkprogressbar_new();
    }

    public static function getEllipsize(int handle) -> int
    {
        return gtkprogressbar_get_ellipsize(handle);
    }

    public static function getFraction(int handle) -> double
    {
        return gtkprogressbar_get_fraction(handle);
    }

    public static function getInverted(int handle) -> bool
    {
        int r;

        let r = gtkprogressbar_get_inverted(handle);

        return r == 1;
    }

    public static function getPulseStep(int handle) -> double
    {
        return gtkprogressbar_get_pulse_step(handle);
    }

    public static function getShowText(int handle) -> bool
    {
        int r;

        let r = gtkprogressbar_get_show_text(handle);

        return r == 1;
    }

    public static function getText(int handle) -> var
    {
        var result;

        let result = gtkprogressbar_get_text(handle);

        return result;
    }

    public static function pulse(int handle) -> void
    {
        gtkprogressbar_pulse(handle);
    }

    public static function setEllipsize(int handle, int mode) -> void
    {
        gtkprogressbar_set_ellipsize(handle, mode);
    }

    public static function setFraction(int handle, double fraction) -> void
    {
        gtkprogressbar_set_fraction(handle, fraction);
    }

    public static function setInverted(int handle, bool inverted) -> void
    {
        gtkprogressbar_set_inverted(handle, inverted);
    }

    public static function setPulseStep(int handle, double fraction) -> void
    {
        gtkprogressbar_set_pulse_step(handle, fraction);
    }

    public static function setShowText(int handle, bool showText) -> void
    {
        gtkprogressbar_set_show_text(handle, showText);
    }

    public static function setText(int handle, var text) -> void
    {
        gtkprogressbar_set_text(handle, text);
    }
}
