// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkScale;

class GtkScale
{
    public static function new_(int orientation, int adjustment) -> int
    {
        return gtkscale_new(orientation, adjustment);
    }

    public static function newWithRange(int orientation, double min, double max, double step) -> int
    {
        return gtkscale_new_with_range(orientation, min, max, step);
    }

    public static function addMark(int handle, double value, int position, var markup) -> void
    {
        gtkscale_add_mark(handle, value, position, markup);
    }

    public static function clearMarks(int handle) -> void
    {
        gtkscale_clear_marks(handle);
    }

    public static function getDigits(int handle) -> int
    {
        return gtkscale_get_digits(handle);
    }

    public static function getDrawValue(int handle) -> bool
    {
        int r;

        let r = gtkscale_get_draw_value(handle);

        return r == 1;
    }

    public static function getHasOrigin(int handle) -> bool
    {
        int r;

        let r = gtkscale_get_has_origin(handle);

        return r == 1;
    }

    public static function getLayout(int handle) -> int
    {
        return gtkscale_get_layout(handle);
    }

    public static function getLayoutOffsets(int handle) -> array
    {
        var result;

        let result = gtkscale_get_layout_offsets(handle);

        return result;
    }

    public static function getValuePos(int handle) -> int
    {
        return gtkscale_get_value_pos(handle);
    }

    public static function setDigits(int handle, int digits) -> void
    {
        gtkscale_set_digits(handle, digits);
    }

    public static function setDrawValue(int handle, bool drawValue) -> void
    {
        gtkscale_set_draw_value(handle, drawValue);
    }

    public static function setHasOrigin(int handle, bool hasOrigin) -> void
    {
        gtkscale_set_has_origin(handle, hasOrigin);
    }

    public static function setValuePos(int handle, int pos) -> void
    {
        gtkscale_set_value_pos(handle, pos);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_scale_set_format_value_func(GtkScale* scale, func, user_data, destroy_notify) — non-signal callback

}
