// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkApplicationWindow;

class GtkApplicationWindow
{
    public static function new_(int application) -> int
    {
        return gtkapplicationwindow_new(application);
    }

    public static function getId(int handle) -> int
    {
        return gtkapplicationwindow_get_id(handle);
    }

    public static function getShowMenubar(int handle) -> bool
    {
        int r;

        let r = gtkapplicationwindow_get_show_menubar(handle);

        return r == 1;
    }

    public static function setShowMenubar(int handle, bool showMenubar) -> void
    {
        gtkapplicationwindow_set_show_menubar(handle, showMenubar);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_application_window_get_help_overlay(void) — deprecated
    // @reserved gtk_application_window_set_help_overlay(GtkShortcutsWindow* help_overlay) — deprecated

}
