// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkSwitch;

class GtkSwitch
{
    public static function new_() -> int
    {
        return gtkswitch_new();
    }

    public static function getActive(int handle) -> bool
    {
        int r;

        let r = gtkswitch_get_active(handle);

        return r == 1;
    }

    public static function getState(int handle) -> bool
    {
        int r;

        let r = gtkswitch_get_state(handle);

        return r == 1;
    }

    public static function setActive(int handle, bool isActive) -> void
    {
        gtkswitch_set_active(handle, isActive);
    }

    public static function setState(int handle, bool state) -> void
    {
        gtkswitch_set_state(handle, state);
    }
}
