// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkScrollable;

class GtkScrollable
{
    public static function getBorder(int handle) -> array
    {
        var result;

        let result = gtkscrollable_get_border(handle);

        return result;
    }

    public static function getHadjustment(int handle) -> int
    {
        return gtkscrollable_get_hadjustment(handle);
    }

    public static function getHscrollPolicy(int handle) -> int
    {
        return gtkscrollable_get_hscroll_policy(handle);
    }

    public static function getVadjustment(int handle) -> int
    {
        return gtkscrollable_get_vadjustment(handle);
    }

    public static function getVscrollPolicy(int handle) -> int
    {
        return gtkscrollable_get_vscroll_policy(handle);
    }

    public static function setHadjustment(int handle, int hadjustment) -> void
    {
        gtkscrollable_set_hadjustment(handle, hadjustment);
    }

    public static function setHscrollPolicy(int handle, int policy) -> void
    {
        gtkscrollable_set_hscroll_policy(handle, policy);
    }

    public static function setVadjustment(int handle, int vadjustment) -> void
    {
        gtkscrollable_set_vadjustment(handle, vadjustment);
    }

    public static function setVscrollPolicy(int handle, int policy) -> void
    {
        gtkscrollable_set_vscroll_policy(handle, policy);
    }
}
