// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkPicture;

class GtkPicture
{
    public static function new_() -> int
    {
        return gtkpicture_new();
    }

    public static function newForFile(int file) -> int
    {
        return gtkpicture_new_for_file(file);
    }

    public static function newForFilename(var filename) -> int
    {
        return gtkpicture_new_for_filename(filename);
    }

    public static function newForPaintable(int paintable) -> int
    {
        return gtkpicture_new_for_paintable(paintable);
    }

    public static function newForResource(var resourcePath) -> int
    {
        return gtkpicture_new_for_resource(resourcePath);
    }

    public static function getAlternativeText(int handle) -> var
    {
        var result;

        let result = gtkpicture_get_alternative_text(handle);

        return result;
    }

    public static function getCanShrink(int handle) -> bool
    {
        int r;

        let r = gtkpicture_get_can_shrink(handle);

        return r == 1;
    }

    public static function getContentFit(int handle) -> int
    {
        return gtkpicture_get_content_fit(handle);
    }

    public static function getFile(int handle) -> int
    {
        return gtkpicture_get_file(handle);
    }

    public static function getPaintable(int handle) -> int
    {
        return gtkpicture_get_paintable(handle);
    }

    public static function setAlternativeText(int handle, var alternativeText) -> void
    {
        gtkpicture_set_alternative_text(handle, alternativeText);
    }

    public static function setCanShrink(int handle, bool canShrink) -> void
    {
        gtkpicture_set_can_shrink(handle, canShrink);
    }

    public static function setContentFit(int handle, int contentFit) -> void
    {
        gtkpicture_set_content_fit(handle, contentFit);
    }

    public static function setFile(int handle, int file) -> void
    {
        gtkpicture_set_file(handle, file);
    }

    public static function setFilename(int handle, var filename) -> void
    {
        gtkpicture_set_filename(handle, filename);
    }

    public static function setPaintable(int handle, int paintable) -> void
    {
        gtkpicture_set_paintable(handle, paintable);
    }

    public static function setResource(int handle, var resourcePath) -> void
    {
        gtkpicture_set_resource(handle, resourcePath);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_picture_new_for_pixbuf(GdkPixbuf* pixbuf) — deprecated
    // @reserved gtk_picture_get_keep_aspect_ratio(GtkPicture* self) — deprecated
    // @reserved gtk_picture_set_keep_aspect_ratio(GtkPicture* self, keep_aspect_ratio) — deprecated
    // @reserved gtk_picture_set_pixbuf(GtkPicture* self, GdkPixbuf* pixbuf) — deprecated

}
