// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkGrid;

class GtkGrid
{
    public static function new_() -> int
    {
        return gtkgrid_new();
    }

    public static function attach(int handle, int child, int column, int row, int width, int height) -> void
    {
        gtkgrid_attach(handle, child, column, row, width, height);
    }

    public static function attachNextTo(int handle, int child, int sibling, int side, int width, int height) -> void
    {
        gtkgrid_attach_next_to(handle, child, sibling, side, width, height);
    }

    public static function getBaselineRow(int handle) -> int
    {
        return gtkgrid_get_baseline_row(handle);
    }

    public static function getChildAt(int handle, int column, int row) -> int
    {
        return gtkgrid_get_child_at(handle, column, row);
    }

    public static function getColumnHomogeneous(int handle) -> bool
    {
        int r;

        let r = gtkgrid_get_column_homogeneous(handle);

        return r == 1;
    }

    public static function getColumnSpacing(int handle) -> int
    {
        return gtkgrid_get_column_spacing(handle);
    }

    public static function getRowBaselinePosition(int handle, int row) -> int
    {
        return gtkgrid_get_row_baseline_position(handle, row);
    }

    public static function getRowHomogeneous(int handle) -> bool
    {
        int r;

        let r = gtkgrid_get_row_homogeneous(handle);

        return r == 1;
    }

    public static function getRowSpacing(int handle) -> int
    {
        return gtkgrid_get_row_spacing(handle);
    }

    public static function insertColumn(int handle, int position) -> void
    {
        gtkgrid_insert_column(handle, position);
    }

    public static function insertNextTo(int handle, int sibling, int side) -> void
    {
        gtkgrid_insert_next_to(handle, sibling, side);
    }

    public static function insertRow(int handle, int position) -> void
    {
        gtkgrid_insert_row(handle, position);
    }

    public static function queryChild(int handle, int child) -> array
    {
        var result;

        let result = gtkgrid_query_child(handle, child);

        return result;
    }

    public static function remove(int handle, int child) -> void
    {
        gtkgrid_remove(handle, child);
    }

    public static function removeColumn(int handle, int position) -> void
    {
        gtkgrid_remove_column(handle, position);
    }

    public static function removeRow(int handle, int position) -> void
    {
        gtkgrid_remove_row(handle, position);
    }

    public static function setBaselineRow(int handle, int row) -> void
    {
        gtkgrid_set_baseline_row(handle, row);
    }

    public static function setColumnHomogeneous(int handle, bool homogeneous) -> void
    {
        gtkgrid_set_column_homogeneous(handle, homogeneous);
    }

    public static function setColumnSpacing(int handle, int spacing) -> void
    {
        gtkgrid_set_column_spacing(handle, spacing);
    }

    public static function setRowBaselinePosition(int handle, int row, int pos) -> void
    {
        gtkgrid_set_row_baseline_position(handle, row, pos);
    }

    public static function setRowHomogeneous(int handle, bool homogeneous) -> void
    {
        gtkgrid_set_row_homogeneous(handle, homogeneous);
    }

    public static function setRowSpacing(int handle, int spacing) -> void
    {
        gtkgrid_set_row_spacing(handle, spacing);
    }
}
