// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkToggleButton;

class GtkToggleButton
{
    public static function new_() -> int
    {
        return gtktogglebutton_new();
    }

    public static function newWithLabel(string label) -> int
    {
        return gtktogglebutton_new_with_label(label);
    }

    public static function newWithMnemonic(string label) -> int
    {
        return gtktogglebutton_new_with_mnemonic(label);
    }

    public static function getActive(int handle) -> bool
    {
        int r;

        let r = gtktogglebutton_get_active(handle);

        return r == 1;
    }

    public static function setActive(int handle, bool isActive) -> void
    {
        gtktogglebutton_set_active(handle, isActive);
    }

    public static function setGroup(int handle, int group) -> void
    {
        gtktogglebutton_set_group(handle, group);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_toggle_button_toggled(self) — deprecated

}
