// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkListItem;

class GtkListItem
{
    public static function getAccessibleDescription(int handle) -> string
    {
        var result;

        let result = gtklistitem_get_accessible_description(handle);

        return result;
    }

    public static function getAccessibleLabel(int handle) -> string
    {
        var result;

        let result = gtklistitem_get_accessible_label(handle);

        return result;
    }

    public static function getActivatable(int handle) -> bool
    {
        int r;

        let r = gtklistitem_get_activatable(handle);

        return r == 1;
    }

    public static function getChild(int handle) -> int
    {
        return gtklistitem_get_child(handle);
    }

    public static function getFocusable(int handle) -> bool
    {
        int r;

        let r = gtklistitem_get_focusable(handle);

        return r == 1;
    }

    public static function getItem(int handle) -> int
    {
        return gtklistitem_get_item(handle);
    }

    public static function getPosition(int handle) -> int
    {
        return gtklistitem_get_position(handle);
    }

    public static function getSelectable(int handle) -> bool
    {
        int r;

        let r = gtklistitem_get_selectable(handle);

        return r == 1;
    }

    public static function getSelected(int handle) -> bool
    {
        int r;

        let r = gtklistitem_get_selected(handle);

        return r == 1;
    }

    public static function setAccessibleDescription(int handle, string description) -> void
    {
        gtklistitem_set_accessible_description(handle, description);
    }

    public static function setAccessibleLabel(int handle, string label) -> void
    {
        gtklistitem_set_accessible_label(handle, label);
    }

    public static function setActivatable(int handle, bool activatable) -> void
    {
        gtklistitem_set_activatable(handle, activatable);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtklistitem_set_child(handle, child);
    }

    public static function setFocusable(int handle, bool focusable) -> void
    {
        gtklistitem_set_focusable(handle, focusable);
    }

    public static function setSelectable(int handle, bool selectable) -> void
    {
        gtklistitem_set_selectable(handle, selectable);
    }
}
