// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkTextView;

class GtkTextView
{
    public static function new_() -> int
    {
        return gtktextview_new();
    }

    public static function newWithBuffer(int buffer) -> int
    {
        return gtktextview_new_with_buffer(buffer);
    }

    public static function addChildAtAnchor(int handle, int child, int anchor) -> void
    {
        gtktextview_add_child_at_anchor(handle, child, anchor);
    }

    public static function addOverlay(int handle, int child, int xpos, int ypos) -> void
    {
        gtktextview_add_overlay(handle, child, xpos, ypos);
    }

    public static function bufferToWindowCoords(int handle, int win, int bufferX, int bufferY) -> array
    {
        var result;

        let result = gtktextview_buffer_to_window_coords(handle, win, bufferX, bufferY);

        return result;
    }

    public static function getAcceptsTab(int handle) -> bool
    {
        int r;

        let r = gtktextview_get_accepts_tab(handle);

        return r == 1;
    }

    public static function getBottomMargin(int handle) -> int
    {
        return gtktextview_get_bottom_margin(handle);
    }

    public static function getBuffer(int handle) -> int
    {
        return gtktextview_get_buffer(handle);
    }

    public static function getCursorVisible(int handle) -> bool
    {
        int r;

        let r = gtktextview_get_cursor_visible(handle);

        return r == 1;
    }

    public static function getEditable(int handle) -> bool
    {
        int r;

        let r = gtktextview_get_editable(handle);

        return r == 1;
    }

    public static function getExtraMenu(int handle) -> int
    {
        return gtktextview_get_extra_menu(handle);
    }

    public static function getGutter(int handle, int win) -> int
    {
        return gtktextview_get_gutter(handle, win);
    }

    public static function getIndent(int handle) -> int
    {
        return gtktextview_get_indent(handle);
    }

    public static function getInputHints(int handle) -> int
    {
        return gtktextview_get_input_hints(handle);
    }

    public static function getInputPurpose(int handle) -> int
    {
        return gtktextview_get_input_purpose(handle);
    }

    public static function getJustification(int handle) -> int
    {
        return gtktextview_get_justification(handle);
    }

    public static function getLeftMargin(int handle) -> int
    {
        return gtktextview_get_left_margin(handle);
    }

    public static function getLtrContext(int handle) -> int
    {
        return gtktextview_get_ltr_context(handle);
    }

    public static function getMonospace(int handle) -> bool
    {
        int r;

        let r = gtktextview_get_monospace(handle);

        return r == 1;
    }

    public static function getOverwrite(int handle) -> bool
    {
        int r;

        let r = gtktextview_get_overwrite(handle);

        return r == 1;
    }

    public static function getPixelsAboveLines(int handle) -> int
    {
        return gtktextview_get_pixels_above_lines(handle);
    }

    public static function getPixelsBelowLines(int handle) -> int
    {
        return gtktextview_get_pixels_below_lines(handle);
    }

    public static function getPixelsInsideWrap(int handle) -> int
    {
        return gtktextview_get_pixels_inside_wrap(handle);
    }

    public static function getRightMargin(int handle) -> int
    {
        return gtktextview_get_right_margin(handle);
    }

    public static function getRtlContext(int handle) -> int
    {
        return gtktextview_get_rtl_context(handle);
    }

    public static function getTopMargin(int handle) -> int
    {
        return gtktextview_get_top_margin(handle);
    }

    public static function getVisibleOffset(int handle) -> array
    {
        var result;

        let result = gtktextview_get_visible_offset(handle);

        return result;
    }

    public static function getVisibleRect(int handle) -> array
    {
        var result;

        let result = gtktextview_get_visible_rect(handle);

        return result;
    }

    public static function getWrapMode(int handle) -> int
    {
        return gtktextview_get_wrap_mode(handle);
    }

    public static function imContextFilterKeypress(int handle, int event) -> bool
    {
        int r;

        let r = gtktextview_im_context_filter_keypress(handle, event);

        return r == 1;
    }

    public static function moveMarkOnscreen(int handle, int mark) -> bool
    {
        int r;

        let r = gtktextview_move_mark_onscreen(handle, mark);

        return r == 1;
    }

    public static function moveOverlay(int handle, int child, int xpos, int ypos) -> void
    {
        gtktextview_move_overlay(handle, child, xpos, ypos);
    }

    public static function placeCursorOnscreen(int handle) -> bool
    {
        int r;

        let r = gtktextview_place_cursor_onscreen(handle);

        return r == 1;
    }

    public static function remove(int handle, int child) -> void
    {
        gtktextview_remove(handle, child);
    }

    public static function resetCursorBlink(int handle) -> void
    {
        gtktextview_reset_cursor_blink(handle);
    }

    public static function resetImContext(int handle) -> void
    {
        gtktextview_reset_im_context(handle);
    }

    public static function scrollMarkOnscreen(int handle, int mark) -> void
    {
        gtktextview_scroll_mark_onscreen(handle, mark);
    }

    public static function scrollToMark(int handle, int mark, double withinMargin, bool useAlign, double xalign, double yalign) -> void
    {
        gtktextview_scroll_to_mark(handle, mark, withinMargin, useAlign, xalign, yalign);
    }

    public static function setAcceptsTab(int handle, bool acceptsTab) -> void
    {
        gtktextview_set_accepts_tab(handle, acceptsTab);
    }

    public static function setBottomMargin(int handle, int bottomMargin) -> void
    {
        gtktextview_set_bottom_margin(handle, bottomMargin);
    }

    public static function setBuffer(int handle, int buffer) -> void
    {
        gtktextview_set_buffer(handle, buffer);
    }

    public static function setCursorVisible(int handle, bool setting) -> void
    {
        gtktextview_set_cursor_visible(handle, setting);
    }

    public static function setEditable(int handle, bool setting) -> void
    {
        gtktextview_set_editable(handle, setting);
    }

    public static function setExtraMenu(int handle, int model) -> void
    {
        gtktextview_set_extra_menu(handle, model);
    }

    public static function setGutter(int handle, int win, int widget) -> void
    {
        gtktextview_set_gutter(handle, win, widget);
    }

    public static function setIndent(int handle, int indent) -> void
    {
        gtktextview_set_indent(handle, indent);
    }

    public static function setInputHints(int handle, int hints) -> void
    {
        gtktextview_set_input_hints(handle, hints);
    }

    public static function setInputPurpose(int handle, int purpose) -> void
    {
        gtktextview_set_input_purpose(handle, purpose);
    }

    public static function setJustification(int handle, int justification) -> void
    {
        gtktextview_set_justification(handle, justification);
    }

    public static function setLeftMargin(int handle, int leftMargin) -> void
    {
        gtktextview_set_left_margin(handle, leftMargin);
    }

    public static function setMonospace(int handle, bool monospace) -> void
    {
        gtktextview_set_monospace(handle, monospace);
    }

    public static function setOverwrite(int handle, bool overwrite) -> void
    {
        gtktextview_set_overwrite(handle, overwrite);
    }

    public static function setPixelsAboveLines(int handle, int pixelsAboveLines) -> void
    {
        gtktextview_set_pixels_above_lines(handle, pixelsAboveLines);
    }

    public static function setPixelsBelowLines(int handle, int pixelsBelowLines) -> void
    {
        gtktextview_set_pixels_below_lines(handle, pixelsBelowLines);
    }

    public static function setPixelsInsideWrap(int handle, int pixelsInsideWrap) -> void
    {
        gtktextview_set_pixels_inside_wrap(handle, pixelsInsideWrap);
    }

    public static function setRightMargin(int handle, int rightMargin) -> void
    {
        gtktextview_set_right_margin(handle, rightMargin);
    }

    public static function setTopMargin(int handle, int topMargin) -> void
    {
        gtktextview_set_top_margin(handle, topMargin);
    }

    public static function setWrapMode(int handle, int wrapMode) -> void
    {
        gtktextview_set_wrap_mode(handle, wrapMode);
    }

    public static function windowToBufferCoords(int handle, int win, int windowX, int windowY) -> array
    {
        var result;

        let result = gtktextview_window_to_buffer_coords(handle, win, windowX, windowY);

        return result;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "im-module" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved gtk_text_view_backward_display_line(GtkTextIter* iter) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_backward_display_line_start(GtkTextIter* iter) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_forward_display_line(GtkTextIter* iter) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_forward_display_line_end(GtkTextIter* iter) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_get_cursor_locations(const GtkTextIter* iter, GdkRectangle* strong, GdkRectangle* weak) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_get_iter_at_location(GtkTextIter* iter, int x, int y) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_get_iter_at_position(GtkTextIter* iter, int* trailing, int x, int y) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_get_iter_location(const GtkTextIter* iter, GdkRectangle* location) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_get_line_at_y(GtkTextIter* target_iter, int y, int* line_top) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_get_line_yrange(const GtkTextIter* iter, int* y, int* height) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_get_tabs(void) — PangoTabArray*
    // @reserved gtk_text_view_move_visually(GtkTextIter* iter, int count) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_scroll_to_iter(GtkTextIter* iter, double within_margin, gboolean use_align, double xalign, double yalign) — GtkTextIter* / stack boxed
    // @reserved gtk_text_view_set_tabs(PangoTabArray* tabs) — PangoTabArray*
    // @reserved gtk_text_view_starts_display_line(const GtkTextIter* iter) — GtkTextIter* / stack boxed

}
