// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkStringObject;

class GtkStringObject
{
    public static function new_(string string_) -> int
    {
        return gtkstringobject_new(string_);
    }

    public static function getString(int handle) -> var
    {
        var result;

        let result = gtkstringobject_get_string(handle);

        return result;
    }
}
