// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkSearchEntry;

class GtkSearchEntry
{
    public static function new_() -> int
    {
        return gtksearchentry_new();
    }

    public static function getInputHints(int handle) -> int
    {
        return gtksearchentry_get_input_hints(handle);
    }

    public static function getInputPurpose(int handle) -> int
    {
        return gtksearchentry_get_input_purpose(handle);
    }

    public static function getKeyCaptureWidget(int handle) -> int
    {
        return gtksearchentry_get_key_capture_widget(handle);
    }

    public static function getPlaceholderText(int handle) -> var
    {
        var result;

        let result = gtksearchentry_get_placeholder_text(handle);

        return result;
    }

    public static function getSearchDelay(int handle) -> int
    {
        return gtksearchentry_get_search_delay(handle);
    }

    public static function setInputHints(int handle, int hints) -> void
    {
        gtksearchentry_set_input_hints(handle, hints);
    }

    public static function setInputPurpose(int handle, int purpose) -> void
    {
        gtksearchentry_set_input_purpose(handle, purpose);
    }

    public static function setKeyCaptureWidget(int handle, int widget) -> void
    {
        gtksearchentry_set_key_capture_widget(handle, widget);
    }

    public static function setPlaceholderText(int handle, var text) -> void
    {
        gtksearchentry_set_placeholder_text(handle, text);
    }

    public static function setSearchDelay(int handle, int delay) -> void
    {
        gtksearchentry_set_search_delay(handle, delay);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "activates-default" — no C accessor; use Bridge::getProperty/setProperty

}
