
extern zend_class_entry *gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_ce;

ZEPHIR_INIT_CLASS(Gtk_Gtk_GtkEventControllerMotion_GtkEventControllerMotion);

PHP_METHOD(Gtk_Gtk_GtkEventControllerMotion_GtkEventControllerMotion, new_);
PHP_METHOD(Gtk_Gtk_GtkEventControllerMotion_GtkEventControllerMotion, containsPointer);
PHP_METHOD(Gtk_Gtk_GtkEventControllerMotion_GtkEventControllerMotion, isPointer);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_containspointer, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_ispointer, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_method_entry) {
	PHP_ME(Gtk_Gtk_GtkEventControllerMotion_GtkEventControllerMotion, new_, arginfo_gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkEventControllerMotion_GtkEventControllerMotion, containsPointer, arginfo_gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_containspointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkEventControllerMotion_GtkEventControllerMotion, isPointer, arginfo_gtk_gtk_gtkeventcontrollermotion_gtkeventcontrollermotion_ispointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
