// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkOrientable;

class GtkOrientable
{
    public static function getOrientation(int handle) -> int
    {
        return gtkorientable_get_orientation(handle);
    }

    public static function setOrientation(int handle, int orientation) -> void
    {
        gtkorientable_set_orientation(handle, orientation);
    }
}
