// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkPopoverMenu;

class GtkPopoverMenu
{
    public static function newFromModel(int model) -> int
    {
        return gtkpopovermenu_new_from_model(model);
    }

    public static function newFromModelFull(int model, int flags) -> int
    {
        return gtkpopovermenu_new_from_model_full(model, flags);
    }

    public static function addChild(int handle, int child, string id) -> bool
    {
        int r;

        let r = gtkpopovermenu_add_child(handle, child, id);

        return r == 1;
    }

    public static function getFlags(int handle) -> int
    {
        return gtkpopovermenu_get_flags(handle);
    }

    public static function getMenuModel(int handle) -> int
    {
        return gtkpopovermenu_get_menu_model(handle);
    }

    public static function removeChild(int handle, int child) -> bool
    {
        int r;

        let r = gtkpopovermenu_remove_child(handle, child);

        return r == 1;
    }

    public static function setFlags(int handle, int flags) -> void
    {
        gtkpopovermenu_set_flags(handle, flags);
    }

    public static function setMenuModel(int handle, int model) -> void
    {
        gtkpopovermenu_set_menu_model(handle, model);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "visible-submenu" — no dedicated C accessor; use Bridge::getProperty/setProperty

}
