
extern zend_class_entry *gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_ce;

ZEPHIR_INIT_CLASS(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey);

PHP_METHOD(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, new_);
PHP_METHOD(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, forward);
PHP_METHOD(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, getGroup);
PHP_METHOD(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, getImContext);
PHP_METHOD(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, setImContext);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_forward, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, widget, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_getgroup, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_getimcontext, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_setimcontext, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, imContext, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_method_entry) {
	PHP_ME(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, new_, arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, forward, arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_forward, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, getGroup, arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_getgroup, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, getImContext, arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_getimcontext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Gtk_Gtk_GtkEventControllerKey_GtkEventControllerKey, setImContext, arginfo_gtk_gtk_gtkeventcontrollerkey_gtkeventcontrollerkey_setimcontext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
