// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkPaned;

class GtkPaned
{
    public static function new_(int orientation) -> int
    {
        return gtkpaned_new(orientation);
    }

    public static function getEndChild(int handle) -> int
    {
        return gtkpaned_get_end_child(handle);
    }

    public static function getPosition(int handle) -> int
    {
        return gtkpaned_get_position(handle);
    }

    public static function getResizeEndChild(int handle) -> bool
    {
        int r;

        let r = gtkpaned_get_resize_end_child(handle);

        return r == 1;
    }

    public static function getResizeStartChild(int handle) -> bool
    {
        int r;

        let r = gtkpaned_get_resize_start_child(handle);

        return r == 1;
    }

    public static function getShrinkEndChild(int handle) -> bool
    {
        int r;

        let r = gtkpaned_get_shrink_end_child(handle);

        return r == 1;
    }

    public static function getShrinkStartChild(int handle) -> bool
    {
        int r;

        let r = gtkpaned_get_shrink_start_child(handle);

        return r == 1;
    }

    public static function getStartChild(int handle) -> int
    {
        return gtkpaned_get_start_child(handle);
    }

    public static function getWideHandle(int handle) -> bool
    {
        int r;

        let r = gtkpaned_get_wide_handle(handle);

        return r == 1;
    }

    public static function setEndChild(int handle, int child) -> void
    {
        gtkpaned_set_end_child(handle, child);
    }

    public static function setPosition(int handle, int position) -> void
    {
        gtkpaned_set_position(handle, position);
    }

    public static function setResizeEndChild(int handle, bool resize) -> void
    {
        gtkpaned_set_resize_end_child(handle, resize);
    }

    public static function setResizeStartChild(int handle, bool resize) -> void
    {
        gtkpaned_set_resize_start_child(handle, resize);
    }

    public static function setShrinkEndChild(int handle, bool resize) -> void
    {
        gtkpaned_set_shrink_end_child(handle, resize);
    }

    public static function setShrinkStartChild(int handle, bool resize) -> void
    {
        gtkpaned_set_shrink_start_child(handle, resize);
    }

    public static function setStartChild(int handle, int child) -> void
    {
        gtkpaned_set_start_child(handle, child);
    }

    public static function setWideHandle(int handle, bool wide) -> void
    {
        gtkpaned_set_wide_handle(handle, wide);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "max-position" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "min-position" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved property "position-set" — no dedicated C accessor; use Bridge::getProperty/setProperty

}
