// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkEventControllerMotion;

class GtkEventControllerMotion
{
    public static function new_() -> int
    {
        return gtkeventcontrollermotion_new();
    }

    public static function containsPointer(int handle) -> bool
    {
        int r;

        let r = gtkeventcontrollermotion_contains_pointer(handle);

        return r == 1;
    }

    public static function isPointer(int handle) -> bool
    {
        int r;

        let r = gtkeventcontrollermotion_is_pointer(handle);

        return r == 1;
    }
}
