// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GAction;

class GAction
{
    public static function nameIsValid(string actionName) -> bool
    {
        int r;

        let r = gaction_name_is_valid(actionName);

        return r == 1;
    }

    public static function getEnabled(int handle) -> bool
    {
        int r;

        let r = gaction_get_enabled(handle);

        return r == 1;
    }

    public static function getName(int handle) -> var
    {
        var result;

        let result = gaction_get_name(handle);

        return result;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved g_action_parse_detailed_name(detailed_name, action_name, target_value) — GError** / GVariant**
    // @reserved g_action_print_detailed_name(action_name, GVariant* target_value) — GVariant*
    // @reserved g_action_activate(self, GVariant* parameter) — GVariant*
    // @reserved g_action_change_state(self, GVariant* value) — GVariant*
    // @reserved g_action_get_parameter_type(self) — GVariantType*
    // @reserved g_action_get_state(self) — GVariant*
    // @reserved g_action_get_state_hint(self) — GVariant*
    // @reserved g_action_get_state_type(self) — GVariantType*

}
