// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkLevelBar;

class GtkLevelBar
{
    public static function new_() -> int
    {
        return gtklevelbar_new();
    }

    public static function newForInterval(double minValue, double maxValue) -> int
    {
        return gtklevelbar_new_for_interval(minValue, maxValue);
    }

    public static function addOffsetValue(int handle, string name, double value) -> void
    {
        gtklevelbar_add_offset_value(handle, name, value);
    }

    public static function getInverted(int handle) -> bool
    {
        int r;

        let r = gtklevelbar_get_inverted(handle);

        return r == 1;
    }

    public static function getMaxValue(int handle) -> double
    {
        return gtklevelbar_get_max_value(handle);
    }

    public static function getMinValue(int handle) -> double
    {
        return gtklevelbar_get_min_value(handle);
    }

    public static function getMode(int handle) -> int
    {
        return gtklevelbar_get_mode(handle);
    }

    public static function getOffsetValue(int handle, var name) -> array
    {
        var result;

        let result = gtklevelbar_get_offset_value(handle, name);

        return result;
    }

    public static function getValue(int handle) -> double
    {
        return gtklevelbar_get_value(handle);
    }

    public static function removeOffsetValue(int handle, var name) -> void
    {
        gtklevelbar_remove_offset_value(handle, name);
    }

    public static function setInverted(int handle, bool inverted) -> void
    {
        gtklevelbar_set_inverted(handle, inverted);
    }

    public static function setMaxValue(int handle, double value) -> void
    {
        gtklevelbar_set_max_value(handle, value);
    }

    public static function setMinValue(int handle, double value) -> void
    {
        gtklevelbar_set_min_value(handle, value);
    }

    public static function setMode(int handle, int mode) -> void
    {
        gtklevelbar_set_mode(handle, mode);
    }

    public static function setValue(int handle, double value) -> void
    {
        gtklevelbar_set_value(handle, value);
    }
}
