// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkBox;

class GtkBox
{
    public static function new_(int orientation, int spacing) -> int
    {
        return gtkbox_new(orientation, spacing);
    }

    public static function append(int handle, int child) -> void
    {
        gtkbox_append(handle, child);
    }

    public static function getBaselineChild(int handle) -> int
    {
        return gtkbox_get_baseline_child(handle);
    }

    public static function getBaselinePosition(int handle) -> int
    {
        return gtkbox_get_baseline_position(handle);
    }

    public static function getHomogeneous(int handle) -> bool
    {
        int r;

        let r = gtkbox_get_homogeneous(handle);

        return r == 1;
    }

    public static function getSpacing(int handle) -> int
    {
        return gtkbox_get_spacing(handle);
    }

    public static function insertChildAfter(int handle, int child, int sibling) -> void
    {
        gtkbox_insert_child_after(handle, child, sibling);
    }

    public static function prepend(int handle, int child) -> void
    {
        gtkbox_prepend(handle, child);
    }

    public static function remove(int handle, int child) -> void
    {
        gtkbox_remove(handle, child);
    }

    public static function reorderChildAfter(int handle, int child, int sibling) -> void
    {
        gtkbox_reorder_child_after(handle, child, sibling);
    }

    public static function setBaselineChild(int handle, int child) -> void
    {
        gtkbox_set_baseline_child(handle, child);
    }

    public static function setBaselinePosition(int handle, int position) -> void
    {
        gtkbox_set_baseline_position(handle, position);
    }

    public static function setHomogeneous(int handle, bool homogeneous) -> void
    {
        gtkbox_set_homogeneous(handle, homogeneous);
    }

    public static function setSpacing(int handle, int spacing) -> void
    {
        gtkbox_set_spacing(handle, spacing);
    }
}
