// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkColumnView;

class GtkColumnView
{
    public static function new_(int model) -> int
    {
        return gtkcolumnview_new(model);
    }

    public static function appendColumn(int handle, int column) -> void
    {
        gtkcolumnview_append_column(handle, column);
    }

    public static function getColumns(int handle) -> int
    {
        return gtkcolumnview_get_columns(handle);
    }

    public static function getEnableRubberband(int handle) -> bool
    {
        int r;

        let r = gtkcolumnview_get_enable_rubberband(handle);

        return r == 1;
    }

    public static function getHeaderFactory(int handle) -> int
    {
        return gtkcolumnview_get_header_factory(handle);
    }

    public static function getModel(int handle) -> int
    {
        return gtkcolumnview_get_model(handle);
    }

    public static function getReorderable(int handle) -> bool
    {
        int r;

        let r = gtkcolumnview_get_reorderable(handle);

        return r == 1;
    }

    public static function getRowFactory(int handle) -> int
    {
        return gtkcolumnview_get_row_factory(handle);
    }

    public static function getShowColumnSeparators(int handle) -> bool
    {
        int r;

        let r = gtkcolumnview_get_show_column_separators(handle);

        return r == 1;
    }

    public static function getShowRowSeparators(int handle) -> bool
    {
        int r;

        let r = gtkcolumnview_get_show_row_separators(handle);

        return r == 1;
    }

    public static function getSingleClickActivate(int handle) -> bool
    {
        int r;

        let r = gtkcolumnview_get_single_click_activate(handle);

        return r == 1;
    }

    public static function getTabBehavior(int handle) -> int
    {
        return gtkcolumnview_get_tab_behavior(handle);
    }

    public static function insertColumn(int handle, int position, int column) -> void
    {
        gtkcolumnview_insert_column(handle, position, column);
    }

    public static function removeColumn(int handle, int column) -> void
    {
        gtkcolumnview_remove_column(handle, column);
    }

    public static function setEnableRubberband(int handle, bool enableRubberband) -> void
    {
        gtkcolumnview_set_enable_rubberband(handle, enableRubberband);
    }

    public static function setHeaderFactory(int handle, int factory) -> void
    {
        gtkcolumnview_set_header_factory(handle, factory);
    }

    public static function setModel(int handle, int model) -> void
    {
        gtkcolumnview_set_model(handle, model);
    }

    public static function setReorderable(int handle, bool reorderable) -> void
    {
        gtkcolumnview_set_reorderable(handle, reorderable);
    }

    public static function setRowFactory(int handle, int factory) -> void
    {
        gtkcolumnview_set_row_factory(handle, factory);
    }

    public static function setShowColumnSeparators(int handle, bool showColumnSeparators) -> void
    {
        gtkcolumnview_set_show_column_separators(handle, showColumnSeparators);
    }

    public static function setShowRowSeparators(int handle, bool showRowSeparators) -> void
    {
        gtkcolumnview_set_show_row_separators(handle, showRowSeparators);
    }

    public static function setSingleClickActivate(int handle, bool singleClickActivate) -> void
    {
        gtkcolumnview_set_single_click_activate(handle, singleClickActivate);
    }

    public static function setTabBehavior(int handle, int tabBehavior) -> void
    {
        gtkcolumnview_set_tab_behavior(handle, tabBehavior);
    }

    public static function sortByColumn(int handle, int column, int direction) -> void
    {
        gtkcolumnview_sort_by_column(handle, column, direction);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_column_view_get_sorter() — GtkSorter*
    // @reserved gtk_column_view_scroll_to(pos, column, flags, GtkScrollInfo* scroll) — GtkScrollInfo* boxed

}
