// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkEventControllerKey;

class GtkEventControllerKey
{
    public static function new_() -> int
    {
        return gtkeventcontrollerkey_new();
    }

    public static function forward(int handle, int widget) -> bool
    {
        int r;

        let r = gtkeventcontrollerkey_forward(handle, widget);

        return r == 1;
    }

    public static function getGroup(int handle) -> int
    {
        return gtkeventcontrollerkey_get_group(handle);
    }

    public static function getImContext(int handle) -> int
    {
        return gtkeventcontrollerkey_get_im_context(handle);
    }

    public static function setImContext(int handle, int imContext) -> void
    {
        gtkeventcontrollerkey_set_im_context(handle, imContext);
    }
}
