// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkStackSwitcher;

class GtkStackSwitcher
{
    public static function new_() -> int
    {
        return gtkstackswitcher_new();
    }

    public static function getStack(int handle) -> int
    {
        return gtkstackswitcher_get_stack(handle);
    }

    public static function setStack(int handle, int stack) -> void
    {
        gtkstackswitcher_set_stack(handle, stack);
    }
}
