// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkCssProvider;

class GtkCssProvider
{
    public static function new_() -> int
    {
        return cssprovider_new();
    }

    public static function loadFromString(int handle, string css) -> void
    {
        cssprovider_load_from_string(handle, css);
    }

    public static function loadFromPath(int handle, string path) -> void
    {
        cssprovider_load_from_path(handle, path);
    }

    public static function toString(int handle) -> string
    {
        var result;

        let result = cssprovider_to_string(handle);

        return result;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_css_provider_load_from_bytes(self, bytes) — GBytes*
    // @reserved gtk_css_provider_load_from_data(self, data, length) — deprecated 4.12, use load_from_string
    // @reserved gtk_css_provider_load_from_file(self, file) — GFile*
    // @reserved gtk_css_provider_load_from_resource(self, resource_path) — GResource path, no resource bundle in PHPland
    // @reserved gtk_css_provider_load_named(self, name, variant) — theme loading, not app styling

}
