// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkStack;

class GtkStack
{
    public static function new_() -> int
    {
        return gtkstack_new();
    }

    public static function addChild(int handle, int child) -> int
    {
        return gtkstack_add_child(handle, child);
    }

    public static function addNamed(int handle, int child, var name) -> int
    {
        return gtkstack_add_named(handle, child, name);
    }

    public static function addTitled(int handle, int child, var name, string title) -> int
    {
        return gtkstack_add_titled(handle, child, name, title);
    }

    public static function getChildByName(int handle, string name) -> int
    {
        return gtkstack_get_child_by_name(handle, name);
    }

    public static function getHhomogeneous(int handle) -> bool
    {
        int r;

        let r = gtkstack_get_hhomogeneous(handle);

        return r == 1;
    }

    public static function getInterpolateSize(int handle) -> bool
    {
        int r;

        let r = gtkstack_get_interpolate_size(handle);

        return r == 1;
    }

    public static function getPage(int handle, int child) -> int
    {
        return gtkstack_get_page(handle, child);
    }

    public static function getPages(int handle) -> int
    {
        return gtkstack_get_pages(handle);
    }

    public static function getTransitionDuration(int handle) -> int
    {
        return gtkstack_get_transition_duration(handle);
    }

    public static function getTransitionRunning(int handle) -> bool
    {
        int r;

        let r = gtkstack_get_transition_running(handle);

        return r == 1;
    }

    public static function getTransitionType(int handle) -> int
    {
        return gtkstack_get_transition_type(handle);
    }

    public static function getVhomogeneous(int handle) -> bool
    {
        int r;

        let r = gtkstack_get_vhomogeneous(handle);

        return r == 1;
    }

    public static function getVisibleChild(int handle) -> int
    {
        return gtkstack_get_visible_child(handle);
    }

    public static function getVisibleChildName(int handle) -> var
    {
        var result;

        let result = gtkstack_get_visible_child_name(handle);

        return result;
    }

    public static function remove(int handle, int child) -> void
    {
        gtkstack_remove(handle, child);
    }

    public static function setHhomogeneous(int handle, bool hhomogeneous) -> void
    {
        gtkstack_set_hhomogeneous(handle, hhomogeneous);
    }

    public static function setInterpolateSize(int handle, bool interpolateSize) -> void
    {
        gtkstack_set_interpolate_size(handle, interpolateSize);
    }

    public static function setTransitionDuration(int handle, int duration) -> void
    {
        gtkstack_set_transition_duration(handle, duration);
    }

    public static function setTransitionType(int handle, int transition) -> void
    {
        gtkstack_set_transition_type(handle, transition);
    }

    public static function setVhomogeneous(int handle, bool vhomogeneous) -> void
    {
        gtkstack_set_vhomogeneous(handle, vhomogeneous);
    }

    public static function setVisibleChild(int handle, int child) -> void
    {
        gtkstack_set_visible_child(handle, child);
    }

    public static function setVisibleChildFull(int handle, string name, int transition) -> void
    {
        gtkstack_set_visible_child_full(handle, name, transition);
    }

    public static function setVisibleChildName(int handle, string name) -> void
    {
        gtkstack_set_visible_child_name(handle, name);
    }
}
