// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkFrame;

class GtkFrame
{
    public static function new_(var label) -> int
    {
        return gtkframe_new(label);
    }

    public static function getChild(int handle) -> int
    {
        return gtkframe_get_child(handle);
    }

    public static function getLabel(int handle) -> var
    {
        var result;

        let result = gtkframe_get_label(handle);

        return result;
    }

    public static function getLabelAlign(int handle) -> double
    {
        return gtkframe_get_label_align(handle);
    }

    public static function getLabelWidget(int handle) -> int
    {
        return gtkframe_get_label_widget(handle);
    }

    public static function setChild(int handle, int child) -> void
    {
        gtkframe_set_child(handle, child);
    }

    public static function setLabel(int handle, var label) -> void
    {
        gtkframe_set_label(handle, label);
    }

    public static function setLabelAlign(int handle, double xalign) -> void
    {
        gtkframe_set_label_align(handle, xalign);
    }

    public static function setLabelWidget(int handle, int labelWidget) -> void
    {
        gtkframe_set_label_widget(handle, labelWidget);
    }
}
