// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkImage;

class GtkImage
{
    public static function new_() -> int
    {
        return gtkimage_new();
    }

    public static function newFromFile(string filename) -> int
    {
        return gtkimage_new_from_file(filename);
    }

    public static function newFromGicon(int icon) -> int
    {
        return gtkimage_new_from_gicon(icon);
    }

    public static function newFromIconName(var iconName) -> int
    {
        return gtkimage_new_from_icon_name(iconName);
    }

    public static function newFromPaintable(int paintable) -> int
    {
        return gtkimage_new_from_paintable(paintable);
    }

    public static function newFromResource(string resourcePath) -> int
    {
        return gtkimage_new_from_resource(resourcePath);
    }

    public static function clear(int handle) -> void
    {
        gtkimage_clear(handle);
    }

    public static function getGicon(int handle) -> int
    {
        return gtkimage_get_gicon(handle);
    }

    public static function getIconName(int handle) -> var
    {
        var result;

        let result = gtkimage_get_icon_name(handle);

        return result;
    }

    public static function getIconSize(int handle) -> int
    {
        return gtkimage_get_icon_size(handle);
    }

    public static function getPaintable(int handle) -> int
    {
        return gtkimage_get_paintable(handle);
    }

    public static function getPixelSize(int handle) -> int
    {
        return gtkimage_get_pixel_size(handle);
    }

    public static function getStorageType(int handle) -> int
    {
        return gtkimage_get_storage_type(handle);
    }

    public static function setFromFile(int handle, var filename) -> void
    {
        gtkimage_set_from_file(handle, filename);
    }

    public static function setFromGicon(int handle, int icon) -> void
    {
        gtkimage_set_from_gicon(handle, icon);
    }

    public static function setFromIconName(int handle, var iconName) -> void
    {
        gtkimage_set_from_icon_name(handle, iconName);
    }

    public static function setFromPaintable(int handle, int paintable) -> void
    {
        gtkimage_set_from_paintable(handle, paintable);
    }

    public static function setFromResource(int handle, var resourcePath) -> void
    {
        gtkimage_set_from_resource(handle, resourcePath);
    }

    public static function setIconSize(int handle, int iconSize) -> void
    {
        gtkimage_set_icon_size(handle, iconSize);
    }

    public static function setPixelSize(int handle, int pixelSize) -> void
    {
        gtkimage_set_pixel_size(handle, pixelSize);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "file" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "resource" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved property "use-fallback" — no C accessor; use Bridge::getProperty/setProperty
    // @reserved gtk_image_new_from_pixbuf(GdkPixbuf* pixbuf) — deprecated
    // @reserved gtk_image_set_from_pixbuf(GtkImage* image, GdkPixbuf* pixbuf) — deprecated

}
