// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkGestureSingle;

class GtkGestureSingle
{
    public static function getButton(int handle) -> int
    {
        return gtkgesturesingle_get_button(handle);
    }

    public static function getCurrentButton(int handle) -> int
    {
        return gtkgesturesingle_get_current_button(handle);
    }

    public static function getExclusive(int handle) -> bool
    {
        int r;

        let r = gtkgesturesingle_get_exclusive(handle);

        return r == 1;
    }

    public static function getTouchOnly(int handle) -> bool
    {
        int r;

        let r = gtkgesturesingle_get_touch_only(handle);

        return r == 1;
    }

    public static function setButton(int handle, int button) -> void
    {
        gtkgesturesingle_set_button(handle, button);
    }

    public static function setExclusive(int handle, bool exclusive) -> void
    {
        gtkgesturesingle_set_exclusive(handle, exclusive);
    }

    public static function setTouchOnly(int handle, bool touchOnly) -> void
    {
        gtkgesturesingle_set_touch_only(handle, touchOnly);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_gesture_single_get_current_sequence(GtkGestureSingle* gesture) — GdkEventSequence*

}
