// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gio\GListStore;

class GListStore
{
    public static function new_(int itemType) -> int
    {
        return gliststore_new(itemType);
    }

    public static function append(int handle, int item) -> void
    {
        gliststore_append(handle, item);
    }

    public static function find(int handle, int item) -> array
    {
        var result;

        let result = gliststore_find(handle, item);

        return result;
    }

    public static function insert(int handle, int position, int item) -> void
    {
        gliststore_insert(handle, position, item);
    }

    public static function remove(int handle, int position) -> void
    {
        gliststore_remove(handle, position);
    }

    public static function removeAll(int handle) -> void
    {
        gliststore_remove_all(handle);
    }

    public static function splice(int handle, int position, int nRemovals, array additions, int nAdditions) -> void
    {
        gliststore_splice(handle, position, nRemovals, additions, nAdditions);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "item-type" — getter lives on GListModel; construct-only; use Bridge::getProperty
    // @reserved property "n-items" — getter lives on GListModel; use Bridge::getProperty
    // @reserved g_list_store_find_with_equal_func(self, item, GEqualFunc equal_func, position) — non-signal callback
    // @reserved g_list_store_find_with_equal_func_full(self, item, GEqualFuncFull equal_func, user_data, position) — non-signal callback
    // @reserved g_list_store_insert_sorted(self, item, GCompareDataFunc compare_func, user_data) — non-signal callback
    // @reserved g_list_store_sort(self, GCompareDataFunc compare_func, user_data) — non-signal callback

}
