// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkTextTagTable;

class GtkTextTagTable
{
    public static function new_() -> int
    {
        return gtktexttagtable_new();
    }

    public static function add(int handle, int tag) -> bool
    {
        int r;

        let r = gtktexttagtable_add(handle, tag);

        return r == 1;
    }

    public static function getSize(int handle) -> int
    {
        return gtktexttagtable_get_size(handle);
    }

    public static function lookup(int handle, string name) -> int
    {
        return gtktexttagtable_lookup(handle, name);
    }

    public static function remove(int handle, int tag) -> void
    {
        gtktexttagtable_remove(handle, tag);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved gtk_text_tag_table_foreach(GtkTextTagTableForeach func, gpointer data) — non-signal callback

}
