// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkListBox;

class GtkListBox
{
    public static function new_() -> int
    {
        return gtklistbox_new();
    }

    public static function append(int handle, int child) -> void
    {
        gtklistbox_append(handle, child);
    }

    public static function dragHighlightRow(int handle, int row) -> void
    {
        gtklistbox_drag_highlight_row(handle, row);
    }

    public static function dragUnhighlightRow(int handle) -> void
    {
        gtklistbox_drag_unhighlight_row(handle);
    }

    public static function getActivateOnSingleClick(int handle) -> bool
    {
        int r;

        let r = gtklistbox_get_activate_on_single_click(handle);

        return r == 1;
    }

    public static function getAdjustment(int handle) -> int
    {
        return gtklistbox_get_adjustment(handle);
    }

    public static function getRowAtIndex(int handle, int index) -> int
    {
        return gtklistbox_get_row_at_index(handle, index);
    }

    public static function getRowAtY(int handle, int y) -> int
    {
        return gtklistbox_get_row_at_y(handle, y);
    }

    public static function getSelectedRow(int handle) -> int
    {
        return gtklistbox_get_selected_row(handle);
    }

    public static function getSelectedRows(int handle) -> array
    {
        var result;

        let result = gtklistbox_get_selected_rows(handle);

        return result;
    }

    public static function getSelectionMode(int handle) -> int
    {
        return gtklistbox_get_selection_mode(handle);
    }

    public static function getShowSeparators(int handle) -> bool
    {
        int r;

        let r = gtklistbox_get_show_separators(handle);

        return r == 1;
    }

    public static function getTabBehavior(int handle) -> int
    {
        return gtklistbox_get_tab_behavior(handle);
    }

    public static function insert(int handle, int child, int position) -> void
    {
        gtklistbox_insert(handle, child, position);
    }

    public static function invalidateFilter(int handle) -> void
    {
        gtklistbox_invalidate_filter(handle);
    }

    public static function invalidateHeaders(int handle) -> void
    {
        gtklistbox_invalidate_headers(handle);
    }

    public static function invalidateSort(int handle) -> void
    {
        gtklistbox_invalidate_sort(handle);
    }

    public static function prepend(int handle, int child) -> void
    {
        gtklistbox_prepend(handle, child);
    }

    public static function remove(int handle, int child) -> void
    {
        gtklistbox_remove(handle, child);
    }

    public static function removeAll(int handle) -> void
    {
        gtklistbox_remove_all(handle);
    }

    public static function selectAll(int handle) -> void
    {
        gtklistbox_select_all(handle);
    }

    public static function selectRow(int handle, int row) -> void
    {
        gtklistbox_select_row(handle, row);
    }

    public static function setActivateOnSingleClick(int handle, bool single) -> void
    {
        gtklistbox_set_activate_on_single_click(handle, single);
    }

    public static function setAdjustment(int handle, int adjustment) -> void
    {
        gtklistbox_set_adjustment(handle, adjustment);
    }

    public static function setPlaceholder(int handle, int placeholder) -> void
    {
        gtklistbox_set_placeholder(handle, placeholder);
    }

    public static function setSelectionMode(int handle, int mode) -> void
    {
        gtklistbox_set_selection_mode(handle, mode);
    }

    public static function setShowSeparators(int handle, bool showSeparators) -> void
    {
        gtklistbox_set_show_separators(handle, showSeparators);
    }

    public static function setTabBehavior(int handle, int behavior) -> void
    {
        gtklistbox_set_tab_behavior(handle, behavior);
    }

    public static function unselectAll(int handle) -> void
    {
        gtklistbox_unselect_all(handle);
    }

    public static function unselectRow(int handle, int row) -> void
    {
        gtklistbox_unselect_row(handle, row);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "accept-unpaired-release" — no dedicated C accessor; use Bridge::getProperty/setProperty
    // @reserved gtk_list_box_bind_model(GListModel* model, GtkListBoxCreateWidgetFunc create_widget_func, gpointer user_data, GDestroyNotify user_data_free_func) — non-signal callback
    // @reserved gtk_list_box_selected_foreach(GtkListBoxForeachFunc func, gpointer data) — non-signal callback
    // @reserved gtk_list_box_set_filter_func(GtkListBoxFilterFunc filter_func, gpointer user_data, GDestroyNotify destroy) — non-signal callback
    // @reserved gtk_list_box_set_header_func(GtkListBoxUpdateHeaderFunc update_header, gpointer user_data, GDestroyNotify destroy) — non-signal callback
    // @reserved gtk_list_box_set_sort_func(GtkListBoxSortFunc sort_func, gpointer user_data, GDestroyNotify destroy) — non-signal callback

}
