// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Gtk\Gtk\GtkNotebook;

class GtkNotebook
{
    public static function new_() -> int
    {
        return gtknotebook_new();
    }

    public static function appendPage(int handle, int child, int tabLabel) -> int
    {
        return gtknotebook_append_page(handle, child, tabLabel);
    }

    public static function appendPageMenu(int handle, int child, int tabLabel, int menuLabel) -> int
    {
        return gtknotebook_append_page_menu(handle, child, tabLabel, menuLabel);
    }

    public static function detachTab(int handle, int child) -> void
    {
        gtknotebook_detach_tab(handle, child);
    }

    public static function getActionWidget(int handle, int packType) -> int
    {
        return gtknotebook_get_action_widget(handle, packType);
    }

    public static function getCurrentPage(int handle) -> int
    {
        return gtknotebook_get_current_page(handle);
    }

    public static function getGroupName(int handle) -> var
    {
        var result;

        let result = gtknotebook_get_group_name(handle);

        return result;
    }

    public static function getMenuLabel(int handle, int child) -> int
    {
        return gtknotebook_get_menu_label(handle, child);
    }

    public static function getMenuLabelText(int handle, int child) -> var
    {
        var result;

        let result = gtknotebook_get_menu_label_text(handle, child);

        return result;
    }

    public static function getNPages(int handle) -> int
    {
        return gtknotebook_get_n_pages(handle);
    }

    public static function getNthPage(int handle, int pageNum) -> int
    {
        return gtknotebook_get_nth_page(handle, pageNum);
    }

    public static function getPage(int handle, int child) -> int
    {
        return gtknotebook_get_page(handle, child);
    }

    public static function getPages(int handle) -> int
    {
        return gtknotebook_get_pages(handle);
    }

    public static function getScrollable(int handle) -> bool
    {
        int r;

        let r = gtknotebook_get_scrollable(handle);

        return r == 1;
    }

    public static function getShowBorder(int handle) -> bool
    {
        int r;

        let r = gtknotebook_get_show_border(handle);

        return r == 1;
    }

    public static function getShowTabs(int handle) -> bool
    {
        int r;

        let r = gtknotebook_get_show_tabs(handle);

        return r == 1;
    }

    public static function getTabDetachable(int handle, int child) -> bool
    {
        int r;

        let r = gtknotebook_get_tab_detachable(handle, child);

        return r == 1;
    }

    public static function getTabLabel(int handle, int child) -> int
    {
        return gtknotebook_get_tab_label(handle, child);
    }

    public static function getTabLabelText(int handle, int child) -> var
    {
        var result;

        let result = gtknotebook_get_tab_label_text(handle, child);

        return result;
    }

    public static function getTabPos(int handle) -> int
    {
        return gtknotebook_get_tab_pos(handle);
    }

    public static function getTabReorderable(int handle, int child) -> bool
    {
        int r;

        let r = gtknotebook_get_tab_reorderable(handle, child);

        return r == 1;
    }

    public static function insertPage(int handle, int child, int tabLabel, int position) -> int
    {
        return gtknotebook_insert_page(handle, child, tabLabel, position);
    }

    public static function insertPageMenu(int handle, int child, int tabLabel, int menuLabel, int position) -> int
    {
        return gtknotebook_insert_page_menu(handle, child, tabLabel, menuLabel, position);
    }

    public static function nextPage(int handle) -> void
    {
        gtknotebook_next_page(handle);
    }

    public static function pageNum(int handle, int child) -> int
    {
        return gtknotebook_page_num(handle, child);
    }

    public static function popupDisable(int handle) -> void
    {
        gtknotebook_popup_disable(handle);
    }

    public static function popupEnable(int handle) -> void
    {
        gtknotebook_popup_enable(handle);
    }

    public static function prependPage(int handle, int child, int tabLabel) -> int
    {
        return gtknotebook_prepend_page(handle, child, tabLabel);
    }

    public static function prependPageMenu(int handle, int child, int tabLabel, int menuLabel) -> int
    {
        return gtknotebook_prepend_page_menu(handle, child, tabLabel, menuLabel);
    }

    public static function prevPage(int handle) -> void
    {
        gtknotebook_prev_page(handle);
    }

    public static function removePage(int handle, int pageNum) -> void
    {
        gtknotebook_remove_page(handle, pageNum);
    }

    public static function reorderChild(int handle, int child, int position) -> void
    {
        gtknotebook_reorder_child(handle, child, position);
    }

    public static function setActionWidget(int handle, int widget, int packType) -> void
    {
        gtknotebook_set_action_widget(handle, widget, packType);
    }

    public static function setCurrentPage(int handle, int pageNum) -> void
    {
        gtknotebook_set_current_page(handle, pageNum);
    }

    public static function setGroupName(int handle, var groupName) -> void
    {
        gtknotebook_set_group_name(handle, groupName);
    }

    public static function setMenuLabel(int handle, int child, int menuLabel) -> void
    {
        gtknotebook_set_menu_label(handle, child, menuLabel);
    }

    public static function setMenuLabelText(int handle, int child, string menuText) -> void
    {
        gtknotebook_set_menu_label_text(handle, child, menuText);
    }

    public static function setScrollable(int handle, bool scrollable) -> void
    {
        gtknotebook_set_scrollable(handle, scrollable);
    }

    public static function setShowBorder(int handle, bool showBorder) -> void
    {
        gtknotebook_set_show_border(handle, showBorder);
    }

    public static function setShowTabs(int handle, bool showTabs) -> void
    {
        gtknotebook_set_show_tabs(handle, showTabs);
    }

    public static function setTabDetachable(int handle, int child, bool detachable) -> void
    {
        gtknotebook_set_tab_detachable(handle, child, detachable);
    }

    public static function setTabLabel(int handle, int child, int tabLabel) -> void
    {
        gtknotebook_set_tab_label(handle, child, tabLabel);
    }

    public static function setTabLabelText(int handle, int child, string tabText) -> void
    {
        gtknotebook_set_tab_label_text(handle, child, tabText);
    }

    public static function setTabPos(int handle, int pos) -> void
    {
        gtknotebook_set_tab_pos(handle, pos);
    }

    public static function setTabReorderable(int handle, int child, bool reorderable) -> void
    {
        gtknotebook_set_tab_reorderable(handle, child, reorderable);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved property "enable-popup" — no dedicated C accessor; use Bridge::getProperty/setProperty

}
